export interface RomanVariantGoldCase {
  roman: string;
  canonicalDevanagari: string;
  category: 'q/k' | 'kh/x' | 'ph/f' | 'z/j' | 'v/w' | 'vowel length' | 'slang/english';
  notes: string;
}

export const ROMAN_VARIANTS_CASES: RomanVariantGoldCase[] = [
  // =========================================================================
  // 1. Q vs K PERSO-ARABIC VARIATIONS (25 ENTRIES)
  // =========================================================================
  { roman: 'qudrat', canonicalDevanagari: 'क़ुदरत', category: 'q/k', notes: 'Urdu uvular /q/ standard transliteration' },
  { roman: 'kudrat', canonicalDevanagari: 'क़ुदरत', category: 'q/k', notes: 'Hindi conversational velar /k/ transliteration' },
  { roman: 'haqeeqat', canonicalDevanagari: 'हक़ीक़त', category: 'q/k', notes: 'Double uvular q standard' },
  { roman: 'hakikat', canonicalDevanagari: 'हक़ीक़त', category: 'q/k', notes: 'Double velar k variant' },
  { roman: 'haqiqat', canonicalDevanagari: 'हक़ीक़त', category: 'q/k', notes: 'Single i vowel spelling' },
  { roman: 'qafiya', canonicalDevanagari: 'क़ाफ़िया', category: 'q/k', notes: 'Technical ghazal term with q' },
  { roman: 'kafiya', canonicalDevanagari: 'क़ाफ़िया', category: 'q/k', notes: 'Conversational k spelling' },
  { roman: 'qareeb', canonicalDevanagari: 'क़रीब', category: 'q/k', notes: 'q transliteration' },
  { roman: 'karib', canonicalDevanagari: 'क़रीब', category: 'q/k', notes: 'k transliteration' },
  { roman: 'kareeb', canonicalDevanagari: 'क़रीब', category: 'q/k', notes: 'ee vowel spelling with k' },
  { roman: 'auqaat', canonicalDevanagari: 'औक़ात', category: 'q/k', notes: 'Diphthong au + q' },
  { roman: 'aukat', canonicalDevanagari: 'औक़ात', category: 'q/k', notes: 'Diphthong au + k' },
  { roman: 'mulaqaat', canonicalDevanagari: 'मुलाक़ात', category: 'q/k', notes: 'Perso-Arabic q spelling' },
  { roman: 'mulakat', canonicalDevanagari: 'मुलाक़ात', category: 'q/k', notes: 'Conversational k spelling' },
  { roman: 'ishq', canonicalDevanagari: 'इश्क़', category: 'q/k', notes: 'Classic q coda' },
  { roman: 'ishk', canonicalDevanagari: 'इश्क़', category: 'q/k', notes: 'Conversational k coda' },
  { roman: 'shauq', canonicalDevanagari: 'शौक़', category: 'q/k', notes: 'Classic q coda' },
  { roman: 'shauk', canonicalDevanagari: 'शौक़', category: 'q/k', notes: 'Conversational k coda' },
  { roman: 'taqdeer', canonicalDevanagari: 'तक़दीर', category: 'q/k', notes: 'Medial q spelling' },
  { roman: 'takdir', canonicalDevanagari: 'तक़दीर', category: 'q/k', notes: 'Medial k spelling' },
  { roman: 'faqeer', canonicalDevanagari: 'फकीर', category: 'q/k', notes: 'Medial q spelling' },
  { roman: 'fakir', canonicalDevanagari: 'फकीर', category: 'q/k', notes: 'Medial k spelling' },
  { roman: 'qalam', canonicalDevanagari: 'क़लम', category: 'q/k', notes: 'Initial q spelling' },
  { roman: 'kalam', canonicalDevanagari: 'क़लम', category: 'q/k', notes: 'Initial k spelling' },
  { roman: 'inqilaab', canonicalDevanagari: 'इंक़लाब', category: 'q/k', notes: 'Medial q spelling' },

  // =========================================================================
  // 2. KH vs X PERSO-ARABIC VARIATIONS (25 ENTRIES)
  // =========================================================================
  { roman: 'khwab', canonicalDevanagari: 'ख़्वाब', category: 'kh/x', notes: 'Standard kh transliteration' },
  { roman: 'khwaab', canonicalDevanagari: 'ख़्वाब', category: 'kh/x', notes: 'Double aa spelling' },
  { roman: 'xwaab', canonicalDevanagari: 'ख़्वाब', category: 'kh/x', notes: 'IPA-style x spelling' },
  { roman: 'khushi', canonicalDevanagari: 'ख़ुशी', category: 'kh/x', notes: 'Standard kh spelling' },
  { roman: 'khusi', canonicalDevanagari: 'ख़ुशी', category: 'kh/x', notes: 'Sibilant variation s' },
  { roman: 'xushi', canonicalDevanagari: 'ख़ुशी', category: 'kh/x', notes: 'x transliteration' },
  { roman: 'kharab', canonicalDevanagari: 'ख़राब', category: 'kh/x', notes: 'Standard kh spelling' },
  { roman: 'kharaab', canonicalDevanagari: 'ख़राब', category: 'kh/x', notes: 'Double aa spelling' },
  { roman: 'xarab', canonicalDevanagari: 'ख़राब', category: 'kh/x', notes: 'x transliteration' },
  { roman: 'khauf', canonicalDevanagari: 'ख़ौफ़', category: 'kh/x', notes: 'Standard kh spelling' },
  { roman: 'khof', canonicalDevanagari: 'ख़ौफ़', category: 'kh/x', notes: 'Single o spelling' },
  { roman: 'xauf', canonicalDevanagari: 'ख़ौफ़', category: 'kh/x', notes: 'x transliteration' },
  { roman: 'khamosh', canonicalDevanagari: 'ख़ामोश', category: 'kh/x', notes: 'Standard kh spelling' },
  { roman: 'xamosh', canonicalDevanagari: 'ख़ामोश', category: 'kh/x', notes: 'x transliteration' },
  { roman: 'khamoshi', canonicalDevanagari: 'ख़ामोशी', category: 'kh/x', notes: 'Standard kh spelling' },
  { roman: 'xamoshi', canonicalDevanagari: 'ख़ामोशी', category: 'kh/x', notes: 'x transliteration' },
  { roman: 'khayal', canonicalDevanagari: 'ख़याल', category: 'kh/x', notes: 'Standard kh spelling' },
  { roman: 'khayaal', canonicalDevanagari: 'ख़याल', category: 'kh/x', notes: 'Double aa spelling' },
  { roman: 'xayal', canonicalDevanagari: 'ख़याल', category: 'kh/x', notes: 'x transliteration' },
  { roman: 'maikhana', canonicalDevanagari: 'मयख़ाना', category: 'kh/x', notes: 'Compound with kh' },
  { roman: 'maykhana', canonicalDevanagari: 'मयख़ाना', category: 'kh/x', notes: 'Compound with y' },
  { roman: 'maixana', canonicalDevanagari: 'मयख़ाना', category: 'kh/x', notes: 'Compound with x' },
  { roman: 'khallas', canonicalDevanagari: 'खल्लास', category: 'kh/x', notes: 'Slang kh spelling' },
  { roman: 'xallas', canonicalDevanagari: 'खल्लास', category: 'kh/x', notes: 'Slang x spelling' },
  { roman: 'khalas', canonicalDevanagari: 'खल्लास', category: 'kh/x', notes: 'Single l spelling' },

  // =========================================================================
  // 3. PH vs F VARIATIONS (25 ENTRIES)
  // =========================================================================
  { roman: 'fursat', canonicalDevanagari: 'फ़ुरसत', category: 'ph/f', notes: 'Standard f spelling' },
  { roman: 'phursat', canonicalDevanagari: 'फ़ुरसत', category: 'ph/f', notes: 'Hindi aspirated p spelling' },
  { roman: 'fasana', canonicalDevanagari: 'फ़साना', category: 'ph/f', notes: 'Standard f spelling' },
  { roman: 'phasana', canonicalDevanagari: 'फ़साना', category: 'ph/f', notes: 'Aspirated ph spelling' },
  { roman: 'falak', canonicalDevanagari: 'फ़लक', category: 'ph/f', notes: 'Standard f spelling' },
  { roman: 'phalak', canonicalDevanagari: 'फ़लक', category: 'ph/f', notes: 'Aspirated ph spelling' },
  { roman: 'faaltu', canonicalDevanagari: 'फालतू', category: 'ph/f', notes: 'Standard f spelling' },
  { roman: 'phaltu', canonicalDevanagari: 'फालतू', category: 'ph/f', notes: 'Aspirated ph spelling' },
  { roman: 'fauj', canonicalDevanagari: 'फ़ौज', category: 'ph/f', notes: 'Standard f spelling' },
  { roman: 'phauj', canonicalDevanagari: 'फ़ौज', category: 'ph/f', notes: 'Aspirated ph spelling' },
  { roman: 'nafrat', canonicalDevanagari: 'नफ़रत', category: 'ph/f', notes: 'Standard f spelling' },
  { roman: 'naphart', canonicalDevanagari: 'नफ़रत', category: 'ph/f', notes: 'Metathesis slang spelling' },
  { roman: 'safar', canonicalDevanagari: 'सफ़र', category: 'ph/f', notes: 'Standard f spelling' },
  { roman: 'saphar', canonicalDevanagari: 'सफ़र', category: 'ph/f', notes: 'Aspirated ph spelling' },
  { roman: 'mehfil', canonicalDevanagari: 'महफ़िल', category: 'ph/f', notes: 'Standard f spelling' },
  { roman: 'mahfil', canonicalDevanagari: 'महफ़िल', category: 'ph/f', notes: 'a vowel variant' },
  { roman: 'mehphil', canonicalDevanagari: 'महफ़िल', category: 'ph/f', notes: 'Aspirated ph variant' },
  { roman: 'kafan', canonicalDevanagari: 'कफ़न', category: 'ph/f', notes: 'Standard f spelling' },
  { roman: 'kaphan', canonicalDevanagari: 'कफ़न', category: 'ph/f', notes: 'Aspirated ph spelling' },
  { roman: 'dafan', canonicalDevanagari: 'दफ़न', category: 'ph/f', notes: 'Standard f spelling' },
  { roman: 'daphan', canonicalDevanagari: 'दफ़न', category: 'ph/f', notes: 'Aspirated ph spelling' },
  { roman: 'saaf', canonicalDevanagari: 'साफ़', category: 'ph/f', notes: 'Coda f spelling' },
  { roman: 'saaph', canonicalDevanagari: 'साफ़', category: 'ph/f', notes: 'Coda ph spelling' },
  { roman: 'maaf', canonicalDevanagari: 'माफ़', category: 'ph/f', notes: 'Coda f spelling' },
  { roman: 'maaph', canonicalDevanagari: 'माफ़', category: 'ph/f', notes: 'Coda ph spelling' },

  // =========================================================================
  // 4. Z vs J VARIATIONS (25 ENTRIES)
  // =========================================================================
  { roman: 'zindagi', canonicalDevanagari: 'ज़िंदगी', category: 'z/j', notes: 'Standard voiced sibilant z' },
  { roman: 'jindagi', canonicalDevanagari: 'ज़िंदगी', category: 'z/j', notes: 'Conversational affricate j' },
  { roman: 'zamana', canonicalDevanagari: 'ज़माना', category: 'z/j', notes: 'Standard z' },
  { roman: 'jamana', canonicalDevanagari: 'ज़माना', category: 'z/j', notes: 'Conversational j' },
  { roman: 'zahar', canonicalDevanagari: 'ज़हर', category: 'z/j', notes: 'Standard z' },
  { roman: 'jahar', canonicalDevanagari: 'ज़हर', category: 'z/j', notes: 'Conversational j' },
  { roman: 'zehar', canonicalDevanagari: 'ज़हर', category: 'z/j', notes: 'Vowel height variant e' },
  { roman: 'zanjeer', canonicalDevanagari: 'ज़ंजीर', category: 'z/j', notes: 'Standard z' },
  { roman: 'janjeer', canonicalDevanagari: 'ज़ंजीर', category: 'z/j', notes: 'Conversational j' },
  { roman: 'jazbaat', canonicalDevanagari: 'जज़्बात', category: 'z/j', notes: 'Medial z spelling' },
  { roman: 'jajbaat', canonicalDevanagari: 'जज़्बात', category: 'z/j', notes: 'Medial j spelling' },
  { roman: 'jazba', canonicalDevanagari: 'जज़्बा', category: 'z/j', notes: 'Singular noun with z' },
  { roman: 'jajba', canonicalDevanagari: 'जज़्बा', category: 'z/j', notes: 'Singular noun with j' },
  { roman: 'saza', canonicalDevanagari: 'सज़ा', category: 'z/j', notes: 'Standard z' },
  { roman: 'saja', canonicalDevanagari: 'सज़ा', category: 'z/j', notes: 'Conversational j' },
  { roman: 'maza', canonicalDevanagari: 'मज़ा', category: 'z/j', notes: 'Standard z' },
  { roman: 'maja', canonicalDevanagari: 'मज़ा', category: 'z/j', notes: 'Conversational j' },
  { roman: 'nazar', canonicalDevanagari: 'नज़र', category: 'z/j', notes: 'Standard z' },
  { roman: 'najar', canonicalDevanagari: 'नज़र', category: 'z/j', notes: 'Conversational j' },
  { roman: 'guzar', canonicalDevanagari: 'गुज़र', category: 'z/j', notes: 'Standard z' },
  { roman: 'gujar', canonicalDevanagari: 'गुज़र', category: 'z/j', notes: 'Conversational j' },
  { roman: 'nazara', canonicalDevanagari: 'नज़ारा', category: 'z/j', notes: 'Standard z' },
  { roman: 'najara', canonicalDevanagari: 'नज़ारा', category: 'z/j', notes: 'Conversational j' },
  { roman: 'zawal', canonicalDevanagari: 'ज़वाल', category: 'z/j', notes: 'Standard z' },
  { roman: 'jawal', canonicalDevanagari: 'ज़वाल', category: 'z/j', notes: 'Conversational j' },

  // =========================================================================
  // 5. V vs W VARIATIONS (25 ENTRIES)
  // =========================================================================
  { roman: 'wafa', canonicalDevanagari: 'वफ़ा', category: 'v/w', notes: 'Approximant w' },
  { roman: 'vafa', canonicalDevanagari: 'वफ़ा', category: 'v/w', notes: 'Fricative v' },
  { roman: 'waqt', canonicalDevanagari: 'वक़्त', category: 'v/w', notes: 'w spelling' },
  { roman: 'vakt', canonicalDevanagari: 'वक़्त', category: 'v/w', notes: 'v spelling' },
  { roman: 'watan', canonicalDevanagari: 'वतन', category: 'v/w', notes: 'w spelling' },
  { roman: 'vatan', canonicalDevanagari: 'वतन', category: 'v/w', notes: 'v spelling' },
  { roman: 'hawa', canonicalDevanagari: 'हवा', category: 'v/w', notes: 'w spelling' },
  { roman: 'hava', canonicalDevanagari: 'हवा', category: 'v/w', notes: 'v spelling' },
  { roman: 'dawa', canonicalDevanagari: 'दवा', category: 'v/w', notes: 'w spelling' },
  { roman: 'dava', canonicalDevanagari: 'दवा', category: 'v/w', notes: 'v spelling' },
  { roman: 'deewar', canonicalDevanagari: 'दीवार', category: 'v/w', notes: 'w spelling' },
  { roman: 'deevar', canonicalDevanagari: 'दीवार', category: 'v/w', notes: 'v spelling' },
  { roman: 'parwana', canonicalDevanagari: 'परवाना', category: 'v/w', notes: 'w spelling' },
  { roman: 'parvana', canonicalDevanagari: 'परवाना', category: 'v/w', notes: 'v spelling' },
  { roman: 'deewana', canonicalDevanagari: 'दीवाना', category: 'v/w', notes: 'w spelling' },
  { roman: 'deevana', canonicalDevanagari: 'दीवाना', category: 'v/w', notes: 'v spelling' },
  { roman: 'jawani', canonicalDevanagari: 'जवानी', category: 'v/w', notes: 'w spelling' },
  { roman: 'javani', canonicalDevanagari: 'जवानी', category: 'v/w', notes: 'v spelling' },
  { roman: 'rawani', canonicalDevanagari: 'रवानी', category: 'v/w', notes: 'w spelling' },
  { roman: 'ravani', canonicalDevanagari: 'रवानी', category: 'v/w', notes: 'v spelling' },
  { roman: 'bawaal', canonicalDevanagari: 'बवाल', category: 'v/w', notes: 'w spelling' },
  { roman: 'bavaal', canonicalDevanagari: 'बवाल', category: 'v/w', notes: 'v spelling' },
  { roman: 'visaal', canonicalDevanagari: 'विसाल', category: 'v/w', notes: 'v spelling' },
  { roman: 'wisaal', canonicalDevanagari: 'विसाल', category: 'v/w', notes: 'w spelling' },
  { roman: 'vishwas', canonicalDevanagari: 'विश्वास', category: 'v/w', notes: 'v spelling' },

  // =========================================================================
  // 6. VOWEL LENGTH & CONTRACTIONS (35 ENTRIES)
  // =========================================================================
  { roman: 'raat', canonicalDevanagari: 'रात', category: 'vowel length', notes: 'Double aa long vowel' },
  { roman: 'rat', canonicalDevanagari: 'रात', category: 'vowel length', notes: 'Single a fast typing' },
  { roman: 'baat', canonicalDevanagari: 'बात', category: 'vowel length', notes: 'Double aa long vowel' },
  { roman: 'bat', canonicalDevanagari: 'बात', category: 'vowel length', notes: 'Single a fast typing' },
  { roman: 'saath', canonicalDevanagari: 'साथ', category: 'vowel length', notes: 'Double aa long vowel' },
  { roman: 'sat', canonicalDevanagari: 'साथ', category: 'vowel length', notes: 'Single a fast typing' },
  { roman: 'haath', canonicalDevanagari: 'हाथ', category: 'vowel length', notes: 'Double aa long vowel' },
  { roman: 'hath', canonicalDevanagari: 'हाथ', category: 'vowel length', notes: 'Single a fast typing' },
  { roman: 'naam', canonicalDevanagari: 'नाम', category: 'vowel length', notes: 'Double aa long vowel' },
  { roman: 'nam', canonicalDevanagari: 'नाम', category: 'vowel length', notes: 'Single a fast typing' },
  { roman: 'kaam', canonicalDevanagari: 'काम', category: 'vowel length', notes: 'Double aa long vowel' },
  { roman: 'kam', canonicalDevanagari: 'कम', category: 'vowel length', notes: 'Short schwa word vs long' },
  { roman: 'pyaar', canonicalDevanagari: 'प्यार', category: 'vowel length', notes: 'Double aa long vowel' },
  { roman: 'pyar', canonicalDevanagari: 'प्यार', category: 'vowel length', notes: 'Single a fast typing' },
  { roman: 'yaar', canonicalDevanagari: 'यार', category: 'vowel length', notes: 'Double aa long vowel' },
  { roman: 'yar', canonicalDevanagari: 'यार', category: 'vowel length', notes: 'Single a fast typing' },
  { roman: 'aag', canonicalDevanagari: 'आग', category: 'vowel length', notes: 'Double aa initial' },
  { roman: 'ag', canonicalDevanagari: 'आग', category: 'vowel length', notes: 'Single a initial' },
  { roman: 'daag', canonicalDevanagari: 'दाग', category: 'vowel length', notes: 'Double aa' },
  { roman: 'dag', canonicalDevanagari: 'दाग', category: 'vowel length', notes: 'Single a' },
  { roman: 'sukoon', canonicalDevanagari: 'सुकून', category: 'vowel length', notes: 'Double oo' },
  { roman: 'sukun', canonicalDevanagari: 'सुकून', category: 'vowel length', notes: 'Single u' },
  { roman: 'junoon', canonicalDevanagari: 'जुनून', category: 'vowel length', notes: 'Double oo' },
  { roman: 'junun', canonicalDevanagari: 'जुनून', category: 'vowel length', notes: 'Single u' },
  { roman: 'khoon', canonicalDevanagari: 'खून', category: 'vowel length', notes: 'Double oo' },
  { roman: 'khun', canonicalDevanagari: 'खून', category: 'vowel length', notes: 'Single u' },
  { roman: 'kanoon', canonicalDevanagari: 'कानून', category: 'vowel length', notes: 'Double oo' },
  { roman: 'kanun', canonicalDevanagari: 'कानून', category: 'vowel length', notes: 'Single u' },
  { roman: 'teer', canonicalDevanagari: 'तीर', category: 'vowel length', notes: 'Double ee' },
  { roman: 'tir', canonicalDevanagari: 'तीर', category: 'vowel length', notes: 'Single i' },
  { roman: 'peer', canonicalDevanagari: 'पीर', category: 'vowel length', notes: 'Double ee' },
  { roman: 'pir', canonicalDevanagari: 'पीर', category: 'vowel length', notes: 'Single i' },
  { roman: 'zameen', canonicalDevanagari: 'ज़मीन', category: 'vowel length', notes: 'Double ee' },
  { roman: 'zamin', canonicalDevanagari: 'ज़मीन', category: 'vowel length', notes: 'Single i' },
  { roman: 'tasveer', canonicalDevanagari: 'तस्वीर', category: 'vowel length', notes: 'Double ee' }
];
