import { GoldWordEntry } from './words-gold';

export const GOLD_WORDS_PART3: GoldWordEntry[] = [
  // =========================================================================
  // 11. NATURE, COSMOS & GEOGRAPHY (45 WORDS)
  // =========================================================================
  {
    devanagari: 'चाँद',
    roman: ['chaand', 'chand'],
    urdu: 'چاند',
    pronunciations: ['t͡ʃãːnd̪'],
    syllables: 1,
    breakdown: ['t͡ʃãːnd̪'],
    nucleus: 'ãː',
    coda: 'nd̪',
    rhymeKey: 'ãːnd̪',
    register: 'common',
    meaning: 'moon',
    variants: ['chaand'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'मांद',
    roman: ['maand'],
    urdu: 'ماند',
    pronunciations: ['mãːnd̪'],
    syllables: 1,
    breakdown: ['mãːnd̪'],
    nucleus: 'ãː',
    coda: 'nd̪',
    rhymeKey: 'ãːnd̪',
    register: 'poetic',
    meaning: 'faded, dim, animal den',
    variants: ['maand'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'सूरज',
    roman: ['suraj', 'sooraj'],
    urdu: 'سورج',
    pronunciations: ['suː.rəd͡ʒ'],
    syllables: 2,
    breakdown: ['suː', 'rəd͡ʒ'],
    nucleus: 'ə',
    coda: 'd͡ʒ',
    rhymeKey: 'əd͡ʒ',
    register: 'common',
    meaning: 'sun',
    variants: ['suraj'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'मूरज',
    roman: ['muraj'],
    urdu: 'مورج',
    pronunciations: ['muː.rəd͡ʒ'],
    syllables: 2,
    breakdown: ['muː', 'rəd͡ʒ'],
    nucleus: 'ə',
    coda: 'd͡ʒ',
    rhymeKey: 'əd͡ʒ',
    register: 'literary',
    meaning: 'drum, percussion instrument',
    variants: ['muraj'],
    origin: 'Sanskrit'
  },
  {
    devanagari: 'बादल',
    roman: ['baadal', 'badal'],
    urdu: 'بادل',
    pronunciations: ['baː.d̪əl'],
    syllables: 2,
    breakdown: ['baː', 'd̪əl'],
    nucleus: 'ə',
    coda: 'l',
    rhymeKey: 'əl',
    register: 'common',
    meaning: 'cloud',
    variants: ['baadal'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'काजल',
    roman: ['kaajal', 'kajal'],
    urdu: 'کاجل',
    pronunciations: ['kaː.d͡ʒəl'],
    syllables: 2,
    breakdown: ['kaː', 'd͡ʒəl'],
    nucleus: 'ə',
    coda: 'l',
    rhymeKey: 'əl',
    register: 'common',
    meaning: 'kohl, eyeliner',
    variants: ['kaajal'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'घायल',
    roman: ['ghaayal', 'ghayal'],
    urdu: 'گھائل',
    pronunciations: ['ɡʱaː.jəl'],
    syllables: 2,
    breakdown: ['ɡʱaː', 'jəl'],
    nucleus: 'ə',
    coda: 'l',
    rhymeKey: 'əl',
    register: 'common',
    meaning: 'wounded, injured',
    variants: ['ghaayal'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'क़ायल',
    roman: ['qaayal', 'qayal'],
    urdu: 'قائل',
    pronunciations: ['qaː.jəl', 'kaː.jəl'],
    syllables: 2,
    breakdown: ['qaː', 'jəl'],
    nucleus: 'ə',
    coda: 'l',
    rhymeKey: 'əl',
    register: 'poetic',
    meaning: 'convinced, admirer',
    variants: ['qaayal'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'मायल',
    roman: ['maayal', 'mayal'],
    urdu: 'مائل',
    pronunciations: ['maː.jəl'],
    syllables: 2,
    breakdown: ['maː', 'jəl'],
    nucleus: 'ə',
    coda: 'l',
    rhymeKey: 'əl',
    register: 'poetic',
    meaning: 'inclined, disposed',
    variants: ['maayal'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'बिजली',
    roman: ['bijli'],
    urdu: 'بجلی',
    pronunciations: ['bɪd͡ʒ.liː'],
    syllables: 2,
    breakdown: ['bɪd͡ʒ', 'liː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'liː',
    register: 'common',
    meaning: 'lightning, electricity',
    variants: ['bijli'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'तितली',
    roman: ['titli'],
    urdu: 'تتلی',
    pronunciations: ['t̪ɪt̪.liː'],
    syllables: 2,
    breakdown: ['t̪ɪt̪', 'liː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'liː',
    register: 'common',
    meaning: 'butterfly',
    variants: ['titli'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'पुतली',
    roman: ['putli'],
    urdu: 'پتلی',
    pronunciations: ['pʊt̪.liː'],
    syllables: 2,
    breakdown: ['pʊt̪', 'liː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'liː',
    register: 'common',
    meaning: 'puppet, eyeball pupil',
    variants: ['putli'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'पतली',
    roman: ['patli'],
    urdu: 'پتلی',
    pronunciations: ['pət̪.liː'],
    syllables: 2,
    breakdown: ['pət̪', 'liː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'liː',
    register: 'common',
    meaning: 'thin, slender',
    variants: ['patli'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'दरिया',
    roman: ['dariya'],
    urdu: 'دریا',
    pronunciations: ['d̪ə.rɪ.jaː'],
    syllables: 3,
    breakdown: ['d̪ə', 'rɪ', 'jaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'ɪjaː',
    register: 'poetic',
    meaning: 'river, vast sea',
    variants: ['dariya'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'ज़रिया',
    roman: ['zariya', 'jariya'],
    urdu: 'ذریعہ',
    pronunciations: ['zə.rɪ.jaː'],
    syllables: 3,
    breakdown: ['zə', 'rɪ', 'jaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'ɪjaː',
    register: 'common',
    meaning: 'medium, conduit, means',
    variants: ['zariya'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'नज़रिया',
    roman: ['nazariya'],
    urdu: 'نظریہ',
    pronunciations: ['nə.zə.rɪ.jaː'],
    syllables: 4,
    breakdown: ['nə', 'zə', 'rɪ', 'jaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'ɪjaː',
    register: 'common',
    meaning: 'perspective, viewpoint',
    variants: ['nazariya'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'समंदर',
    roman: ['samandar'],
    urdu: 'سمندر',
    pronunciations: ['sə.mən.d̪ər'],
    syllables: 3,
    breakdown: ['sə', 'mən', 'd̪ər'],
    nucleus: 'ə',
    coda: 'r',
    rhymeKey: 'ənd̪ər',
    register: 'common',
    meaning: 'ocean, sea',
    variants: ['samandar'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'सिकंदर',
    roman: ['sikandar'],
    urdu: 'سکندر',
    pronunciations: ['sɪ.kən.d̪ər'],
    syllables: 3,
    breakdown: ['sɪ', 'kən', 'd̪ər'],
    nucleus: 'ə',
    coda: 'r',
    rhymeKey: 'ənd̪ər',
    register: 'common',
    meaning: 'conqueror, Alexander',
    variants: ['sikandar'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'अंदर',
    roman: ['andar'],
    urdu: 'اندر',
    pronunciations: ['ən.d̪ər'],
    syllables: 2,
    breakdown: ['ən', 'd̪ər'],
    nucleus: 'ə',
    coda: 'r',
    rhymeKey: 'ənd̪ər',
    register: 'common',
    meaning: 'inside, within',
    variants: ['andar'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'बंदर',
    roman: ['bandar'],
    urdu: 'بندر',
    pronunciations: ['bən.d̪ər'],
    syllables: 2,
    breakdown: ['bən', 'd̪ər'],
    nucleus: 'ə',
    coda: 'r',
    rhymeKey: 'ənd̪ər',
    register: 'common',
    meaning: 'monkey, port',
    variants: ['bandar'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'कलंदर',
    roman: ['qalandar', 'kalandar'],
    urdu: 'قلندر',
    pronunciations: ['qə.lən.d̪ər', 'kə.lən.d̪ər'],
    syllables: 3,
    breakdown: ['qə', 'lən', 'd̪ər'],
    nucleus: 'ə',
    coda: 'r',
    rhymeKey: 'ənd̪ər',
    register: 'poetic',
    meaning: 'free-spirited mystic, saint',
    variants: ['qalandar'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'सहरा',
    roman: ['sahra', 'sehra'],
    urdu: 'صحرا',
    pronunciations: ['sɛːɦ.raː', 'səɦ.raː'],
    syllables: 2,
    breakdown: ['sɛːɦ', 'raː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'raː',
    register: 'poetic',
    meaning: 'desert, wilderness',
    variants: ['sahra'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'गुलशन',
    roman: ['gulshan'],
    urdu: 'گلشن',
    pronunciations: ['ɡʊl.ʃən'],
    syllables: 2,
    breakdown: ['ɡʊl', 'ʃən'],
    nucleus: 'ə',
    coda: 'n',
    rhymeKey: 'ən',
    register: 'poetic',
    meaning: 'rose garden',
    variants: ['gulshan'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'रोशन',
    roman: ['roshan'],
    urdu: 'روشن',
    pronunciations: ['roː.ʃən'],
    syllables: 2,
    breakdown: ['roː', 'ʃən'],
    nucleus: 'ə',
    coda: 'n',
    rhymeKey: 'ən',
    register: 'common',
    meaning: 'bright, illuminated',
    variants: ['roshan'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'दुश्मन',
    roman: ['dushman'],
    urdu: 'دشمن',
    pronunciations: ['d̪ʊʃ.mən'],
    syllables: 2,
    breakdown: ['d̪ʊʃ', 'mən'],
    nucleus: 'ə',
    coda: 'n',
    rhymeKey: 'ən',
    register: 'common',
    meaning: 'enemy, rival',
    variants: ['dushman'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'बहार',
    roman: ['bahaar', 'bahar'],
    urdu: 'بہار',
    pronunciations: ['bə.ɦaːr'],
    syllables: 2,
    breakdown: ['bə', 'ɦaːr'],
    nucleus: 'aː',
    coda: 'r',
    rhymeKey: 'aːr',
    register: 'poetic',
    meaning: 'springtime, bloom',
    variants: ['bahaar'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'धुंध',
    roman: ['dhundh', 'dhund'],
    urdu: 'دھند',
    pronunciations: ['d̪ʱʊnd̪ʱ'],
    syllables: 1,
    breakdown: ['d̪ʱʊnd̪ʱ'],
    nucleus: 'ʊ',
    coda: 'nd̪ʱ',
    rhymeKey: 'ʊnd̪ʱ',
    register: 'common',
    meaning: 'fog, haze, blur',
    variants: ['dhundh'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'सन्नाटा',
    roman: ['sannata'],
    urdu: 'سناٹا',
    pronunciations: ['sən.naː.ʈaː'],
    syllables: 3,
    breakdown: ['sən', 'naː', 'ʈaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːʈaː',
    register: 'common',
    meaning: 'dead silence, stillness',
    variants: ['sannata'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'तमाचा',
    roman: ['tamacha'],
    urdu: 'تماچہ',
    pronunciations: ['t̪ə.maː.t͡ʃaː'],
    syllables: 3,
    breakdown: ['t̪ə', 'maː', 't͡ʃaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːt͡ʃaː',
    register: 'common',
    meaning: 'slap, hard strike',
    variants: ['tamacha'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'जंगल',
    roman: ['jungle', 'jangal'],
    urdu: 'جنگل',
    pronunciations: ['d͡ʒəŋ.ɡəl'],
    syllables: 2,
    breakdown: ['d͡ʒəŋ', 'ɡəl'],
    nucleus: 'ə',
    coda: 'l',
    rhymeKey: 'əl',
    register: 'common',
    meaning: 'forest, jungle',
    variants: ['jungle', 'jangal'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'दंगल',
    roman: ['dangal'],
    urdu: 'دنگل',
    pronunciations: ['d̪əŋ.ɡəl'],
    syllables: 2,
    breakdown: ['d̪əŋ', 'ɡəl'],
    nucleus: 'ə',
    coda: 'l',
    rhymeKey: 'əl',
    register: 'common',
    meaning: 'wrestling bout, arena fight',
    variants: ['dangal'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'मंगल',
    roman: ['mangal'],
    urdu: 'منگل',
    pronunciations: ['məŋ.ɡəl'],
    syllables: 2,
    breakdown: ['məŋ', 'ɡəl'],
    nucleus: 'ə',
    coda: 'l',
    rhymeKey: 'əl',
    register: 'common',
    meaning: 'auspicious, Mars, Tuesday',
    variants: ['mangal'],
    origin: 'Sanskrit'
  },
  {
    devanagari: 'पहाड़',
    roman: ['pahaad', 'pahad'],
    urdu: 'پہاڑ',
    pronunciations: ['pə.ɦaːɽ'],
    syllables: 2,
    breakdown: ['pə', 'ɦaːɽ'],
    nucleus: 'aː',
    coda: 'ɽ',
    rhymeKey: 'aːɽ',
    register: 'common',
    meaning: 'mountain',
    variants: ['pahaad'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'दहाड़',
    roman: ['dahaad', 'dahad'],
    urdu: 'دہاڑ',
    pronunciations: ['d̪ə.ɦaːɽ'],
    syllables: 2,
    breakdown: ['d̪ə', 'ɦaːɽ'],
    nucleus: 'aː',
    coda: 'ɽ',
    rhymeKey: 'aːɽ',
    register: 'common',
    meaning: 'roar',
    variants: ['dahaad'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'पछाड़',
    roman: ['pachhad'],
    urdu: 'پچھاڑ',
    pronunciations: ['pə.t͡ʃʰaːɽ'],
    syllables: 2,
    breakdown: ['pə', 't͡ʃʰaːɽ'],
    nucleus: 'aː',
    coda: 'ɽ',
    rhymeKey: 'aːɽ',
    register: 'common',
    meaning: 'throwdown, defeat',
    variants: ['pachhad'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'आँधी',
    roman: ['aandhi'],
    urdu: 'آندھی',
    pronunciations: ['ãːn.d̪ʱiː'],
    syllables: 2,
    breakdown: ['ãːn', 'd̪ʱiː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'd̪ʱiː',
    register: 'common',
    meaning: 'dust storm, whirlwind',
    variants: ['aandhi'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'गांधी',
    roman: ['gandhi'],
    urdu: 'گاندھی',
    pronunciations: ['ɡaːn.d̪ʱiː'],
    syllables: 2,
    breakdown: ['ɡaːn', 'd̪ʱiː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'd̪ʱiː',
    register: 'common',
    meaning: 'Gandhi surname / perfume merchant',
    variants: ['gandhi'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'बाँधी',
    roman: ['baandhi'],
    urdu: 'باندھی',
    pronunciations: ['bãːn.d̪ʱiː'],
    syllables: 2,
    breakdown: ['bãːn', 'd̪ʱiː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'd̪ʱiː',
    register: 'common',
    meaning: 'tied, bound (fem)',
    variants: ['baandhi'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'साँधी',
    roman: ['saandhi'],
    urdu: 'ساندھی',
    pronunciations: ['sãːn.d̪ʱiː'],
    syllables: 2,
    breakdown: ['sãːn', 'd̪ʱiː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'd̪ʱiː',
    register: 'poetic',
    meaning: 'blended, jointed',
    variants: ['saandhi'],
    origin: 'Hindustani'
  },

  // =========================================================================
  // 12. HIP-HOP ANCHOR LOANWORDS (40 WORDS)
  // =========================================================================
  {
    devanagari: 'क्लब',
    roman: ['club'],
    urdu: 'کلب',
    pronunciations: ['kləb'],
    syllables: 1,
    breakdown: ['kləb'],
    nucleus: 'ə',
    coda: 'b',
    rhymeKey: 'əb',
    register: 'slang',
    meaning: 'nightclub',
    variants: ['club'],
    origin: 'English'
  },
  {
    devanagari: 'सब',
    roman: ['sab'],
    urdu: 'سب',
    pronunciations: ['səb'],
    syllables: 1,
    breakdown: ['səb'],
    nucleus: 'ə',
    coda: 'b',
    rhymeKey: 'əb',
    register: 'common',
    meaning: 'all, everyone',
    variants: ['sab'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'रब',
    roman: ['rab'],
    urdu: 'رب',
    pronunciations: ['rəb'],
    syllables: 1,
    breakdown: ['rəb'],
    nucleus: 'ə',
    coda: 'b',
    rhymeKey: 'əb',
    register: 'poetic',
    meaning: 'Lord, God',
    variants: ['rab'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'कब',
    roman: ['kab'],
    urdu: 'کب',
    pronunciations: ['kəb'],
    syllables: 1,
    breakdown: ['kəb'],
    nucleus: 'ə',
    coda: 'b',
    rhymeKey: 'əb',
    register: 'common',
    meaning: 'when',
    variants: ['kab'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'अब',
    roman: ['ab'],
    urdu: 'اب',
    pronunciations: ['əb'],
    syllables: 1,
    breakdown: ['əb'],
    nucleus: 'ə',
    coda: 'b',
    rhymeKey: 'əb',
    register: 'common',
    meaning: 'now',
    variants: ['ab'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'तब',
    roman: ['tab'],
    urdu: 'تب',
    pronunciations: ['t̪əb'],
    syllables: 1,
    breakdown: ['t̪əb'],
    nucleus: 'ə',
    coda: 'b',
    rhymeKey: 'əb',
    register: 'common',
    meaning: 'then',
    variants: ['tab'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'ट्रैक',
    roman: ['track'],
    urdu: 'ٹریک',
    pronunciations: ['ʈrɛːk'],
    syllables: 1,
    breakdown: ['ʈrɛːk'],
    nucleus: 'ɛː',
    coda: 'k',
    rhymeKey: 'ɛːk',
    register: 'technical',
    meaning: 'song audio track',
    variants: ['track'],
    origin: 'English'
  },
  {
    devanagari: 'ब्लैक',
    roman: ['black'],
    urdu: 'بلیک',
    pronunciations: ['blɛːk'],
    syllables: 1,
    breakdown: ['blɛːk'],
    nucleus: 'ɛː',
    coda: 'k',
    rhymeKey: 'ɛːk',
    register: 'slang',
    meaning: 'black color / money',
    variants: ['black'],
    origin: 'English'
  },
  {
    devanagari: 'स्टेज',
    roman: ['stage'],
    urdu: 'سٹیج',
    pronunciations: ['sʈeːd͡ʒ'],
    syllables: 1,
    breakdown: ['sʈeːd͡ʒ'],
    nucleus: 'eː',
    coda: 'd͡ʒ',
    rhymeKey: 'eːd͡ʒ',
    register: 'technical',
    meaning: 'stage platform',
    variants: ['stage'],
    origin: 'English'
  },
  {
    devanagari: 'पेज',
    roman: ['page'],
    urdu: 'پیج',
    pronunciations: ['peːd͡ʒ'],
    syllables: 1,
    breakdown: ['peːd͡ʒ'],
    nucleus: 'eː',
    coda: 'd͡ʒ',
    rhymeKey: 'eːd͡ʒ',
    register: 'common',
    meaning: 'book page',
    variants: ['page'],
    origin: 'English'
  },
  {
    devanagari: 'माइक',
    roman: ['mic', 'mike'],
    urdu: 'مائیک',
    pronunciations: ['maːɪk', 'maːjk'],
    syllables: 1,
    breakdown: ['maːjk'],
    nucleus: 'aːɪ',
    coda: 'k',
    rhymeKey: 'aːjk',
    register: 'technical',
    meaning: 'microphone',
    variants: ['mic', 'mike'],
    origin: 'English'
  },
  {
    devanagari: 'लाइक',
    roman: ['like'],
    urdu: 'لائیک',
    pronunciations: ['laːɪk', 'laːjk'],
    syllables: 1,
    breakdown: ['laːjk'],
    nucleus: 'aːɪ',
    coda: 'k',
    rhymeKey: 'aːjk',
    register: 'slang',
    meaning: 'social media like / worthy',
    variants: ['like'],
    origin: 'English'
  },
  {
    devanagari: 'स्ट्राइक',
    roman: ['strike'],
    urdu: 'سٹرائیک',
    pronunciations: ['sʈraːɪk', 'sʈraːjk'],
    syllables: 1,
    breakdown: ['sʈraːjk'],
    nucleus: 'aːɪ',
    coda: 'k',
    rhymeKey: 'aːjk',
    register: 'slang',
    meaning: 'strike, hit',
    variants: ['strike'],
    origin: 'English'
  },
  {
    devanagari: 'गेम',
    roman: ['game'],
    urdu: 'گیم',
    pronunciations: ['ɡeːm'],
    syllables: 1,
    breakdown: ['ɡeːm'],
    nucleus: 'eː',
    coda: 'm',
    rhymeKey: 'eːm',
    register: 'slang',
    meaning: 'rap game, hustle',
    variants: ['game'],
    origin: 'English'
  },
  {
    devanagari: 'फेम',
    roman: ['fame'],
    urdu: 'فیم',
    pronunciations: ['feːm'],
    syllables: 1,
    breakdown: ['feːm'],
    nucleus: 'eː',
    coda: 'm',
    rhymeKey: 'eːm',
    register: 'slang',
    meaning: 'stardom, celebrity',
    variants: ['fame'],
    origin: 'English'
  },
  {
    devanagari: 'नेम',
    roman: ['name'],
    urdu: 'نیم',
    pronunciations: ['neːm'],
    syllables: 1,
    breakdown: ['neːm'],
    nucleus: 'eː',
    coda: 'm',
    rhymeKey: 'eːm',
    register: 'slang',
    meaning: 'name, reputation',
    variants: ['name'],
    origin: 'English'
  },
  {
    devanagari: 'बॉस',
    roman: ['boss'],
    urdu: 'باس',
    pronunciations: ['bɔːs'],
    syllables: 1,
    breakdown: ['bɔːs'],
    nucleus: 'ɔː',
    coda: 's',
    rhymeKey: 'ɔːs',
    register: 'slang',
    meaning: 'leader, kingpin',
    variants: ['boss'],
    origin: 'English'
  },
  {
    devanagari: 'लॉस',
    roman: ['loss'],
    urdu: 'لاس',
    pronunciations: ['lɔːs'],
    syllables: 1,
    breakdown: ['lɔːs'],
    nucleus: 'ɔː',
    coda: 's',
    rhymeKey: 'ɔːs',
    register: 'common',
    meaning: 'financial/personal loss',
    variants: ['loss'],
    origin: 'English'
  },
  {
    devanagari: 'टॉस',
    roman: ['toss'],
    urdu: 'ٹاس',
    pronunciations: ['ʈɔːs'],
    syllables: 1,
    breakdown: ['ʈɔːs'],
    nucleus: 'ɔː',
    coda: 's',
    rhymeKey: 'ɔːs',
    register: 'common',
    meaning: 'coin flip',
    variants: ['toss'],
    origin: 'English'
  },
  {
    devanagari: 'किंग',
    roman: ['king'],
    urdu: 'کنگ',
    pronunciations: ['kɪŋ'],
    syllables: 1,
    breakdown: ['kɪŋ'],
    nucleus: 'ɪ',
    coda: 'ŋ',
    rhymeKey: 'ɪŋ',
    register: 'slang',
    meaning: 'monarch, rap king',
    variants: ['king'],
    origin: 'English'
  },
  {
    devanagari: 'रिंग',
    roman: ['ring'],
    urdu: 'رنگ',
    pronunciations: ['rɪŋ'],
    syllables: 1,
    breakdown: ['rɪŋ'],
    nucleus: 'ɪ',
    coda: 'ŋ',
    rhymeKey: 'ɪŋ',
    register: 'slang',
    meaning: 'boxing ring / jewelry',
    variants: ['ring'],
    origin: 'English'
  },
  {
    devanagari: 'विंग',
    roman: ['wing'],
    urdu: 'ونگ',
    pronunciations: ['ʋɪŋ'],
    syllables: 1,
    breakdown: ['ʋɪŋ'],
    nucleus: 'ɪ',
    coda: 'ŋ',
    rhymeKey: 'ɪŋ',
    register: 'common',
    meaning: 'faction, feather wing',
    variants: ['wing'],
    origin: 'English'
  },
  {
    devanagari: 'ड्रॉप',
    roman: ['drop'],
    urdu: 'ڈراپ',
    pronunciations: ['ɖrɔːp'],
    syllables: 1,
    breakdown: ['ɖrɔːp'],
    nucleus: 'ɔː',
    coda: 'p',
    rhymeKey: 'ɔːp',
    register: 'technical',
    meaning: 'beat drop, track release',
    variants: ['drop'],
    origin: 'English'
  },
  {
    devanagari: 'पॉप',
    roman: ['pop'],
    urdu: 'پاپ',
    pronunciations: ['pɔːp'],
    syllables: 1,
    breakdown: ['pɔːp'],
    nucleus: 'ɔː',
    coda: 'p',
    rhymeKey: 'ɔːp',
    register: 'common',
    meaning: 'pop genre, pop sound',
    variants: ['pop'],
    origin: 'English'
  },
  {
    devanagari: 'टॉप',
    roman: ['top'],
    urdu: 'ٹاپ',
    pronunciations: ['ʈɔːp'],
    syllables: 1,
    breakdown: ['ʈɔːp'],
    nucleus: 'ɔː',
    coda: 'p',
    rhymeKey: 'ɔːp',
    register: 'slang',
    meaning: 'highest tier, summit',
    variants: ['top'],
    origin: 'English'
  },
  {
    devanagari: 'स्टॉप',
    roman: ['stop'],
    urdu: 'سٹاپ',
    pronunciations: ['sʈɔːp'],
    syllables: 1,
    breakdown: ['sʈɔːp'],
    nucleus: 'ɔː',
    coda: 'p',
    rhymeKey: 'ɔːp',
    register: 'common',
    meaning: 'halt, cease',
    variants: ['stop'],
    origin: 'English'
  },
  {
    devanagari: 'हुक',
    roman: ['hook'],
    urdu: 'ہک',
    pronunciations: ['ɦʊk'],
    syllables: 1,
    breakdown: ['ɦʊk'],
    nucleus: 'ʊ',
    coda: 'k',
    rhymeKey: 'ʊk',
    register: 'technical',
    meaning: 'song chorus hook',
    variants: ['hook'],
    origin: 'English'
  },
  {
    devanagari: 'लुक',
    roman: ['look'],
    urdu: 'لک',
    pronunciations: ['lʊk'],
    syllables: 1,
    breakdown: ['lʊk'],
    nucleus: 'ʊ',
    coda: 'k',
    rhymeKey: 'ʊk',
    register: 'slang',
    meaning: 'appearance, glance',
    variants: ['look'],
    origin: 'English'
  },
  {
    devanagari: 'बुक',
    roman: ['book'],
    urdu: 'بک',
    pronunciations: ['bʊk'],
    syllables: 1,
    breakdown: ['bʊk'],
    nucleus: 'ʊ',
    coda: 'k',
    rhymeKey: 'ʊk',
    register: 'common',
    meaning: 'book, reservation',
    variants: ['book'],
    origin: 'English'
  },
  {
    devanagari: 'ट्रैप',
    roman: ['trap'],
    urdu: 'ٹریپ',
    pronunciations: ['ʈrɛːp'],
    syllables: 1,
    breakdown: ['ʈrɛːp'],
    nucleus: 'ɛː',
    coda: 'p',
    rhymeKey: 'ɛːp',
    register: 'slang',
    meaning: 'trap music subgenre',
    variants: ['trap'],
    origin: 'English'
  },
  {
    devanagari: 'रैप',
    roman: ['rap'],
    urdu: 'ریپ',
    pronunciations: ['rɛːp'],
    syllables: 1,
    breakdown: ['rɛːp'],
    nucleus: 'ɛː',
    coda: 'p',
    rhymeKey: 'ɛːp',
    register: 'technical',
    meaning: 'rhythm and poetry',
    variants: ['rap'],
    origin: 'English'
  },
  {
    devanagari: 'कैप',
    roman: ['cap'],
    urdu: 'کیپ',
    pronunciations: ['kɛːp'],
    syllables: 1,
    breakdown: ['kɛːp'],
    nucleus: 'ɛː',
    coda: 'p',
    rhymeKey: 'ɛːp',
    register: 'slang',
    meaning: 'cap, lie (no cap)',
    variants: ['cap'],
    origin: 'English'
  },
  {
    devanagari: 'हिट',
    roman: ['hit'],
    urdu: 'ہٹ',
    pronunciations: ['ɦɪʈ'],
    syllables: 1,
    breakdown: ['ɦɪʈ'],
    nucleus: 'ɪ',
    coda: 'ʈ',
    rhymeKey: 'ɪʈ',
    register: 'slang',
    meaning: 'hit single, success',
    variants: ['hit'],
    origin: 'English'
  },
  {
    devanagari: 'फ़िट',
    roman: ['fit'],
    urdu: 'فٹ',
    pronunciations: ['fɪʈ'],
    syllables: 1,
    breakdown: ['fɪʈ'],
    nucleus: 'ɪ',
    coda: 'ʈ',
    rhymeKey: 'ɪʈ',
    register: 'slang',
    meaning: 'outfit / healthy',
    variants: ['fit'],
    origin: 'English'
  },
  {
    devanagari: 'लिट',
    roman: ['lit'],
    urdu: 'لٹ',
    pronunciations: ['lɪʈ'],
    syllables: 1,
    breakdown: ['lɪʈ'],
    nucleus: 'ɪ',
    coda: 'ʈ',
    rhymeKey: 'ɪʈ',
    register: 'slang',
    meaning: 'wild, exciting, on fire',
    variants: ['lit'],
    origin: 'English'
  },
  {
    devanagari: 'सिट',
    roman: ['sit'],
    urdu: 'سٹ',
    pronunciations: ['sɪʈ'],
    syllables: 1,
    breakdown: ['sɪʈ'],
    nucleus: 'ɪ',
    coda: 'ʈ',
    rhymeKey: 'ɪʈ',
    register: 'common',
    meaning: 'sit down',
    variants: ['sit'],
    origin: 'English'
  }
];
