export interface GoldWordEntry {
  devanagari: string;
  roman: string[];
  urdu?: string;
  pronunciations: string[];
  syllables: number;
  breakdown: string[];
  nucleus: string;
  coda: string;
  rhymeKey: string;
  register: 'common' | 'poetic' | 'slang' | 'technical' | 'literary' | 'colloquial';
  meaning: string;
  variants?: string[];
  origin?: 'Hindustani' | 'Perso-Arabic' | 'Sanskrit' | 'English' | 'Slang';
}

export const GOLD_WORDS: GoldWordEntry[] = [
  // =========================================================================
  // 1. EMOTION & PSYCHE (50 WORDS)
  // =========================================================================
  {
    devanagari: 'प्यार',
    roman: ['pyaar', 'pyar'],
    urdu: 'پیار',
    pronunciations: ['pjaːr'],
    syllables: 1,
    breakdown: ['pjaːr'],
    nucleus: 'aː',
    coda: 'r',
    rhymeKey: 'aːr',
    register: 'common',
    meaning: 'love, affection',
    variants: ['pyaar', 'pyar'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'इश्क़',
    roman: ['ishq', 'ishk'],
    urdu: 'عشق',
    pronunciations: ['ɪʃq', 'ɪʃk'],
    syllables: 1,
    breakdown: ['ɪʃq'],
    nucleus: 'ɪ',
    coda: 'ʃq',
    rhymeKey: 'ɪʃq',
    register: 'poetic',
    meaning: 'passionate love',
    variants: ['ishq', 'ishk', 'ishak'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'दर्द',
    roman: ['dard'],
    urdu: 'درد',
    pronunciations: ['d̪ərd̪'],
    syllables: 1,
    breakdown: ['d̪ərd̪'],
    nucleus: 'ə',
    coda: 'rd̪',
    rhymeKey: 'ərd̪',
    register: 'poetic',
    meaning: 'pain, agony',
    variants: ['dard'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'सुकून',
    roman: ['sukoon', 'sukun'],
    urdu: 'سکون',
    pronunciations: ['sʊ.kuːn'],
    syllables: 2,
    breakdown: ['sʊ', 'kuːn'],
    nucleus: 'uː',
    coda: 'n',
    rhymeKey: 'uːn',
    register: 'common',
    meaning: 'peace, tranquility',
    variants: ['sukoon', 'sukun'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'जुनून',
    roman: ['junoon', 'junun'],
    urdu: 'جنون',
    pronunciations: ['d͡ʒʊ.nuːn'],
    syllables: 2,
    breakdown: ['d͡ʒʊ', 'nuːn'],
    nucleus: 'uː',
    coda: 'n',
    rhymeKey: 'uːn',
    register: 'poetic',
    meaning: 'obsession, madness, zeal',
    variants: ['junoon', 'junun'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'तन्हाई',
    roman: ['tanhai', 'tanhaai'],
    urdu: 'تنہائی',
    pronunciations: ['t̪ən.ɦaː.iː'],
    syllables: 3,
    breakdown: ['t̪ən', 'ɦaː', 'iː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'aːiː',
    register: 'poetic',
    meaning: 'solitude, loneliness',
    variants: ['tanhai', 'tanhaai'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'जुदाई',
    roman: ['judai', 'judaai'],
    urdu: 'جدائی',
    pronunciations: ['d͡ʒʊ.d̪aː.iː'],
    syllables: 3,
    breakdown: ['d͡ʒʊ', 'd̪aː', 'iː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'aːiː',
    register: 'poetic',
    meaning: 'separation',
    variants: ['judai', 'judaai'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'रुसवाई',
    roman: ['ruswai', 'ruswaai'],
    urdu: 'رسوائی',
    pronunciations: ['rʊs.ʋaː.iː'],
    syllables: 3,
    breakdown: ['rʊs', 'ʋaː', 'iː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'aːiː',
    register: 'poetic',
    meaning: 'disgrace, infamy',
    variants: ['ruswai'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'गहराई',
    roman: ['gahrai', 'gehraai'],
    urdu: 'گہرائی',
    pronunciations: ['ɡɛːɦ.raː.iː', 'ɡəɦ.raː.iː'],
    syllables: 3,
    breakdown: ['ɡɛːɦ', 'raː', 'iː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'aːiː',
    register: 'common',
    meaning: 'depth',
    variants: ['gahrai', 'gehrai'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'सच्चाई',
    roman: ['sachai', 'sachhai', 'sachchaai'],
    urdu: 'سچائی',
    pronunciations: ['sət͡ʃ.t͡ʃaː.iː'],
    syllables: 3,
    breakdown: ['sət͡ʃ', 't͡ʃaː', 'iː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'aːiː',
    register: 'common',
    meaning: 'truth, reality',
    variants: ['sachai', 'sacchai'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'नफ़रत',
    roman: ['nafrat'],
    urdu: 'نفرت',
    pronunciations: ['nəf.rət̪', 'nəpʰ.rət̪'],
    syllables: 2,
    breakdown: ['nəf', 'rət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'common',
    meaning: 'hatred',
    variants: ['nafrat', 'naphart'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'हसरत',
    roman: ['hasrat'],
    urdu: 'حسرت',
    pronunciations: ['ɦəs.rət̪'],
    syllables: 2,
    breakdown: ['ɦəs', 'rət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'poetic',
    meaning: 'unfulfilled longing',
    variants: ['hasrat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'ग़म',
    roman: ['gham', 'gam'],
    urdu: 'غم',
    pronunciations: ['ɣəm', 'ɡəm'],
    syllables: 1,
    breakdown: ['ɣəm'],
    nucleus: 'ə',
    coda: 'm',
    rhymeKey: 'əm',
    register: 'poetic',
    meaning: 'sorrow, grief',
    variants: ['gham', 'gam'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'ख़ुशी',
    roman: ['khushi', 'khusi'],
    urdu: 'خوشی',
    pronunciations: ['xʊ.ʃiː', 'kʰʊ.ʃiː'],
    syllables: 2,
    breakdown: ['xʊ', 'ʃiː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'iː',
    register: 'common',
    meaning: 'happiness',
    variants: ['khushi', 'khusi'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'आँसू',
    roman: ['aansu', 'aansoo'],
    urdu: 'آنسو',
    pronunciations: ['ãː.suː'],
    syllables: 2,
    breakdown: ['ãː', 'suː'],
    nucleus: 'uː',
    coda: '',
    rhymeKey: 'uː',
    register: 'common',
    meaning: 'tears',
    variants: ['aansu', 'aansoo'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'हँसी',
    roman: ['hansi', 'hansee'],
    urdu: 'ہنسی',
    pronunciations: ['ɦə̃.siː'],
    syllables: 2,
    breakdown: ['ɦə̃', 'siː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'iː',
    register: 'common',
    meaning: 'laughter',
    variants: ['hansi', 'hasin'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'वफ़ा',
    roman: ['wafa', 'vafa'],
    urdu: 'وفا',
    pronunciations: ['ʋə.faː', 'ʋə.pʰaː'],
    syllables: 2,
    breakdown: ['ʋə', 'faː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aː',
    register: 'poetic',
    meaning: 'loyalty, fidelity',
    variants: ['wafa', 'vafa'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'जफ़ा',
    roman: ['jafa'],
    urdu: 'جفا',
    pronunciations: ['d͡ʒə.faː', 'd͡ʒə.pʰaː'],
    syllables: 2,
    breakdown: ['d͡ʒə', 'faː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aː',
    register: 'poetic',
    meaning: 'oppression, cruelty, unfaithfulness',
    variants: ['jafa'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'सज़ा',
    roman: ['saza', 'saja'],
    urdu: 'سزا',
    pronunciations: ['sə.zaː', 'sə.d͡ʒaː'],
    syllables: 2,
    breakdown: ['sə', 'zaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aː',
    register: 'common',
    meaning: 'punishment',
    variants: ['saza', 'saja'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'मज़ा',
    roman: ['maza', 'maja'],
    urdu: 'مزا',
    pronunciations: ['mə.zaː', 'mə.d͡ʒaː'],
    syllables: 2,
    breakdown: ['mə', 'zaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aː',
    register: 'common',
    meaning: 'fun, enjoyment, taste',
    variants: ['maza', 'maja'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'गुस्सा',
    roman: ['gussa'],
    urdu: 'غصہ',
    pronunciations: ['ɡʊs.saː'],
    syllables: 2,
    breakdown: ['ɡʊs', 'saː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'saː',
    register: 'common',
    meaning: 'anger',
    variants: ['gussa'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'धोखा',
    roman: ['dhokha', 'dhoka'],
    urdu: 'دھوکا',
    pronunciations: ['d̪ʱoː.kʰaː'],
    syllables: 2,
    breakdown: ['d̪ʱoː', 'kʰaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'kʰaː',
    register: 'common',
    meaning: 'betrayal, deception',
    variants: ['dhokha', 'dhoka'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'मौका',
    roman: ['mauka', 'mowka'],
    urdu: 'موقع',
    pronunciations: ['mɔː.kaː'],
    syllables: 2,
    breakdown: ['mɔː', 'kaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'kaː',
    register: 'common',
    meaning: 'opportunity, chance',
    variants: ['mauka', 'moka'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'चौंक',
    roman: ['chaunk', 'chouk'],
    urdu: 'چونک',
    pronunciations: ['t͡ʃɔ̃ːk'],
    syllables: 1,
    breakdown: ['t͡ʃɔ̃ːk'],
    nucleus: 'ɔ̃ː',
    coda: 'k',
    rhymeKey: 'ɔ̃ːk',
    register: 'common',
    meaning: 'surprise, startle',
    variants: ['chaunk'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'ख़ौफ़',
    roman: ['khauf', 'khof'],
    urdu: 'خوف',
    pronunciations: ['xɔːf', 'kʰɔːf'],
    syllables: 1,
    breakdown: ['xɔːf'],
    nucleus: 'ɔː',
    coda: 'f',
    rhymeKey: 'ɔːf',
    register: 'poetic',
    meaning: 'fear, dread',
    variants: ['khauf', 'khof'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'शौक़',
    roman: ['shauq', 'shauk'],
    urdu: 'شوق',
    pronunciations: ['ʃɔːq', 'ʃɔːk'],
    syllables: 1,
    breakdown: ['ʃɔːq'],
    nucleus: 'ɔː',
    coda: 'q',
    rhymeKey: 'ɔːk',
    register: 'poetic',
    meaning: 'passion, fondness',
    variants: ['shauq', 'shauk'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'ज़ौक़',
    roman: ['zauq', 'zauk'],
    urdu: 'ذوق',
    pronunciations: ['zɔːq', 'zɔːk'],
    syllables: 1,
    breakdown: ['zɔːq'],
    nucleus: 'ɔː',
    coda: 'q',
    rhymeKey: 'ɔːk',
    register: 'literary',
    meaning: 'taste, aesthetic discernment',
    variants: ['zauq'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'दीवाना',
    roman: ['deewana', 'diwana'],
    urdu: 'دیوانہ',
    pronunciations: ['d̪iː.ʋaː.naː'],
    syllables: 3,
    breakdown: ['d̪iː', 'ʋaː', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːnaː',
    register: 'poetic',
    meaning: 'madman, passionately in love',
    variants: ['deewana', 'diwana'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'परवाना',
    roman: ['parwana'],
    urdu: 'پروانہ',
    pronunciations: ['pər.ʋaː.naː'],
    syllables: 3,
    breakdown: ['pər', 'ʋaː', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːnaː',
    register: 'poetic',
    meaning: 'moth drawn to flame',
    variants: ['parwana'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'मस्ताना',
    roman: ['mastana'],
    urdu: 'مستانہ',
    pronunciations: ['məs.t̪aː.naː'],
    syllables: 3,
    breakdown: ['məs', 't̪aː', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːnaː',
    register: 'poetic',
    meaning: 'intoxicated, carefree',
    variants: ['mastana'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'फ़साना',
    roman: ['fasana'],
    urdu: 'فسانہ',
    pronunciations: ['fə.saː.naː', 'pʰə.saː.naː'],
    syllables: 3,
    breakdown: ['fə', 'saː', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːnaː',
    register: 'poetic',
    meaning: 'tale, romance, myth',
    variants: ['fasana'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'ज़माना',
    roman: ['zamana'],
    urdu: 'زمانہ',
    pronunciations: ['zə.maː.naː'],
    syllables: 3,
    breakdown: ['zə', 'maː', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːnaː',
    register: 'common',
    meaning: 'era, world, times',
    variants: ['zamana', 'jamana'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'निशाना',
    roman: ['nishana'],
    urdu: 'نشانہ',
    pronunciations: ['nɪ.ʃaː.naː'],
    syllables: 3,
    breakdown: ['nɪ', 'ʃaː', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːnaː',
    register: 'common',
    meaning: 'target, mark, aim',
    variants: ['nishana'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'बहाना',
    roman: ['bahana'],
    urdu: 'بہانہ',
    pronunciations: ['bə.ɦaː.naː'],
    syllables: 3,
    breakdown: ['bə', 'ɦaː', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːnaː',
    register: 'common',
    meaning: 'excuse, pretense',
    variants: ['bahana'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'तराना',
    roman: ['tarana'],
    urdu: 'ترانہ',
    pronunciations: ['t̪ə.raː.naː'],
    syllables: 3,
    breakdown: ['t̪ə', 'raː', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːnaː',
    register: 'poetic',
    meaning: 'anthem, song, melody',
    variants: ['tarana'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'आशियाना',
    roman: ['aashiyana', 'aashiana'],
    urdu: 'آشیانہ',
    pronunciations: ['aː.ʃɪ.jaː.naː'],
    syllables: 4,
    breakdown: ['aː', 'ʃɪ', 'jaː', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːnaː',
    register: 'poetic',
    meaning: 'nest, abode, home',
    variants: ['aashiyana'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'मयख़ाना',
    roman: ['maikhana', 'maykhana'],
    urdu: 'میخانہ',
    pronunciations: ['mɛː.xaː.naː', 'mɛː.kʰaː.naː'],
    syllables: 3,
    breakdown: ['mɛː', 'xaː', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːnaː',
    register: 'poetic',
    meaning: 'tavern, bar',
    variants: ['maikhana'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'पैमाना',
    roman: ['paimana', 'paymana'],
    urdu: 'پیمانہ',
    pronunciations: ['pɛː.maː.naː'],
    syllables: 3,
    breakdown: ['pɛː', 'maː', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːnaː',
    register: 'poetic',
    meaning: 'goblet, measure',
    variants: ['paimana'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'शर्म',
    roman: ['sharm'],
    urdu: 'شرم',
    pronunciations: ['ʃərm'],
    syllables: 1,
    breakdown: ['ʃərm'],
    nucleus: 'ə',
    coda: 'rm',
    rhymeKey: 'ərm',
    register: 'common',
    meaning: 'shame, modesty',
    variants: ['sharm'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'गर्म',
    roman: ['garm'],
    urdu: 'گرم',
    pronunciations: ['ɡərm'],
    syllables: 1,
    breakdown: ['ɡərm'],
    nucleus: 'ə',
    coda: 'rm',
    rhymeKey: 'ərm',
    register: 'common',
    meaning: 'hot, warm',
    variants: ['garm'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'नर्म',
    roman: ['narm'],
    urdu: 'نرم',
    pronunciations: ['nərm'],
    syllables: 1,
    breakdown: ['nərm'],
    nucleus: 'ə',
    coda: 'rm',
    rhymeKey: 'ərm',
    register: 'common',
    meaning: 'soft, gentle',
    variants: ['narm'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'धड़कन',
    roman: ['dhadkan', 'dhadakan'],
    urdu: 'دھڑکن',
    pronunciations: ['d̪ʱəɽ.kən'],
    syllables: 2,
    breakdown: ['d̪ʱəɽ', 'kən'],
    nucleus: 'ə',
    coda: 'n',
    rhymeKey: 'ən',
    register: 'poetic',
    meaning: 'heartbeat',
    variants: ['dhadkan'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'तड़प',
    roman: ['tadap'],
    urdu: 'تڑپ',
    pronunciations: ['t̪ə.ɽəp'],
    syllables: 2,
    breakdown: ['t̪ə', 'ɽəp'],
    nucleus: 'ə',
    coda: 'p',
    rhymeKey: 'əp',
    register: 'poetic',
    meaning: 'restlessness, throbbing ache',
    variants: ['tadap'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'आस',
    roman: ['aas'],
    urdu: 'آس',
    pronunciations: ['aːs'],
    syllables: 1,
    breakdown: ['aːs'],
    nucleus: 'aː',
    coda: 's',
    rhymeKey: 'aːs',
    register: 'poetic',
    meaning: 'hope, longing',
    variants: ['aas'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'प्यास',
    roman: ['pyaas', 'pyas'],
    urdu: 'پیاس',
    pronunciations: ['pjaːs'],
    syllables: 1,
    breakdown: ['pjaːs'],
    nucleus: 'aː',
    coda: 's',
    rhymeKey: 'aːs',
    register: 'common',
    meaning: 'thirst',
    variants: ['pyaas'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'सास',
    roman: ['saas'],
    urdu: 'ساس',
    pronunciations: ['saːs'],
    syllables: 1,
    breakdown: ['saːs'],
    nucleus: 'aː',
    coda: 's',
    rhymeKey: 'aːs',
    register: 'common',
    meaning: 'mother-in-law',
    variants: ['saas'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'एहसास',
    roman: ['ehsaas', 'ehsas'],
    urdu: 'احساس',
    pronunciations: ['ɛːɦ.saːs', 'əɦ.saːs'],
    syllables: 2,
    breakdown: ['ɛːɦ', 'saːs'],
    nucleus: 'aː',
    coda: 's',
    rhymeKey: 'aːs',
    register: 'poetic',
    meaning: 'feeling, realization',
    variants: ['ehsaas', 'ehsas'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'विश्वास',
    roman: ['vishwas', 'viswas'],
    urdu: 'وشواس',
    pronunciations: ['ʋɪʃ.ʋaːs', 'ʋɪs.ʋaːs'],
    syllables: 2,
    breakdown: ['ʋɪʃ', 'ʋaːs'],
    nucleus: 'aː',
    coda: 's',
    rhymeKey: 'aːs',
    register: 'common',
    meaning: 'trust, faith',
    variants: ['vishwas'],
    origin: 'Sanskrit'
  },
  {
    devanagari: 'जज़्बा',
    roman: ['jazba', 'jazbaa'],
    urdu: 'جذبہ',
    pronunciations: ['d͡ʒəz.baː'],
    syllables: 2,
    breakdown: ['d͡ʒəz', 'baː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'baː',
    register: 'poetic',
    meaning: 'emotion, passion',
    variants: ['jazba'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'जज़्बात',
    roman: ['jazbaat', 'jazbat'],
    urdu: 'جذبات',
    pronunciations: ['d͡ʒəz.baːt̪'],
    syllables: 2,
    breakdown: ['d͡ʒəz', 'baːt̪'],
    nucleus: 'aː',
    coda: 't̪',
    rhymeKey: 'aːt̪',
    register: 'poetic',
    meaning: 'emotions, sentiments',
    variants: ['jazbaat'],
    origin: 'Perso-Arabic'
  },

  // =========================================================================
  // 2. TIME & SPACE (40 WORDS)
  // =========================================================================
  {
    devanagari: 'रात',
    roman: ['raat', 'rat'],
    urdu: 'رات',
    pronunciations: ['raːt̪'],
    syllables: 1,
    breakdown: ['raːt̪'],
    nucleus: 'aː',
    coda: 't̪',
    rhymeKey: 'aːt̪',
    register: 'common',
    meaning: 'night',
    variants: ['raat'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'दिन',
    roman: ['din'],
    urdu: 'دن',
    pronunciations: ['d̪ɪn'],
    syllables: 1,
    breakdown: ['d̪ɪn'],
    nucleus: 'ɪ',
    coda: 'n',
    rhymeKey: 'ɪn',
    register: 'common',
    meaning: 'day',
    variants: ['din'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'गिन',
    roman: ['gin'],
    urdu: 'گن',
    pronunciations: ['ɡɪn'],
    syllables: 1,
    breakdown: ['ɡɪn'],
    nucleus: 'ɪ',
    coda: 'n',
    rhymeKey: 'ɪn',
    register: 'common',
    meaning: 'count',
    variants: ['gin'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'पिन',
    roman: ['pin'],
    urdu: 'پن',
    pronunciations: ['pɪn'],
    syllables: 1,
    breakdown: ['pɪn'],
    nucleus: 'ɪ',
    coda: 'n',
    rhymeKey: 'ɪn',
    register: 'common',
    meaning: 'pin',
    variants: ['pin'],
    origin: 'English'
  },
  {
    devanagari: 'छिन',
    roman: ['chhin', 'chin'],
    urdu: 'چھن',
    pronunciations: ['t͡ʃʰɪn'],
    syllables: 1,
    breakdown: ['t͡ʃʰɪn'],
    nucleus: 'ɪ',
    coda: 'n',
    rhymeKey: 'ɪn',
    register: 'poetic',
    meaning: 'moment, snatch away',
    variants: ['chhin'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'शहर',
    roman: ['shahar', 'shehar'],
    urdu: 'شہر',
    pronunciations: ['ʃɛː.ɦər', 'ʃə.ɦər'],
    syllables: 2,
    breakdown: ['ʃɛː', 'ɦər'],
    nucleus: 'ə',
    coda: 'r',
    rhymeKey: 'ər',
    register: 'common',
    meaning: 'city',
    variants: ['shahar', 'shehar'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'ज़हर',
    roman: ['zahar', 'zehar'],
    urdu: 'زہر',
    pronunciations: ['zɛː.ɦər', 'zə.ɦər'],
    syllables: 2,
    breakdown: ['zɛː', 'ɦər'],
    nucleus: 'ə',
    coda: 'r',
    rhymeKey: 'ər',
    register: 'poetic',
    meaning: 'poison',
    variants: ['zahar', 'zehar'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'क़हर',
    roman: ['qahar', 'kahar'],
    urdu: 'قہر',
    pronunciations: ['qɛː.ɦər', 'kɛː.ɦər'],
    syllables: 2,
    breakdown: ['qɛː', 'ɦər'],
    nucleus: 'ə',
    coda: 'r',
    rhymeKey: 'ər',
    register: 'poetic',
    meaning: 'wrath, devastation',
    variants: ['qahar', 'kahar'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'लहर',
    roman: ['lahar', 'lehar'],
    urdu: 'لہر',
    pronunciations: ['lɛː.ɦər', 'lə.ɦər'],
    syllables: 2,
    breakdown: ['lɛː', 'ɦər'],
    nucleus: 'ə',
    coda: 'r',
    rhymeKey: 'ər',
    register: 'common',
    meaning: 'wave',
    variants: ['lahar', 'lehar'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'पहर',
    roman: ['pahar', 'pehar'],
    urdu: 'پہر',
    pronunciations: ['pɛː.ɦər', 'pə.ɦər'],
    syllables: 2,
    breakdown: ['pɛː', 'ɦər'],
    nucleus: 'ə',
    coda: 'r',
    rhymeKey: 'ər',
    register: 'poetic',
    meaning: 'watch of the day, 3-hour period',
    variants: ['pahar'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'सफ़र',
    roman: ['safar'],
    urdu: 'سفر',
    pronunciations: ['sə.fər', 'sə.pʰər'],
    syllables: 2,
    breakdown: ['sə', 'fər'],
    nucleus: 'ə',
    coda: 'r',
    rhymeKey: 'ər',
    register: 'common',
    meaning: 'journey, voyage',
    variants: ['safar'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'असर',
    roman: ['asar'],
    urdu: 'اثر',
    pronunciations: ['ə.sər'],
    syllables: 2,
    breakdown: ['ə', 'sər'],
    nucleus: 'ə',
    coda: 'r',
    rhymeKey: 'ər',
    register: 'common',
    meaning: 'effect, impact',
    variants: ['asar'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'ख़बर',
    roman: ['khabar'],
    urdu: 'خبر',
    pronunciations: ['xə.bər', 'kʰə.bər'],
    syllables: 2,
    breakdown: ['xə', 'bər'],
    nucleus: 'ə',
    coda: 'r',
    rhymeKey: 'ər',
    register: 'common',
    meaning: 'news, awareness',
    variants: ['khabar'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'नज़र',
    roman: ['nazar'],
    urdu: 'نظر',
    pronunciations: ['nə.zər'],
    syllables: 2,
    breakdown: ['nə', 'zər'],
    nucleus: 'ə',
    coda: 'r',
    rhymeKey: 'ər',
    register: 'common',
    meaning: 'gaze, glance, evil eye',
    variants: ['nazar', 'najar'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'सवेरा',
    roman: ['savera'],
    urdu: 'سویرا',
    pronunciations: ['sə.ʋeː.raː'],
    syllables: 3,
    breakdown: ['sə', 'ʋeː', 'raː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'eːraː',
    register: 'poetic',
    meaning: 'dawn, morning',
    variants: ['savera'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'अंधेरा',
    roman: ['andhera'],
    urdu: 'اندھیرا',
    pronunciations: ['ən.d̪ʱeː.raː'],
    syllables: 3,
    breakdown: ['ən', 'd̪ʱeː', 'raː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'eːraː',
    register: 'common',
    meaning: 'darkness',
    variants: ['andhera'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'डेरा',
    roman: ['dera'],
    urdu: 'ڈیرا',
    pronunciations: ['ɖeː.raː'],
    syllables: 2,
    breakdown: ['ɖeː', 'raː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'eːraː',
    register: 'colloquial',
    meaning: 'camp, settlement',
    variants: ['dera'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'घेरा',
    roman: ['ghera'],
    urdu: 'گھیرا',
    pronunciations: ['ɡʱeː.raː'],
    syllables: 2,
    breakdown: ['ɡʱeː', 'raː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'eːraː',
    register: 'common',
    meaning: 'circle, siege',
    variants: ['ghera'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'गली',
    roman: ['gali'],
    urdu: 'گلی',
    pronunciations: ['ɡə.liː'],
    syllables: 2,
    breakdown: ['ɡə', 'liː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'liː',
    register: 'common',
    meaning: 'lane, street',
    variants: ['gali'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'सड़क',
    roman: ['sadak'],
    urdu: 'سڑک',
    pronunciations: ['sə.ɽək'],
    syllables: 2,
    breakdown: ['sə', 'ɽək'],
    nucleus: 'ə',
    coda: 'k',
    rhymeKey: 'ək',
    register: 'common',
    meaning: 'road',
    variants: ['sadak'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'कमरा',
    roman: ['kamra'],
    urdu: 'کمرہ',
    pronunciations: ['kəm.raː'],
    syllables: 2,
    breakdown: ['kəm', 'raː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'raː',
    register: 'common',
    meaning: 'room',
    variants: ['kamra', 'kamara'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'दरवाज़ा',
    roman: ['darwaza', 'darwaja'],
    urdu: 'دروازہ',
    pronunciations: ['d̪ər.ʋaː.zaː', 'd̪ər.ʋaː.d͡ʒaː'],
    syllables: 3,
    breakdown: ['d̪ər', 'ʋaː', 'zaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːzaː',
    register: 'common',
    meaning: 'door',
    variants: ['darwaza', 'darwaja'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'छत',
    roman: ['chhat', 'chat'],
    urdu: 'چھت',
    pronunciations: ['t͡ʃʰət̪'],
    syllables: 1,
    breakdown: ['t͡ʃʰət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'common',
    meaning: 'roof, ceiling',
    variants: ['chhat'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'दुनिया',
    roman: ['duniya'],
    urdu: 'دنیا',
    pronunciations: ['d̪ʊ.nɪ.jaː'],
    syllables: 3,
    breakdown: ['d̪ʊ', 'nɪ', 'jaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'ɪjaː',
    register: 'common',
    meaning: 'world',
    variants: ['duniya'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'ज़मीन',
    roman: ['zameen', 'zamin'],
    urdu: 'زمین',
    pronunciations: ['zə.miːn'],
    syllables: 2,
    breakdown: ['zə', 'miːn'],
    nucleus: 'iː',
    coda: 'n',
    rhymeKey: 'iːn',
    register: 'common',
    meaning: 'earth, ground',
    variants: ['zameen', 'zamin'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'आसमान',
    roman: ['aasman', 'aasmaan'],
    urdu: 'آسمان',
    pronunciations: ['aːs.maːn'],
    syllables: 2,
    breakdown: ['aːs', 'maːn'],
    nucleus: 'aː',
    coda: 'n',
    rhymeKey: 'aːn',
    register: 'common',
    meaning: 'sky, heaven',
    variants: ['aasman', 'aasmaan'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'जहान',
    roman: ['jahan', 'jahaan'],
    urdu: 'جہان',
    pronunciations: ['d͡ʒə.ɦaːn'],
    syllables: 2,
    breakdown: ['d͡ʒə', 'ɦaːn'],
    nucleus: 'aː',
    coda: 'n',
    rhymeKey: 'aːn',
    register: 'poetic',
    meaning: 'universe, realm',
    variants: ['jahan'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'मकान',
    roman: ['makan', 'makaan'],
    urdu: 'مکان',
    pronunciations: ['mə.kaːn'],
    syllables: 2,
    breakdown: ['mə', 'kaːn'],
    nucleus: 'aː',
    coda: 'n',
    rhymeKey: 'aːn',
    register: 'common',
    meaning: 'house, building',
    variants: ['makan'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'दुकान',
    roman: ['dukan', 'dukaan'],
    urdu: 'دکان',
    pronunciations: ['d̪ʊ.kaːn'],
    syllables: 2,
    breakdown: ['d̪ʊ', 'kaːn'],
    nucleus: 'aː',
    coda: 'n',
    rhymeKey: 'aːn',
    register: 'common',
    meaning: 'shop, store',
    variants: ['dukan'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'निशान',
    roman: ['nishan', 'nishaan'],
    urdu: 'نشان',
    pronunciations: ['nɪ.ʃaːn'],
    syllables: 2,
    breakdown: ['nɪ', 'ʃaːn'],
    nucleus: 'aː',
    coda: 'n',
    rhymeKey: 'aːn',
    register: 'common',
    meaning: 'sign, trace, scar',
    variants: ['nishan'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'बयान',
    roman: ['bayan', 'bayaan'],
    urdu: 'بیان',
    pronunciations: ['bə.jaːn'],
    syllables: 2,
    breakdown: ['bə', 'jaːn'],
    nucleus: 'aː',
    coda: 'n',
    rhymeKey: 'aːn',
    register: 'poetic',
    meaning: 'expression, testimony',
    variants: ['bayan'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'गुज़र',
    roman: ['guzar'],
    urdu: 'گزر',
    pronunciations: ['ɡʊ.zər'],
    syllables: 2,
    breakdown: ['ɡʊ', 'zər'],
    nucleus: 'ə',
    coda: 'r',
    rhymeKey: 'ər',
    register: 'common',
    meaning: 'passage, living, elapse',
    variants: ['guzar', 'gujar'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'हवा',
    roman: ['hawa'],
    urdu: 'ہوا',
    pronunciations: ['ɦə.ʋaː'],
    syllables: 2,
    breakdown: ['ɦə', 'ʋaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aː',
    register: 'common',
    meaning: 'wind, air',
    variants: ['hawa'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'दुआ',
    roman: ['dua', 'duaa'],
    urdu: 'دعا',
    pronunciations: ['d̪ʊ.aː'],
    syllables: 2,
    breakdown: ['d̪ʊ', 'aː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aː',
    register: 'poetic',
    meaning: 'prayer, blessing',
    variants: ['dua'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'दवा',
    roman: ['dawa'],
    urdu: 'دوا',
    pronunciations: ['d̪ə.ʋaː'],
    syllables: 2,
    breakdown: ['d̪ə', 'ʋaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aː',
    register: 'common',
    meaning: 'medicine, cure',
    variants: ['dawa'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'किनारा',
    roman: ['kinara'],
    urdu: 'کنارہ',
    pronunciations: ['kɪ.naː.raː'],
    syllables: 3,
    breakdown: ['kɪ', 'naː', 'raː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːraː',
    register: 'poetic',
    meaning: 'shore, edge',
    variants: ['kinara'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'सहारा',
    roman: ['sahara'],
    urdu: 'سہارا',
    pronunciations: ['sə.ɦaː.raː'],
    syllables: 3,
    breakdown: ['sə', 'ɦaː', 'raː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːraː',
    register: 'common',
    meaning: 'support, refuge',
    variants: ['sahara'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'सितारा',
    roman: ['sitara'],
    urdu: 'ستارہ',
    pronunciations: ['sɪ.t̪aː.raː'],
    syllables: 3,
    breakdown: ['sɪ', 't̪aː', 'raː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːraː',
    register: 'poetic',
    meaning: 'star',
    variants: ['sitara'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'इशारा',
    roman: ['ishara'],
    urdu: 'اشارہ',
    pronunciations: ['ɪ.ʃaː.raː'],
    syllables: 3,
    breakdown: ['ɪ', 'ʃaː', 'raː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːraː',
    register: 'common',
    meaning: 'gesture, hint',
    variants: ['ishara'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'नज़ारा',
    roman: ['nazara'],
    urdu: 'نظارہ',
    pronunciations: ['nə.zaː.raː'],
    syllables: 3,
    breakdown: ['nə', 'zaː', 'raː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːraː',
    register: 'poetic',
    meaning: 'view, spectacle, sight',
    variants: ['nazara', 'najara'],
    origin: 'Perso-Arabic'
  },

  // =========================================================================
  // 3. ABSTRACT, PHILOSOPHY & LIFE (45 WORDS)
  // =========================================================================
  {
    devanagari: 'ज़िंदगी',
    roman: ['zindagi'],
    urdu: 'زندگی',
    pronunciations: ['zɪn.d̪ə.ɡiː'],
    syllables: 3,
    breakdown: ['zɪn', 'd̪ə', 'ɡiː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'ɡiː',
    register: 'common',
    meaning: 'life',
    variants: ['zindagi'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'बंदगी',
    roman: ['bandagi'],
    urdu: 'بندگی',
    pronunciations: ['bən.d̪ə.ɡiː'],
    syllables: 3,
    breakdown: ['bən', 'd̪ə', 'ɡiː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'ɡiː',
    register: 'poetic',
    meaning: 'devotion, worship',
    variants: ['bandagi'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'सादगी',
    roman: ['saadgi'],
    urdu: 'سادگی',
    pronunciations: ['saːd̪.ɡiː'],
    syllables: 2,
    breakdown: ['saːd̪', 'ɡiː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'ɡiː',
    register: 'poetic',
    meaning: 'simplicity',
    variants: ['saadgi'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'ताज़गी',
    roman: ['tazgi', 'taazgi'],
    urdu: 'تازگی',
    pronunciations: ['t̪aːz.ɡiː'],
    syllables: 2,
    breakdown: ['t̪aːz', 'ɡiː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'ɡiː',
    register: 'poetic',
    meaning: 'freshness',
    variants: ['tazgi', 'taazgi'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'मौत',
    roman: ['maut', 'mot'],
    urdu: 'موت',
    pronunciations: ['mɔːt̪'],
    syllables: 1,
    breakdown: ['mɔːt̪'],
    nucleus: 'ɔː',
    coda: 't̪',
    rhymeKey: 'ɔːt̪',
    register: 'common',
    meaning: 'death',
    variants: ['maut', 'mot'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'ख़ौफ़',
    roman: ['khauf'],
    urdu: 'خوف',
    pronunciations: ['xɔːf'],
    syllables: 1,
    breakdown: ['xɔːf'],
    nucleus: 'ɔː',
    coda: 'f',
    rhymeKey: 'ɔːf',
    register: 'poetic',
    meaning: 'terror',
    variants: ['khauf'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'किस्मत',
    roman: ['kismat'],
    urdu: 'قسمت',
    pronunciations: ['kɪs.mət̪'],
    syllables: 2,
    breakdown: ['kɪs', 'mət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'common',
    meaning: 'fate, destiny',
    variants: ['kismat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'हक़ीक़त',
    roman: ['haqeeqat', 'haqiqat'],
    urdu: 'حقیقت',
    pronunciations: ['ɦə.qiː.qət̪', 'ɦə.kiː.kət̪'],
    syllables: 3,
    breakdown: ['ɦə', 'qiː', 'qət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'poetic',
    meaning: 'reality, fundamental truth',
    variants: ['haqeeqat', 'haqiqat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'हक़',
    roman: ['haq', 'hak'],
    urdu: 'حق',
    pronunciations: ['ɦəq', 'ɦək'],
    syllables: 1,
    breakdown: ['ɦəq'],
    nucleus: 'ə',
    coda: 'q',
    rhymeKey: 'ək',
    register: 'common',
    meaning: 'right, entitlement, truth',
    variants: ['haq', 'hak'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'शक',
    roman: ['shak'],
    urdu: 'شک',
    pronunciations: ['ʃək'],
    syllables: 1,
    breakdown: ['ʃək'],
    nucleus: 'ə',
    coda: 'k',
    rhymeKey: 'ək',
    register: 'common',
    meaning: 'doubt, suspicion',
    variants: ['shak'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'तक',
    roman: ['tak'],
    urdu: 'تک',
    pronunciations: ['t̪ək'],
    syllables: 1,
    breakdown: ['t̪ək'],
    nucleus: 'ə',
    coda: 'k',
    rhymeKey: 'ək',
    register: 'common',
    meaning: 'until, up to',
    variants: ['tak'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'सच',
    roman: ['sach'],
    urdu: 'سچ',
    pronunciations: ['sət͡ʃ'],
    syllables: 1,
    breakdown: ['sət͡ʃ'],
    nucleus: 'ə',
    coda: 't͡ʃ',
    rhymeKey: 'ət͡ʃ',
    register: 'common',
    meaning: 'truth',
    variants: ['sach'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'झूठ',
    roman: ['jhooth', 'jhoot'],
    urdu: 'جھوٹ',
    pronunciations: ['d͡ʒʱuːʈʰ'],
    syllables: 1,
    breakdown: ['d͡ʒʱuːʈʰ'],
    nucleus: 'uː',
    coda: 'ʈʰ',
    rhymeKey: 'uːʈʰ',
    register: 'common',
    meaning: 'lie, falsehood',
    variants: ['jhooth'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'घूंट',
    roman: ['ghoont', 'ghunt'],
    urdu: 'گھونٹ',
    pronunciations: ['ɡʱũːʈ'],
    syllables: 1,
    breakdown: ['ɡʱũːʈ'],
    nucleus: 'ũː',
    coda: 'ʈ',
    rhymeKey: 'ũːʈ',
    register: 'common',
    meaning: 'sip, gulp',
    variants: ['ghoont'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'सवाल',
    roman: ['sawal'],
    urdu: 'سوال',
    pronunciations: ['sə.ʋaːl'],
    syllables: 2,
    breakdown: ['sə', 'ʋaːl'],
    nucleus: 'aː',
    coda: 'l',
    rhymeKey: 'aːl',
    register: 'common',
    meaning: 'question',
    variants: ['sawal'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'जवाब',
    roman: ['jawab'],
    urdu: 'جواب',
    pronunciations: ['d͡ʒə.ʋaːb'],
    syllables: 2,
    breakdown: ['d͡ʒə', 'ʋaːb'],
    nucleus: 'aː',
    coda: 'b',
    rhymeKey: 'aːb',
    register: 'common',
    meaning: 'answer, reply',
    variants: ['jawab'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'हिसाब',
    roman: ['hisab', 'hisaab'],
    urdu: 'حساب',
    pronunciations: ['ɦɪ.saːb'],
    syllables: 2,
    breakdown: ['ɦɪ', 'saːb'],
    nucleus: 'aː',
    coda: 'b',
    rhymeKey: 'aːb',
    register: 'common',
    meaning: 'reckoning, calculation, ledger',
    variants: ['hisab', 'hisaab'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'किताब',
    roman: ['kitab', 'kitaab'],
    urdu: 'کتاب',
    pronunciations: ['kɪ.t̪aːb'],
    syllables: 2,
    breakdown: ['kɪ', 't̪aːb'],
    nucleus: 'aː',
    coda: 'b',
    rhymeKey: 'aːb',
    register: 'common',
    meaning: 'book',
    variants: ['kitab'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'गुलाब',
    roman: ['gulab', 'gulaab'],
    urdu: 'گلاب',
    pronunciations: ['ɡʊ.laːb'],
    syllables: 2,
    breakdown: ['ɡʊ', 'laːb'],
    nucleus: 'aː',
    coda: 'b',
    rhymeKey: 'aːb',
    register: 'common',
    meaning: 'rose',
    variants: ['gulab'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'शराब',
    roman: ['sharab', 'sharaab'],
    urdu: 'شراب',
    pronunciations: ['ʃə.raːb'],
    syllables: 2,
    breakdown: ['ʃə', 'raːb'],
    nucleus: 'aː',
    coda: 'b',
    rhymeKey: 'aːb',
    register: 'poetic',
    meaning: 'wine, alcohol',
    variants: ['sharab'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'ख़राब',
    roman: ['kharab', 'kharaab'],
    urdu: 'خراب',
    pronunciations: ['xə.raːb', 'kʰə.raːb'],
    syllables: 2,
    breakdown: ['xə', 'raːb'],
    nucleus: 'aː',
    coda: 'b',
    rhymeKey: 'aːb',
    register: 'common',
    meaning: 'ruined, bad, broken',
    variants: ['kharab'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'ख़्वाब',
    roman: ['khwaab', 'khwab'],
    urdu: 'خواب',
    pronunciations: ['xʷaːb', 'kʰʷaːb'],
    syllables: 1,
    breakdown: ['xʷaːb'],
    nucleus: 'aː',
    coda: 'b',
    rhymeKey: 'aːb',
    register: 'poetic',
    meaning: 'dream, vision',
    variants: ['khwaab', 'khwab'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'आब',
    roman: ['aab'],
    urdu: 'آب',
    pronunciations: ['aːb'],
    syllables: 1,
    breakdown: ['aːb'],
    nucleus: 'aː',
    coda: 'b',
    rhymeKey: 'aːb',
    register: 'poetic',
    meaning: 'water, luster',
    variants: ['aab'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'ताबीर',
    roman: ['tabeer', 'tabir'],
    urdu: 'تعبیر',
    pronunciations: ['t̪aː.biːr'],
    syllables: 2,
    breakdown: ['t̪aː', 'biːr'],
    nucleus: 'iː',
    coda: 'r',
    rhymeKey: 'iːr',
    register: 'poetic',
    meaning: 'interpretation of dream',
    variants: ['tabeer'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'तस्वीर',
    roman: ['tasveer', 'tasvir'],
    urdu: 'تصویر',
    pronunciations: ['t̪əs.ʋiːr'],
    syllables: 2,
    breakdown: ['t̪əs', 'ʋiːr'],
    nucleus: 'iː',
    coda: 'r',
    rhymeKey: 'iːr',
    register: 'common',
    meaning: 'picture, portrait',
    variants: ['tasveer'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'तक़दीर',
    roman: ['taqdeer', 'takdir'],
    urdu: 'تقدیر',
    pronunciations: ['t̪əq.d̪iːr', 't̪ək.d̪iːr'],
    syllables: 2,
    breakdown: ['t̪əq', 'd̪iːr'],
    nucleus: 'iː',
    coda: 'r',
    rhymeKey: 'iːr',
    register: 'poetic',
    meaning: 'fate, providence',
    variants: ['taqdeer'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'ज़ंजीर',
    roman: ['zanjeer', 'zanjir'],
    urdu: 'زنجیر',
    pronunciations: ['zən.d͡ʒiːr'],
    syllables: 2,
    breakdown: ['zən', 'd͡ʒiːr'],
    nucleus: 'iː',
    coda: 'r',
    rhymeKey: 'iːr',
    register: 'poetic',
    meaning: 'chain, shackle',
    variants: ['zanjeer'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'शमशीर',
    roman: ['shamsheer'],
    urdu: 'شمشیر',
    pronunciations: ['ʃəm.ʃiːr'],
    syllables: 2,
    breakdown: ['ʃəm', 'ʃiːr'],
    nucleus: 'iː',
    coda: 'r',
    rhymeKey: 'iːr',
    register: 'literary',
    meaning: 'sword',
    variants: ['shamsheer'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'तीर',
    roman: ['teer', 'tir'],
    urdu: 'تیر',
    pronunciations: ['t̪iːr'],
    syllables: 1,
    breakdown: ['t̪iːr'],
    nucleus: 'iː',
    coda: 'r',
    rhymeKey: 'iːr',
    register: 'common',
    meaning: 'arrow',
    variants: ['teer'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'पीर',
    roman: ['peer', 'pir'],
    urdu: 'پیر',
    pronunciations: ['piːr'],
    syllables: 1,
    breakdown: ['piːr'],
    nucleus: 'iː',
    coda: 'r',
    rhymeKey: 'iːr',
    register: 'poetic',
    meaning: 'spiritual master, saint, pain',
    variants: ['peer'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'नीर',
    roman: ['neer', 'nir'],
    urdu: 'نیر',
    pronunciations: ['niːr'],
    syllables: 1,
    breakdown: ['niːr'],
    nucleus: 'iː',
    coda: 'r',
    rhymeKey: 'iːr',
    register: 'poetic',
    meaning: 'water, tear',
    variants: ['neer'],
    origin: 'Sanskrit'
  },
  {
    devanagari: 'फकीर',
    roman: ['faqeer', 'fakir'],
    urdu: 'فقیر',
    pronunciations: ['fə.qiːr', 'pʰə.kiːr'],
    syllables: 2,
    breakdown: ['fə', 'qiːr'],
    nucleus: 'iː',
    coda: 'r',
    rhymeKey: 'iːr',
    register: 'poetic',
    meaning: 'hermit, ascetic, beggar',
    variants: ['faqeer', 'fakir'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'अमीर',
    roman: ['ameer', 'amir'],
    urdu: 'امیر',
    pronunciations: ['ə.miːr'],
    syllables: 2,
    breakdown: ['ə', 'miːr'],
    nucleus: 'iː',
    coda: 'r',
    rhymeKey: 'iːr',
    register: 'common',
    meaning: 'rich, noble',
    variants: ['ameer'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'ग़रीब',
    roman: ['gareeb', 'gharib'],
    urdu: 'غریب',
    pronunciations: ['ɣə.riːb', 'ɡə.riːb'],
    syllables: 2,
    breakdown: ['ɣə', 'riːb'],
    nucleus: 'iː',
    coda: 'b',
    rhymeKey: 'iːb',
    register: 'common',
    meaning: 'poor, strange',
    variants: ['gareeb'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'क़रीब',
    roman: ['qareeb', 'karib'],
    urdu: 'قریب',
    pronunciations: ['qə.riːb', 'kə.riːb'],
    syllables: 2,
    breakdown: ['qə', 'riːb'],
    nucleus: 'iː',
    coda: 'b',
    rhymeKey: 'iːb',
    register: 'common',
    meaning: 'near, close',
    variants: ['qareeb'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'नसीब',
    roman: ['naseeb', 'nasib'],
    urdu: 'نصیب',
    pronunciations: ['nə.siːb'],
    syllables: 2,
    breakdown: ['nə', 'siːb'],
    nucleus: 'iː',
    coda: 'b',
    rhymeKey: 'iːb',
    register: 'poetic',
    meaning: 'fortune, luck',
    variants: ['naseeb'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'हबीब',
    roman: ['habeeb', 'habib'],
    urdu: 'حبیب',
    pronunciations: ['ɦə.biːb'],
    syllables: 2,
    breakdown: ['ɦə', 'biːb'],
    nucleus: 'iː',
    coda: 'b',
    rhymeKey: 'iːb',
    register: 'poetic',
    meaning: 'beloved, companion',
    variants: ['habeeb'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'तबीब',
    roman: ['tabeeb', 'tabib'],
    urdu: 'طبیب',
    pronunciations: ['t̪ə.biːb'],
    syllables: 2,
    breakdown: ['t̪ə', 'biːb'],
    nucleus: 'iː',
    coda: 'b',
    rhymeKey: 'iːb',
    register: 'poetic',
    meaning: 'physician, healer',
    variants: ['tabeeb'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'अजीब',
    roman: ['ajeeb', 'ajib'],
    urdu: 'عجیب',
    pronunciations: ['ə.d͡ʒiːb'],
    syllables: 2,
    breakdown: ['ə', 'd͡ʒiːb'],
    nucleus: 'iː',
    coda: 'b',
    rhymeKey: 'iːb',
    register: 'common',
    meaning: 'strange, bizarre',
    variants: ['ajeeb'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'रकीब',
    roman: ['raqeeq', 'raqeeb', 'rakib'],
    urdu: 'رقیب',
    pronunciations: ['rə.qiːb', 'rə.kiːb'],
    syllables: 2,
    breakdown: ['rə', 'qiːb'],
    nucleus: 'iː',
    coda: 'b',
    rhymeKey: 'iːb',
    register: 'poetic',
    meaning: 'rival, romantic rival',
    variants: ['raqeeb'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'मंज़िल',
    roman: ['manzil'],
    urdu: 'منزل',
    pronunciations: ['mən.zɪl'],
    syllables: 2,
    breakdown: ['mən', 'zɪl'],
    nucleus: 'ɪ',
    coda: 'l',
    rhymeKey: 'ɪl',
    register: 'poetic',
    meaning: 'destination',
    variants: ['manzil'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'साहिल',
    roman: ['sahil'],
    urdu: 'ساحل',
    pronunciations: ['saː.ɦɪl'],
    syllables: 2,
    breakdown: ['saː', 'ɦɪl'],
    nucleus: 'ɪ',
    coda: 'l',
    rhymeKey: 'ɪl',
    register: 'poetic',
    meaning: 'shore, beach',
    variants: ['sahil'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'महफ़िल',
    roman: ['mehfil', 'mahfil'],
    urdu: 'محفل',
    pronunciations: ['mɛːɦ.fɪl', 'məɦ.fɪl'],
    syllables: 2,
    breakdown: ['mɛːɦ', 'fɪl'],
    nucleus: 'ɪ',
    coda: 'l',
    rhymeKey: 'ɪl',
    register: 'poetic',
    meaning: 'gathering, assembly',
    variants: ['mehfil'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'क़ातिल',
    roman: ['qatil', 'kaatil'],
    urdu: 'قاتل',
    pronunciations: ['qaː.t̪ɪl', 'kaː.t̪ɪl'],
    syllables: 2,
    breakdown: ['qaː', 't̪ɪl'],
    nucleus: 'ɪ',
    coda: 'l',
    rhymeKey: 'ɪl',
    register: 'poetic',
    meaning: 'killer, murderer',
    variants: ['qatil', 'kaatil'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'ग़ाफ़िल',
    roman: ['gafil', 'ghaafil'],
    urdu: 'غافل',
    pronunciations: ['ɣaː.fɪl', 'ɡaː.fɪl'],
    syllables: 2,
    breakdown: ['ɣaː', 'fɪl'],
    nucleus: 'ɪ',
    coda: 'l',
    rhymeKey: 'ɪl',
    register: 'poetic',
    meaning: 'unmindful, careless',
    variants: ['gafil'],
    origin: 'Perso-Arabic'
  },

  // =========================================================================
  // 4. ACTIONS & VERBS (40 WORDS)
  // =========================================================================
  {
    devanagari: 'चलना',
    roman: ['chalna'],
    urdu: 'چلنا',
    pronunciations: ['t͡ʃəl.naː'],
    syllables: 2,
    breakdown: ['t͡ʃəl', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'əlnaː',
    register: 'common',
    meaning: 'to walk, to move',
    variants: ['chalna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'जलना',
    roman: ['jalna'],
    urdu: 'جلنا',
    pronunciations: ['d͡ʒəl.naː'],
    syllables: 2,
    breakdown: ['d͡ʒəl', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'əlnaː',
    register: 'common',
    meaning: 'to burn, to be jealous',
    variants: ['jalna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'गलना',
    roman: ['galna'],
    urdu: 'گلنا',
    pronunciations: ['ɡəl.naː'],
    syllables: 2,
    breakdown: ['ɡəl', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'əlnaː',
    register: 'common',
    meaning: 'to melt, dissolve',
    variants: ['galna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'ढलना',
    roman: ['dhalna'],
    urdu: 'ڈھلنا',
    pronunciations: ['ɖʱəl.naː'],
    syllables: 2,
    breakdown: ['ɖʱəl', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'əlnaː',
    register: 'poetic',
    meaning: 'to set (of sun), decline',
    variants: ['dhalna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'मचलना',
    roman: ['machalna'],
    urdu: 'مچلنا',
    pronunciations: ['mə.t͡ʃəl.naː'],
    syllables: 3,
    breakdown: ['mə', 't͡ʃəl', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'əlnaː',
    register: 'poetic',
    meaning: 'to be stubborn/restless',
    variants: ['machalna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'संभलना',
    roman: ['sambhalna'],
    urdu: 'سنبھلنا',
    pronunciations: ['səm.bʱəl.naː'],
    syllables: 3,
    breakdown: ['səm', 'bʱəl', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'əlnaː',
    register: 'common',
    meaning: 'to steady oneself',
    variants: ['sambhalna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'भागना',
    roman: ['bhagna'],
    urdu: 'بھاگنا',
    pronunciations: ['bʱaːɡ.naː'],
    syllables: 2,
    breakdown: ['bʱaːɡ', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːɡnaː',
    register: 'common',
    meaning: 'to run',
    variants: ['bhagna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'जागना',
    roman: ['jaagna', 'jagna'],
    urdu: 'جاگنا',
    pronunciations: ['d͡ʒaːɡ.naː'],
    syllables: 2,
    breakdown: ['d͡ʒaːɡ', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːɡnaː',
    register: 'common',
    meaning: 'to wake up',
    variants: ['jaagna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'माँगना',
    roman: ['maangna', 'mangna'],
    urdu: 'مانگنا',
    pronunciations: ['mãːŋɡ.naː'],
    syllables: 2,
    breakdown: ['mãːŋɡ', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'ãːŋɡnaː',
    register: 'common',
    meaning: 'to ask for, beg',
    variants: ['maangna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'त्यागना',
    roman: ['tyagna'],
    urdu: 'تیاگنا',
    pronunciations: ['t̪jaːɡ.naː'],
    syllables: 2,
    breakdown: ['t̪jaːɡ', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːɡnaː',
    register: 'literary',
    meaning: 'to renounce, forsake',
    variants: ['tyagna'],
    origin: 'Sanskrit'
  },
  {
    devanagari: 'लड़ना',
    roman: ['ladna'],
    urdu: 'لڑنا',
    pronunciations: ['ləɽ.naː'],
    syllables: 2,
    breakdown: ['ləɽ', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'əɽnaː',
    register: 'common',
    meaning: 'to fight',
    variants: ['ladna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'पड़ना',
    roman: ['padna'],
    urdu: 'پڑنا',
    pronunciations: ['pəɽ.naː'],
    syllables: 2,
    breakdown: ['pəɽ', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'əɽnaː',
    register: 'common',
    meaning: 'to fall, to occur',
    variants: ['padna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'सड़ना',
    roman: ['sadna'],
    urdu: 'سڑنا',
    pronunciations: ['səɽ.naː'],
    syllables: 2,
    breakdown: ['səɽ', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'əɽnaː',
    register: 'common',
    meaning: 'to rot',
    variants: ['sadna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'चढ़ना',
    roman: ['chadhna'],
    urdu: 'چڑھنا',
    pronunciations: ['t͡ʃəɽʱ.naː'],
    syllables: 2,
    breakdown: ['t͡ʃəɽʱ', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'əɽʱnaː',
    register: 'common',
    meaning: 'to climb, rise',
    variants: ['chadhna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'पढ़ना',
    roman: ['padhna'],
    urdu: 'پڑھنا',
    pronunciations: ['pəɽʱ.naː'],
    syllables: 2,
    breakdown: ['pəɽʱ', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'əɽʱnaː',
    register: 'common',
    meaning: 'to read, study',
    variants: ['padhna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'गढ़ना',
    roman: ['gadhna'],
    urdu: 'گڑھنا',
    pronunciations: ['ɡəɽʱ.naː'],
    syllables: 2,
    breakdown: ['ɡəɽʱ', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'əɽʱnaː',
    register: 'poetic',
    meaning: 'to forge, craft',
    variants: ['gadhna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'बढ़ना',
    roman: ['badhna'],
    urdu: 'بڑھنا',
    pronunciations: ['bəɽʱ.naː'],
    syllables: 2,
    breakdown: ['bəɽʱ', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'əɽʱnaː',
    register: 'common',
    meaning: 'to grow, advance',
    variants: ['badhna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'जीतना',
    roman: ['jeetna', 'jitna'],
    urdu: 'جیتنا',
    pronunciations: ['d͡ʒiːt̪.naː'],
    syllables: 2,
    breakdown: ['d͡ʒiːt̪', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'iːt̪naː',
    register: 'common',
    meaning: 'to win',
    variants: ['jeetna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'हारना',
    roman: ['haarna', 'harna'],
    urdu: 'ہارنا',
    pronunciations: ['ɦaːr.naː'],
    syllables: 2,
    breakdown: ['ɦaːr', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːrnaː',
    register: 'common',
    meaning: 'to lose',
    variants: ['haarna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'मारना',
    roman: ['maarna', 'marna'],
    urdu: 'مارنا',
    pronunciations: ['maːr.naː'],
    syllables: 2,
    breakdown: ['maːr', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːrnaː',
    register: 'common',
    meaning: 'to strike, kill',
    variants: ['maarna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'तारना',
    roman: ['taarna'],
    urdu: 'تارنا',
    pronunciations: ['t̪aːr.naː'],
    syllables: 2,
    breakdown: ['t̪aːr', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːrnaː',
    register: 'poetic',
    meaning: 'to liberate, redeem',
    variants: ['taarna'],
    origin: 'Sanskrit'
  },
  {
    devanagari: 'सुधारना',
    roman: ['sudharna'],
    urdu: 'سدھارنا',
    pronunciations: ['sʊ.d̪ʱaːr.naː'],
    syllables: 3,
    breakdown: ['sʊ', 'd̪ʱaːr', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːrnaː',
    register: 'common',
    meaning: 'to reform, mend',
    variants: ['sudharna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'बिगाड़ना',
    roman: ['bigadna'],
    urdu: 'بگاڑنا',
    pronunciations: ['bɪ.ɡaːɽ.naː'],
    syllables: 3,
    breakdown: ['bɪ', 'ɡaːɽ', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːɽnaː',
    register: 'common',
    meaning: 'to ruin, spoil',
    variants: ['bigadna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'लिखना',
    roman: ['likhna'],
    urdu: 'لکھنا',
    pronunciations: ['lɪkʰ.naː'],
    syllables: 2,
    breakdown: ['lɪkʰ', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'ɪkʰnaː',
    register: 'common',
    meaning: 'to write',
    variants: ['likhna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'दिखना',
    roman: ['dikhna'],
    urdu: 'دکھना',
    pronunciations: ['d̪ɪkʰ.naː'],
    syllables: 2,
    breakdown: ['d̪ɪkʰ', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'ɪkʰnaː',
    register: 'common',
    meaning: 'to be seen, appear',
    variants: ['dikhna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'सीखना',
    roman: ['seekhna', 'sikhna'],
    urdu: 'سیکھنا',
    pronunciations: ['siːkʰ.naː'],
    syllables: 2,
    breakdown: ['siːkʰ', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'iːkʰnaː',
    register: 'common',
    meaning: 'to learn',
    variants: ['seekhna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'चीखना',
    roman: ['cheekhna', 'chikhna'],
    urdu: 'چیخنا',
    pronunciations: ['t͡ʃiːkʰ.naː'],
    syllables: 2,
    breakdown: ['t͡ʃiːkʰ', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'iːkʰnaː',
    register: 'common',
    meaning: 'to scream',
    variants: ['cheekhna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'बोलना',
    roman: ['bolna'],
    urdu: 'بولنا',
    pronunciations: ['boːl.naː'],
    syllables: 2,
    breakdown: ['boːl', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'oːlnaː',
    register: 'common',
    meaning: 'to speak',
    variants: ['bolna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'तोलना',
    roman: ['tolna'],
    urdu: 'تولنا',
    pronunciations: ['t̪oːl.naː'],
    syllables: 2,
    breakdown: ['t̪oːl', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'oːlnaː',
    register: 'common',
    meaning: 'to weigh',
    variants: ['tolna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'खोलना',
    roman: ['kholna'],
    urdu: 'کھولنا',
    pronunciations: ['kʰoːl.naː'],
    syllables: 2,
    breakdown: ['kʰoːl', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'oːlnaː',
    register: 'common',
    meaning: 'to open, unfasten',
    variants: ['kholna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'डोलना',
    roman: ['dolna'],
    urdu: 'ڈولنا',
    pronunciations: ['ɖoːl.naː'],
    syllables: 2,
    breakdown: ['ɖoːl', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'oːlnaː',
    register: 'poetic',
    meaning: 'to sway, waver',
    variants: ['dolna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'सोचना',
    roman: ['sochna'],
    urdu: 'سوچنا',
    pronunciations: ['soːt͡ʃ.naː'],
    syllables: 2,
    breakdown: ['soːt͡ʃ', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'oːt͡ʃnaː',
    register: 'common',
    meaning: 'to think',
    variants: ['sochna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'नोचना',
    roman: ['nochna'],
    urdu: 'نوچنا',
    pronunciations: ['noːt͡ʃ.naː'],
    syllables: 2,
    breakdown: ['noːt͡ʃ', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'oːt͡ʃnaː',
    register: 'colloquial',
    meaning: 'to claw, scratch',
    variants: ['nochna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'खींचना',
    roman: ['kheenchna', 'khinchna'],
    urdu: 'کھینچنا',
    pronunciations: ['kʰĩːt͡ʃ.naː'],
    syllables: 2,
    breakdown: ['kʰĩːt͡ʃ', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'ĩːt͡ʃnaː',
    register: 'common',
    meaning: 'to pull, drag',
    variants: ['kheenchna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'सींचना',
    roman: ['seenchna'],
    urdu: 'سینچنا',
    pronunciations: ['sĩːt͡ʃ.naː'],
    syllables: 2,
    breakdown: ['sĩːt͡ʃ', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'ĩːt͡ʃnaː',
    register: 'poetic',
    meaning: 'to irrigate, nurture',
    variants: ['seenchna'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'गाना',
    roman: ['gaana', 'gana'],
    urdu: 'گانا',
    pronunciations: ['ɡaː.naː'],
    syllables: 2,
    breakdown: ['ɡaː', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːnaː',
    register: 'common',
    meaning: 'to sing, song',
    variants: ['gaana'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'लाना',
    roman: ['laana', 'lana'],
    urdu: 'لانا',
    pronunciations: ['laː.naː'],
    syllables: 2,
    breakdown: ['laː', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːnaː',
    register: 'common',
    meaning: 'to bring',
    variants: ['laana'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'पाना',
    roman: ['paana', 'pana'],
    urdu: 'پانا',
    pronunciations: ['paː.naː'],
    syllables: 2,
    breakdown: ['paː', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'aːnaː',
    register: 'common',
    meaning: 'to obtain, achieve',
    variants: ['paana'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'खोना',
    roman: ['khona'],
    urdu: 'کھونا',
    pronunciations: ['kʰoː.naː'],
    syllables: 2,
    breakdown: ['kʰoː', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'oːnaː',
    register: 'common',
    meaning: 'to lose',
    variants: ['khona'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'रोना',
    roman: ['rona'],
    urdu: 'رونا',
    pronunciations: ['roː.naː'],
    syllables: 2,
    breakdown: ['roː', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'oːnaː',
    register: 'common',
    meaning: 'to weep, cry',
    variants: ['rona'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'सोना',
    roman: ['sona'],
    urdu: 'سونا',
    pronunciations: ['soː.naː'],
    syllables: 2,
    breakdown: ['soː', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'oːnaː',
    register: 'common',
    meaning: 'to sleep, gold',
    variants: ['sona'],
    origin: 'Hindustani'
  },

  // =========================================================================
  // 5. STREET, SLANG & RAP CULTURE (40 WORDS)
  // =========================================================================
  {
    devanagari: 'भाई',
    roman: ['bhai'],
    urdu: 'بھائی',
    pronunciations: ['bʱaː.iː'],
    syllables: 2,
    breakdown: ['bʱaː', 'iː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'aːiː',
    register: 'slang',
    meaning: 'brother, bro, homie',
    variants: ['bhai'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'यार',
    roman: ['yaar', 'yar'],
    urdu: 'یار',
    pronunciations: ['jaːr'],
    syllables: 1,
    breakdown: ['jaːr'],
    nucleus: 'aː',
    coda: 'r',
    rhymeKey: 'aːr',
    register: 'colloquial',
    meaning: 'friend, pal',
    variants: ['yaar'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'सीन',
    roman: ['scene', 'seen'],
    urdu: 'سین',
    pronunciations: ['siːn'],
    syllables: 1,
    breakdown: ['siːn'],
    nucleus: 'iː',
    coda: 'n',
    rhymeKey: 'iːn',
    register: 'slang',
    meaning: 'scene, local hip-hop situation',
    variants: ['scene', 'seen'],
    origin: 'English'
  },
  {
    devanagari: 'वाइब',
    roman: ['vibe', 'waib'],
    urdu: 'وائب',
    pronunciations: ['ʋaːɪb', 'ʋaːjb'],
    syllables: 1,
    breakdown: ['ʋaːjb'],
    nucleus: 'aːɪ',
    coda: 'b',
    rhymeKey: 'aːjb',
    register: 'slang',
    meaning: 'vibe, energy, aura',
    variants: ['vibe'],
    origin: 'English'
  },
  {
    devanagari: 'फ्लो',
    roman: ['flow', 'flo'],
    urdu: 'فلو',
    pronunciations: ['floː', 'pʰloː'],
    syllables: 1,
    breakdown: ['floː'],
    nucleus: 'oː',
    coda: '',
    rhymeKey: 'oː',
    register: 'technical',
    meaning: 'rap cadence, flow',
    variants: ['flow'],
    origin: 'English'
  },
  {
    devanagari: 'बीट',
    roman: ['beat', 'beet'],
    urdu: 'بیٹ',
    pronunciations: ['biːʈ'],
    syllables: 1,
    breakdown: ['biːʈ'],
    nucleus: 'iː',
    coda: 'ʈ',
    rhymeKey: 'iːʈ',
    register: 'technical',
    meaning: 'instrumental track',
    variants: ['beat'],
    origin: 'English'
  },
  {
    devanagari: 'बार',
    roman: ['bar', 'baar'],
    urdu: 'بار',
    pronunciations: ['baːr'],
    syllables: 1,
    breakdown: ['baːr'],
    nucleus: 'aː',
    coda: 'r',
    rhymeKey: 'aːr',
    register: 'technical',
    meaning: 'rap bar, lyric measure, time',
    variants: ['bar', 'baar'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'राइम',
    roman: ['rhyme', 'raim'],
    urdu: 'رائم',
    pronunciations: ['raːɪm', 'raːjm'],
    syllables: 1,
    breakdown: ['raːjm'],
    nucleus: 'aːɪ',
    coda: 'm',
    rhymeKey: 'aːjm',
    register: 'technical',
    meaning: 'rhyme',
    variants: ['rhyme'],
    origin: 'English'
  },
  {
    devanagari: 'ड्रिप',
    roman: ['drip'],
    urdu: 'ڈرپ',
    pronunciations: ['ɖrɪp'],
    syllables: 1,
    breakdown: ['ɖrɪp'],
    nucleus: 'ɪ',
    coda: 'p',
    rhymeKey: 'ɪp',
    register: 'slang',
    meaning: 'fashion, swag',
    variants: ['drip'],
    origin: 'English'
  },
  {
    devanagari: 'स्टाइल',
    roman: ['style', 'stail'],
    urdu: 'سٹائل',
    pronunciations: ['sʈaːɪl', 'sʈaːjl'],
    syllables: 1,
    breakdown: ['sʈaːjl'],
    nucleus: 'aːɪ',
    coda: 'l',
    rhymeKey: 'aːjl',
    register: 'slang',
    meaning: 'style, flair',
    variants: ['style'],
    origin: 'English'
  },
  {
    devanagari: 'बंटा',
    roman: ['banta'],
    urdu: 'بنٹا',
    pronunciations: ['bəɳ.ʈaː'],
    syllables: 2,
    breakdown: ['bəɳ', 'ʈaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'ʈaː',
    register: 'slang',
    meaning: 'kid, boy, slang term',
    variants: ['banta'],
    origin: 'Slang'
  },
  {
    devanagari: 'बंटाई',
    roman: ['bantai'],
    urdu: 'بنٹائی',
    pronunciations: ['bəɳ.ʈaː.iː'],
    syllables: 3,
    breakdown: ['bəɳ', 'ʈaː', 'iː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'aːiː',
    register: 'slang',
    meaning: 'Mumbai street term for homie',
    variants: ['bantai'],
    origin: 'Slang'
  },
  {
    devanagari: 'हक से',
    roman: ['haq se', 'hak se'],
    urdu: 'حق سے',
    pronunciations: ['ɦəq.seː'],
    syllables: 2,
    breakdown: ['ɦəq', 'seː'],
    nucleus: 'eː',
    coda: '',
    rhymeKey: 'seː',
    register: 'slang',
    meaning: 'with full right and authority',
    variants: ['haq se'],
    origin: 'Slang'
  },
  {
    devanagari: 'चालू',
    roman: ['chalu'],
    urdu: 'چالو',
    pronunciations: ['t͡ʃaː.luː'],
    syllables: 2,
    breakdown: ['t͡ʃaː', 'luː'],
    nucleus: 'uː',
    coda: '',
    rhymeKey: 'luː',
    register: 'slang',
    meaning: 'cunning, active, crafty',
    variants: ['chalu'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'फालतू',
    roman: ['faaltu', 'faltu'],
    urdu: 'فالتو',
    pronunciations: ['faːl.t̪uː', 'pʰaːl.t̪uː'],
    syllables: 2,
    breakdown: ['faːl', 't̪uː'],
    nucleus: 'uː',
    coda: '',
    rhymeKey: 't̪uː',
    register: 'slang',
    meaning: 'useless, extra, trivial',
    variants: ['faaltu'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'खल्लास',
    roman: ['khallas', 'khalas'],
    urdu: 'خلاص',
    pronunciations: ['xəl.laːs', 'kʰəl.laːs'],
    syllables: 2,
    breakdown: ['xəl', 'laːs'],
    nucleus: 'aː',
    coda: 's',
    rhymeKey: 'aːs',
    register: 'slang',
    meaning: 'finished, done for',
    variants: ['khallas'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'भौकाल',
    roman: ['bhaukaal', 'bhokal'],
    urdu: 'بھوکال',
    pronunciations: ['bʱɔː.kaːl'],
    syllables: 2,
    breakdown: ['bʱɔː', 'kaːl'],
    nucleus: 'aː',
    coda: 'l',
    rhymeKey: 'aːl',
    register: 'slang',
    meaning: 'swag, fear, grandeur',
    variants: ['bhaukaal'],
    origin: 'Slang'
  },
  {
    devanagari: 'जुगाड़',
    roman: ['jugaad', 'jugad'],
    urdu: 'جگاڑ',
    pronunciations: ['d͡ʒʊ.ɡaːɽ'],
    syllables: 2,
    breakdown: ['d͡ʒʊ', 'ɡaːɽ'],
    nucleus: 'aː',
    coda: 'ɽ',
    rhymeKey: 'aːɽ',
    register: 'slang',
    meaning: 'hack, workaround, resourceful fix',
    variants: ['jugaad'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'लोचा',
    roman: ['locha'],
    urdu: 'لوچا',
    pronunciations: ['loː.t͡ʃaː'],
    syllables: 2,
    breakdown: ['loː', 't͡ʃaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 't͡ʃaː',
    register: 'slang',
    meaning: 'mess, trouble, complication',
    variants: ['locha'],
    origin: 'Slang'
  },
  {
    devanagari: 'टोपी',
    roman: ['topi'],
    urdu: 'ٹوپی',
    pronunciations: ['ʈoː.piː'],
    syllables: 2,
    breakdown: ['ʈoː', 'piː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'piː',
    register: 'slang',
    meaning: 'cap, deceit (topi pehnana)',
    variants: ['topi'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'चमचा',
    roman: ['chamcha'],
    urdu: 'چمچہ',
    pronunciations: ['t͡ʃəm.t͡ʃaː'],
    syllables: 2,
    breakdown: ['t͡ʃəm', 't͡ʃaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 't͡ʃaː',
    register: 'slang',
    meaning: 'sycophant, yes-man',
    variants: ['chamcha'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'पेटी',
    roman: ['peti'],
    urdu: 'پیٹی',
    pronunciations: ['peː.ʈiː'],
    syllables: 2,
    breakdown: ['peː', 'ʈiː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'ʈiː',
    register: 'slang',
    meaning: 'box, one lakh rupees (slang)',
    variants: ['peti'],
    origin: 'Slang'
  },
  {
    devanagari: 'खोखा',
    roman: ['khokha'],
    urdu: 'کھوکھا',
    pronunciations: ['kʰoː.kʰaː'],
    syllables: 2,
    breakdown: ['kʰoː', 'kʰaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'kʰaː',
    register: 'slang',
    meaning: 'kiosk, one crore rupees (slang)',
    variants: ['khokha'],
    origin: 'Slang'
  },
  {
    devanagari: 'काण्ड',
    roman: ['kaand', 'kand'],
    urdu: 'کانڈ',
    pronunciations: ['kaːɳɖ'],
    syllables: 1,
    breakdown: ['kaːɳɖ'],
    nucleus: 'aː',
    coda: 'ɳɖ',
    rhymeKey: 'aːɳɖ',
    register: 'slang',
    meaning: 'scandal, misdeed',
    variants: ['kaand'],
    origin: 'Sanskrit'
  },
  {
    devanagari: 'झोल',
    roman: ['jhol'],
    urdu: 'جھول',
    pronunciations: ['d͡ʒʱoːl'],
    syllables: 1,
    breakdown: ['d͡ʒʱoːl'],
    nucleus: 'oː',
    coda: 'l',
    rhymeKey: 'oːl',
    register: 'slang',
    meaning: 'fraud, fishy scheme',
    variants: ['jhol'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'हवाबाज़ी',
    roman: ['hawabaazi', 'hawabazi'],
    urdu: 'ہوابازی',
    pronunciations: ['ɦə.ʋaː.baː.ziː'],
    syllables: 4,
    breakdown: ['ɦə', 'ʋaː', 'baː', 'ziː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'ziː',
    register: 'slang',
    meaning: 'bluffing, flexing, boastful display',
    variants: ['hawabaazi'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'दबाव',
    roman: ['dabav', 'dabaav'],
    urdu: 'دباؤ',
    pronunciations: ['d̪ə.baːʋ'],
    syllables: 2,
    breakdown: ['d̪ə', 'baːʋ'],
    nucleus: 'aː',
    coda: 'ʋ',
    rhymeKey: 'aːʋ',
    register: 'common',
    meaning: 'pressure',
    variants: ['dabav'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'बवाल',
    roman: ['bawaal', 'bawal'],
    urdu: 'بوال',
    pronunciations: ['bə.ʋaːl'],
    syllables: 2,
    breakdown: ['bə', 'ʋaːl'],
    nucleus: 'aː',
    coda: 'l',
    rhymeKey: 'aːl',
    register: 'slang',
    meaning: 'chaos, insane commotion, fire',
    variants: ['bawaal'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'धमाल',
    roman: ['dhamaal', 'dhamal'],
    urdu: 'دھمال',
    pronunciations: ['d̪ʱə.maːl'],
    syllables: 2,
    breakdown: ['d̪ʱə', 'maːl'],
    nucleus: 'aː',
    coda: 'l',
    rhymeKey: 'aːl',
    register: 'slang',
    meaning: 'blast, high-energy party',
    variants: ['dhamaal'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'कमाल',
    roman: ['kamaal', 'kamal'],
    urdu: 'کمال',
    pronunciations: ['kə.maːl'],
    syllables: 2,
    breakdown: ['kə', 'maːl'],
    nucleus: 'aː',
    coda: 'l',
    rhymeKey: 'aːl',
    register: 'common',
    meaning: 'wonder, miracle, excellence',
    variants: ['kamaal'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'धूम',
    roman: ['dhoom', 'dhum'],
    urdu: 'دھوم',
    pronunciations: ['d̪ʱuːm'],
    syllables: 1,
    breakdown: ['d̪ʱuːm'],
    nucleus: 'uː',
    coda: 'm',
    rhymeKey: 'uːm',
    register: 'slang',
    meaning: 'hype, fanfare',
    variants: ['dhoom'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'झूम',
    roman: ['jhoom', 'jhum'],
    urdu: 'جھوم',
    pronunciations: ['d͡ʒʱuːm'],
    syllables: 1,
    breakdown: ['d͡ʒʱuːm'],
    nucleus: 'uː',
    coda: 'm',
    rhymeKey: 'uːm',
    register: 'poetic',
    meaning: 'sway in ecstasy',
    variants: ['jhoom'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'घूम',
    roman: ['ghoom', 'ghum'],
    urdu: 'گھوم',
    pronunciations: ['ɡʱuːm'],
    syllables: 1,
    breakdown: ['ɡʱuːm'],
    nucleus: 'uː',
    coda: 'm',
    rhymeKey: 'uːm',
    register: 'common',
    meaning: 'roam, wander',
    variants: ['ghoom'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'चूम',
    roman: ['choom', 'chum'],
    urdu: 'چوم',
    pronunciations: ['t͡ʃuːm'],
    syllables: 1,
    breakdown: ['t͡ʃuːm'],
    nucleus: 'uː',
    coda: 'm',
    rhymeKey: 'uːm',
    register: 'poetic',
    meaning: 'kiss',
    variants: ['choom'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'शान',
    roman: ['shaan', 'shan'],
    urdu: 'شان',
    pronunciations: ['ʃaːn'],
    syllables: 1,
    breakdown: ['ʃaːn'],
    nucleus: 'aː',
    coda: 'n',
    rhymeKey: 'aːn',
    register: 'common',
    meaning: 'pride, magnificence',
    variants: ['shaan'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'आन',
    roman: ['aan'],
    urdu: 'آن',
    pronunciations: ['aːn'],
    syllables: 1,
    breakdown: ['aːn'],
    nucleus: 'aː',
    coda: 'n',
    rhymeKey: 'aːn',
    register: 'poetic',
    meaning: 'dignity, honor',
    variants: ['aan'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'बान',
    roman: ['baan', 'ban'],
    urdu: 'بان',
    pronunciations: ['baːn'],
    syllables: 1,
    breakdown: ['baːn'],
    nucleus: 'aː',
    coda: 'n',
    rhymeKey: 'aːn',
    register: 'poetic',
    meaning: 'habit, nature, style',
    variants: ['baan'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'जान',
    roman: ['jaan', 'jan'],
    urdu: 'جان',
    pronunciations: ['d͡ʒaːn'],
    syllables: 1,
    breakdown: ['d͡ʒaːn'],
    nucleus: 'aː',
    coda: 'n',
    rhymeKey: 'aːn',
    register: 'common',
    meaning: 'life, soul, darling',
    variants: ['jaan'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'तान',
    roman: ['taan', 'tan'],
    urdu: 'تان',
    pronunciations: ['t̪aːn'],
    syllables: 1,
    breakdown: ['t̪aːn'],
    nucleus: 'aː',
    coda: 'n',
    rhymeKey: 'aːn',
    register: 'poetic',
    meaning: 'musical note, tension',
    variants: ['taan'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'मान',
    roman: ['maan', 'man'],
    urdu: 'مان',
    pronunciations: ['maːn'],
    syllables: 1,
    breakdown: ['maːn'],
    nucleus: 'aː',
    coda: 'n',
    rhymeKey: 'aːn',
    register: 'common',
    meaning: 'respect, honor, accept',
    variants: ['maan'],
    origin: 'Hindustani'
  },

  // =========================================================================
  // 6. PERSO-ARABIC & URDU LITERARY WITH NUQTA (45 WORDS)
  // =========================================================================
  {
    devanagari: 'फ़ुरसत',
    roman: ['fursat', 'phursat'],
    urdu: 'فرصت',
    pronunciations: ['fʊr.sət̪', 'pʰʊr.sət̪'],
    syllables: 2,
    breakdown: ['fʊr', 'sət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'poetic',
    meaning: 'leisure, respite',
    variants: ['fursat', 'phursat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'क़ुदरत',
    roman: ['qudrat', 'kudrat'],
    urdu: 'قدرت',
    pronunciations: ['qʊd̪.rət̪', 'kʊd̪.rət̪'],
    syllables: 2,
    breakdown: ['qʊd̪', 'rət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'poetic',
    meaning: 'nature, divine power',
    variants: ['qudrat', 'kudrat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'कसरत',
    roman: ['kasrat'],
    urdu: 'کثرت',
    pronunciations: ['kəs.rət̪'],
    syllables: 2,
    breakdown: ['kəs', 'rət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'common',
    meaning: 'exercise, abundance',
    variants: ['kasrat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'हरकत',
    roman: ['harkat'],
    urdu: 'حرکت',
    pronunciations: ['ɦər.kət̪'],
    syllables: 2,
    breakdown: ['ɦər', 'kət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'common',
    meaning: 'motion, antic, action',
    variants: ['harkat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'शोहरत',
    roman: ['shohrat'],
    urdu: 'شہرَت',
    pronunciations: ['ʃoːɦ.rət̪'],
    syllables: 2,
    breakdown: ['ʃoːɦ', 'rət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'poetic',
    meaning: 'fame, renown',
    variants: ['shohrat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'ग़ैरत',
    roman: ['ghairat', 'gairat'],
    urdu: 'غیرت',
    pronunciations: ['ɣɛː.rət̪', 'ɡɛː.rət̪'],
    syllables: 2,
    breakdown: ['ɣɛː', 'rət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'poetic',
    meaning: 'honor, self-respect, shame',
    variants: ['ghairat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'हिम्मत',
    roman: ['himmat'],
    urdu: 'ہمت',
    pronunciations: ['ɦɪm.mət̪'],
    syllables: 2,
    breakdown: ['ɦɪm', 'mət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'common',
    meaning: 'courage, audacity',
    variants: ['himmat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'जन्नत',
    roman: ['jannat'],
    urdu: 'جنت',
    pronunciations: ['d͡ʒən.nət̪'],
    syllables: 2,
    breakdown: ['d͡ʒən', 'nət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'poetic',
    meaning: 'paradise, heaven',
    variants: ['jannat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'दौलत',
    roman: ['daulat'],
    urdu: 'دولت',
    pronunciations: ['d̪ɔː.lət̪'],
    syllables: 2,
    breakdown: ['d̪ɔː', 'lət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'common',
    meaning: 'wealth, riches',
    variants: ['daulat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'आदत',
    roman: ['aadat'],
    urdu: 'عادت',
    pronunciations: ['aː.d̪ət̪'],
    syllables: 2,
    breakdown: ['aː', 'd̪ət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'common',
    meaning: 'habit',
    variants: ['aadat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'इबादत',
    roman: ['ibadat'],
    urdu: 'عبادت',
    pronunciations: ['ɪ.baː.d̪ət̪'],
    syllables: 3,
    breakdown: ['ɪ', 'baː', 'd̪ət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'poetic',
    meaning: 'worship, prayer',
    variants: ['ibadat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'इनायत',
    roman: ['inayat'],
    urdu: 'عنایت',
    pronunciations: ['ɪ.naː.jət̪'],
    syllables: 3,
    breakdown: ['ɪ', 'naː', 'jət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'poetic',
    meaning: 'favor, kindness, grace',
    variants: ['inayat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'शिकायत',
    roman: ['shikayat'],
    urdu: 'شکایت',
    pronunciations: ['ʃɪ.kaː.jət̪'],
    syllables: 3,
    breakdown: ['ʃɪ', 'kaː', 'jət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'common',
    meaning: 'complaint',
    variants: ['shikayat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'हिदायत',
    roman: ['hidayat'],
    urdu: 'ہدایت',
    pronunciations: ['ɦɪ.d̪aː.jət̪'],
    syllables: 3,
    breakdown: ['ɦɪ', 'd̪aː', 'jət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'common',
    meaning: 'guidance, instruction',
    variants: ['hidayat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'अमानत',
    roman: ['amanat'],
    urdu: 'امانت',
    pronunciations: ['ə.maː.nət̪'],
    syllables: 3,
    breakdown: ['ə', 'maː', 'nət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'poetic',
    meaning: 'trust, safe deposit',
    variants: ['amanat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'ज़मानत',
    roman: ['zamanat'],
    urdu: 'ضمانت',
    pronunciations: ['zə.maː.nət̪'],
    syllables: 3,
    breakdown: ['zə', 'maː', 'nət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'common',
    meaning: 'bail, guarantee',
    variants: ['zamanat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'सियासत',
    roman: ['siyasat'],
    urdu: 'سیاست',
    pronunciations: ['sɪ.jaː.sət̪'],
    syllables: 3,
    breakdown: ['sɪ', 'jaː', 'sət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'common',
    meaning: 'politics',
    variants: ['siyasat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'रियासत',
    roman: ['riyasat'],
    urdu: 'ریاست',
    pronunciations: ['rɪ.jaː.sət̪'],
    syllables: 3,
    breakdown: ['rɪ', 'jaː', 'sət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'common',
    meaning: 'state, principality',
    variants: ['riyasat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'क़यामत',
    roman: ['qayamat', 'kayamat'],
    urdu: 'قیامت',
    pronunciations: ['qə.jaː.mət̪', 'kə.jaː.mət̪'],
    syllables: 3,
    breakdown: ['qə', 'jaː', 'mət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'poetic',
    meaning: 'resurrection, doomsday, havoc',
    variants: ['qayamat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'सलामत',
    roman: ['salamat'],
    urdu: 'سلامت',
    pronunciations: ['sə.laː.mət̪'],
    syllables: 3,
    breakdown: ['sə', 'laː', 'mət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'poetic',
    meaning: 'safe, intact',
    variants: ['salamat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'मलाल',
    roman: ['malal'],
    urdu: 'ملال',
    pronunciations: ['mə.laːl'],
    syllables: 2,
    breakdown: ['mə', 'laːl'],
    nucleus: 'aː',
    coda: 'l',
    rhymeKey: 'aːl',
    register: 'poetic',
    meaning: 'sorrow, remorse',
    variants: ['malal'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'हलाल',
    roman: ['halal'],
    urdu: 'حلال',
    pronunciations: ['ɦə.laːl'],
    syllables: 2,
    breakdown: ['ɦə', 'laːl'],
    nucleus: 'aː',
    coda: 'l',
    rhymeKey: 'aːl',
    register: 'common',
    meaning: 'lawful, permissible, honest',
    variants: ['halal'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'जलाल',
    roman: ['jalal'],
    urdu: 'جلال',
    pronunciations: ['d͡ʒə.laːl'],
    syllables: 2,
    breakdown: ['d͡ʒə', 'laːl'],
    nucleus: 'aː',
    coda: 'l',
    rhymeKey: 'aːl',
    register: 'poetic',
    meaning: 'glory, majesty, wrath',
    variants: ['jalal'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'ख़याल',
    roman: ['khayal', 'khayaal'],
    urdu: 'خیال',
    pronunciations: ['xə.jaːl', 'kʰə.jaːl'],
    syllables: 2,
    breakdown: ['xə', 'jaːl'],
    nucleus: 'aː',
    coda: 'l',
    rhymeKey: 'aːl',
    register: 'common',
    meaning: 'thought, care, idea',
    variants: ['khayal'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'मिसाल',
    roman: ['misaal', 'misal'],
    urdu: 'مثال',
    pronunciations: ['mɪ.saːl'],
    syllables: 2,
    breakdown: ['mɪ', 'saːl'],
    nucleus: 'aː',
    coda: 'l',
    rhymeKey: 'aːl',
    register: 'common',
    meaning: 'example, precedent',
    variants: ['misaal'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'विसाल',
    roman: ['visaal', 'visal'],
    urdu: 'وصال',
    pronunciations: ['ʋɪ.saːl'],
    syllables: 2,
    breakdown: ['ʋɪ', 'saːl'],
    nucleus: 'aː',
    coda: 'l',
    rhymeKey: 'aːl',
    register: 'poetic',
    meaning: 'union with beloved',
    variants: ['visaal'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'ज़वाल',
    roman: ['zawal'],
    urdu: 'زوال',
    pronunciations: ['zə.ʋaːl'],
    syllables: 2,
    breakdown: ['zə', 'ʋaːl'],
    nucleus: 'aː',
    coda: 'l',
    rhymeKey: 'aːl',
    register: 'poetic',
    meaning: 'downfall, decline',
    variants: ['zawal'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'फ़लक',
    roman: ['falak'],
    urdu: 'فلک',
    pronunciations: ['fə.lək', 'pʰə.lək'],
    syllables: 2,
    breakdown: ['fə', 'lək'],
    nucleus: 'ə',
    coda: 'k',
    rhymeKey: 'ək',
    register: 'poetic',
    meaning: 'sky, firmament, cosmos',
    variants: ['falak'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'झलक',
    roman: ['jhalak'],
    urdu: 'جھلک',
    pronunciations: ['d͡ʒʱə.lək'],
    syllables: 2,
    breakdown: ['d͡ʒʱə', 'lək'],
    nucleus: 'ə',
    coda: 'k',
    rhymeKey: 'ək',
    register: 'common',
    meaning: 'glimpse',
    variants: ['jhalak'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'पलक',
    roman: ['palak'],
    urdu: 'پلک',
    pronunciations: ['pə.lək'],
    syllables: 2,
    breakdown: ['pə', 'lək'],
    nucleus: 'ə',
    coda: 'k',
    rhymeKey: 'ək',
    register: 'poetic',
    meaning: 'eyelid, eyelash, instant',
    variants: ['palak'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'चमक',
    roman: ['chamak'],
    urdu: 'چمک',
    pronunciations: ['t͡ʃə.mək'],
    syllables: 2,
    breakdown: ['t͡ʃə', 'mək'],
    nucleus: 'ə',
    coda: 'k',
    rhymeKey: 'ək',
    register: 'common',
    meaning: 'shine, glitter',
    variants: ['chamak'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'दमक',
    roman: ['damak'],
    urdu: 'دمک',
    pronunciations: ['d̪ə.mək'],
    syllables: 2,
    breakdown: ['d̪ə', 'mək'],
    nucleus: 'ə',
    coda: 'k',
    rhymeKey: 'ək',
    register: 'poetic',
    meaning: 'glow, radiancy',
    variants: ['damak'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'महक',
    roman: ['mahak'],
    urdu: 'مہک',
    pronunciations: ['mə.ɦək'],
    syllables: 2,
    breakdown: ['mə', 'ɦək'],
    nucleus: 'ə',
    coda: 'k',
    rhymeKey: 'ək',
    register: 'poetic',
    meaning: 'fragrance',
    variants: ['mahak'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'बहक',
    roman: ['bahak'],
    urdu: 'بہک',
    pronunciations: ['bə.ɦək'],
    syllables: 2,
    breakdown: ['bə', 'ɦək'],
    nucleus: 'ə',
    coda: 'k',
    rhymeKey: 'ək',
    register: 'poetic',
    meaning: 'intoxication, straying',
    variants: ['bahak'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'चहक',
    roman: ['chahak'],
    urdu: 'چہک',
    pronunciations: ['t͡ʃə.ɦək'],
    syllables: 2,
    breakdown: ['t͡ʃə', 'ɦək'],
    nucleus: 'ə',
    coda: 'k',
    rhymeKey: 'ək',
    register: 'poetic',
    meaning: 'chirping, cheerful voice',
    variants: ['chahak'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'तहज़ीब',
    roman: ['tahzeeb', 'tehzeeb'],
    urdu: 'تہذیب',
    pronunciations: ['t̪ɛːɦ.ziːb', 't̪əɦ.ziːb'],
    syllables: 2,
    breakdown: ['t̪ɛːɦ', 'ziːb'],
    nucleus: 'iː',
    coda: 'b',
    rhymeKey: 'iːb',
    register: 'literary',
    meaning: 'culture, refinement, manners',
    variants: ['tahzeeb'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'तरकीब',
    roman: ['tarkeeb', 'tarkib'],
    urdu: 'ترکیب',
    pronunciations: ['t̪ər.kiːb'],
    syllables: 2,
    breakdown: ['t̪ər', 'kiːb'],
    nucleus: 'iː',
    coda: 'b',
    rhymeKey: 'iːb',
    register: 'common',
    meaning: 'technique, scheme, method',
    variants: ['tarkeeb'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'तक़रीब',
    roman: ['taqreeb', 'takrib'],
    urdu: 'تقریب',
    pronunciations: ['t̪əq.riːb', 't̪ək.riːb'],
    syllables: 2,
    breakdown: ['t̪əq', 'riːb'],
    nucleus: 'iː',
    coda: 'b',
    rhymeKey: 'iːb',
    register: 'literary',
    meaning: 'ceremony, occasion',
    variants: ['taqreeb'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'तरतीब',
    roman: ['tarteeb', 'tartib'],
    urdu: 'ترتیب',
    pronunciations: ['t̪ər.t̪iːb'],
    syllables: 2,
    breakdown: ['t̪ər', 't̪iːb'],
    nucleus: 'iː',
    coda: 'b',
    rhymeKey: 'iːb',
    register: 'literary',
    meaning: 'order, sequence, arrangement',
    variants: ['tarteeb'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'क़ाफ़िया',
    roman: ['qafiya', 'kafiya'],
    urdu: 'قافیہ',
    pronunciations: ['qaː.fɪ.jaː', 'kaː.fɪ.jaː'],
    syllables: 3,
    breakdown: ['qaː', 'fɪ', 'jaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'ɪjaː',
    register: 'technical',
    meaning: 'rhyme word in ghazal',
    variants: ['qafiya'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'रदीफ़',
    roman: ['radeef', 'radif'],
    urdu: 'ردیف',
    pronunciations: ['rə.d̪iːf'],
    syllables: 2,
    breakdown: ['rə', 'd̪iːf'],
    nucleus: 'iː',
    coda: 'f',
    rhymeKey: 'iːf',
    register: 'technical',
    meaning: 'refrain in ghazal',
    variants: ['radeef'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'मतला',
    roman: ['matla'],
    urdu: 'مطلع',
    pronunciations: ['mət̪.laː'],
    syllables: 2,
    breakdown: ['mət̪', 'laː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'laː',
    register: 'technical',
    meaning: 'opening couplet of ghazal',
    variants: ['matla'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'मक़्ता',
    roman: ['maqta', 'makta'],
    urdu: 'مقطع',
    pronunciations: ['məq.t̪aː', 'mək.t̪aː'],
    syllables: 2,
    breakdown: ['məq', 't̪aː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 't̪aː',
    register: 'technical',
    meaning: 'closing couplet containing pen name',
    variants: ['maqta'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'बहर',
    roman: ['bahr', 'beher'],
    urdu: 'بحر',
    pronunciations: ['bəɦr', 'bɛː.ɦər'],
    syllables: 2,
    breakdown: ['bɛː', 'ɦər'],
    nucleus: 'ə',
    coda: 'r',
    rhymeKey: 'ər',
    register: 'technical',
    meaning: 'poetic meter, sea',
    variants: ['bahr', 'beher'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'वज़्न',
    roman: ['wazn', 'vajan'],
    urdu: 'وزن',
    pronunciations: ['ʋəzn', 'ʋə.zən'],
    syllables: 2,
    breakdown: ['ʋə', 'zən'],
    nucleus: 'ə',
    coda: 'n',
    rhymeKey: 'ən',
    register: 'technical',
    meaning: 'poetic weight, meter balance',
    variants: ['wazn'],
    origin: 'Perso-Arabic'
  },

  // =========================================================================
  // 7. NATURE & ELEMENTS (35 WORDS)
  // =========================================================================
  {
    devanagari: 'आग',
    roman: ['aag'],
    urdu: 'آگ',
    pronunciations: ['aːɡ'],
    syllables: 1,
    breakdown: ['aːɡ'],
    nucleus: 'aː',
    coda: 'ɡ',
    rhymeKey: 'aːɡ',
    register: 'common',
    meaning: 'fire',
    variants: ['aag'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'दाग',
    roman: ['daag', 'dag'],
    urdu: 'داغ',
    pronunciations: ['d̪aːɡ', 'd̪aːɣ'],
    syllables: 1,
    breakdown: ['d̪aːɡ'],
    nucleus: 'aː',
    coda: 'ɡ',
    rhymeKey: 'aːɡ',
    register: 'common',
    meaning: 'stain, scar',
    variants: ['daag'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'भाग',
    roman: ['bhaag', 'bhag'],
    urdu: 'بھاگ',
    pronunciations: ['bʱaːɡ'],
    syllables: 1,
    breakdown: ['bʱaːɡ'],
    nucleus: 'aː',
    coda: 'ɡ',
    rhymeKey: 'aːɡ',
    register: 'common',
    meaning: 'portion, run, destiny',
    variants: ['bhaag'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'राग',
    roman: ['raag', 'rag'],
    urdu: 'راگ',
    pronunciations: ['raːɡ'],
    syllables: 1,
    breakdown: ['raːɡ'],
    nucleus: 'aː',
    coda: 'ɡ',
    rhymeKey: 'aːɡ',
    register: 'poetic',
    meaning: 'melody, raga',
    variants: ['raag'],
    origin: 'Sanskrit'
  },
  {
    devanagari: 'झाग',
    roman: ['jhaag', 'jhag'],
    urdu: 'جھاگ',
    pronunciations: ['d͡ʒʱaːɡ'],
    syllables: 1,
    breakdown: ['d͡ʒʱaːɡ'],
    nucleus: 'aː',
    coda: 'ɡ',
    rhymeKey: 'aːɡ',
    register: 'common',
    meaning: 'foam, froth',
    variants: ['jhaag'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'पानी',
    roman: ['paani', 'pani'],
    urdu: 'پانی',
    pronunciations: ['paː.niː'],
    syllables: 2,
    breakdown: ['paː', 'niː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'niː',
    register: 'common',
    meaning: 'water',
    variants: ['paani'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'जवानी',
    roman: ['jawani'],
    urdu: 'جوانی',
    pronunciations: ['d͡ʒə.ʋaː.niː'],
    syllables: 3,
    breakdown: ['d͡ʒə', 'ʋaː', 'niː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'aːniː',
    register: 'poetic',
    meaning: 'youth',
    variants: ['jawani'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'कहानी',
    roman: ['kahani'],
    urdu: 'کہانی',
    pronunciations: ['kə.ɦaː.niː'],
    syllables: 3,
    breakdown: ['kə', 'ɦaː', 'niː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'aːniː',
    register: 'common',
    meaning: 'story, tale',
    variants: ['kahani'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'रवानी',
    roman: ['rawani'],
    urdu: 'روانی',
    pronunciations: ['rə.ʋaː.niː'],
    syllables: 3,
    breakdown: ['rə', 'ʋaː', 'niː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'aːniː',
    register: 'poetic',
    meaning: 'fluency, flow',
    variants: ['rawani'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'निशानी',
    roman: ['nishani'],
    urdu: 'نشانی',
    pronunciations: ['nɪ.ʃaː.niː'],
    syllables: 3,
    breakdown: ['nɪ', 'ʃaː', 'niː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'aːniː',
    register: 'common',
    meaning: 'souvenir, memento',
    variants: ['nishani'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'रूहानी',
    roman: ['roohani', 'ruhani'],
    urdu: 'روحانی',
    pronunciations: ['ruː.ɦaː.niː'],
    syllables: 3,
    breakdown: ['ruː', 'ɦaː', 'niː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'aːniː',
    register: 'poetic',
    meaning: 'spiritual, ethereal',
    variants: ['roohani'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'ज़ुबानी',
    roman: ['zubani'],
    urdu: 'زبانی',
    pronunciations: ['zʊ.baː.niː'],
    syllables: 3,
    breakdown: ['zʊ', 'baː', 'niː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'aːniː',
    register: 'common',
    meaning: 'verbal, oral, by tongue',
    variants: ['zubani'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'तूफ़ान',
    roman: ['toofan', 'tufan'],
    urdu: 'طوفان',
    pronunciations: ['t̪uː.faːn', 't̪uː.pʰaːn'],
    syllables: 2,
    breakdown: ['t̪uː', 'faːn'],
    nucleus: 'aː',
    coda: 'n',
    rhymeKey: 'aːn',
    register: 'common',
    meaning: 'storm, cyclone',
    variants: ['toofan'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'अरमान',
    roman: ['arman', 'armaan'],
    urdu: 'ارمان',
    pronunciations: ['ər.maːn'],
    syllables: 2,
    breakdown: ['ər', 'maːn'],
    nucleus: 'aː',
    coda: 'n',
    rhymeKey: 'aːn',
    register: 'poetic',
    meaning: 'yearning, desire',
    variants: ['arman'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'इंसान',
    roman: ['insan', 'insaan'],
    urdu: 'انسان',
    pronunciations: ['ɪn.saːn'],
    syllables: 2,
    breakdown: ['ɪn', 'saːn'],
    nucleus: 'aː',
    coda: 'n',
    rhymeKey: 'aːn',
    register: 'common',
    meaning: 'human being',
    variants: ['insan'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'हैवान',
    roman: ['haiwan'],
    urdu: 'حیوان',
    pronunciations: ['ɦɛː.ʋaːn'],
    syllables: 2,
    breakdown: ['ɦɛː', 'ʋaːn'],
    nucleus: 'aː',
    coda: 'n',
    rhymeKey: 'aːn',
    register: 'poetic',
    meaning: 'beast, monster',
    variants: ['haiwan'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'शैतान',
    roman: ['shaitan'],
    urdu: 'شیطان',
    pronunciations: ['ʃɛː.t̪aːn'],
    syllables: 2,
    breakdown: ['ʃɛː', 't̪aːn'],
    nucleus: 'aː',
    coda: 'n',
    rhymeKey: 'aːn',
    register: 'common',
    meaning: 'devil, satan',
    variants: ['shaitan'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'नादान',
    roman: ['nadan', 'nadaan'],
    urdu: 'نادان',
    pronunciations: ['naː.d̪aːn'],
    syllables: 2,
    breakdown: ['naː', 'd̪aːn'],
    nucleus: 'aː',
    coda: 'n',
    rhymeKey: 'aːn',
    register: 'poetic',
    meaning: 'naive, innocent',
    variants: ['nadan'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'पहचान',
    roman: ['pehchan'],
    urdu: 'پہچان',
    pronunciations: ['pɛːɦ.t͡ʃaːn', 'pəɦ.t͡ʃaːn'],
    syllables: 2,
    breakdown: ['pɛːɦ', 't͡ʃaːn'],
    nucleus: 'aː',
    coda: 'n',
    rhymeKey: 'aːn',
    register: 'common',
    meaning: 'identity, recognition',
    variants: ['pehchan'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'अनजान',
    roman: ['anjaan', 'anjan'],
    urdu: 'انجان',
    pronunciations: ['ən.d͡ʒaːn'],
    syllables: 2,
    breakdown: ['ən', 'd͡ʒaːn'],
    nucleus: 'aː',
    coda: 'n',
    rhymeKey: 'aːn',
    register: 'common',
    meaning: 'stranger, unknown',
    variants: ['anjaan'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'शबनम',
    roman: ['shabnam'],
    urdu: 'شبنم',
    pronunciations: ['ʃəb.nəm'],
    syllables: 2,
    breakdown: ['ʃəb', 'nəm'],
    nucleus: 'ə',
    coda: 'm',
    rhymeKey: 'əm',
    register: 'poetic',
    meaning: 'dewdrops',
    variants: ['shabnam'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'मरहम',
    roman: ['marham'],
    urdu: 'مرہم',
    pronunciations: ['mər.ɦəm'],
    syllables: 2,
    breakdown: ['mər', 'ɦəm'],
    nucleus: 'ə',
    coda: 'm',
    rhymeKey: 'əm',
    register: 'poetic',
    meaning: 'balm, healing salve',
    variants: ['marham'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'हमदम',
    roman: ['hamdam'],
    urdu: 'ہمدم',
    pronunciations: ['ɦəm.d̪əm'],
    syllables: 2,
    breakdown: ['ɦəm', 'd̪əm'],
    nucleus: 'ə',
    coda: 'm',
    rhymeKey: 'əm',
    register: 'poetic',
    meaning: 'intimate companion',
    variants: ['hamdam'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'मौसम',
    roman: ['mausam', 'mosam'],
    urdu: 'موسم',
    pronunciations: ['mɔː.səm'],
    syllables: 2,
    breakdown: ['mɔː', 'səm'],
    nucleus: 'ə',
    coda: 'm',
    rhymeKey: 'əm',
    register: 'common',
    meaning: 'weather, season',
    variants: ['mausam'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'रेशम',
    roman: ['resham'],
    urdu: 'ریشم',
    pronunciations: ['reː.ʃəm'],
    syllables: 2,
    breakdown: ['reː', 'ʃəm'],
    nucleus: 'ə',
    coda: 'm',
    rhymeKey: 'əm',
    register: 'poetic',
    meaning: 'silk',
    variants: ['resham'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'बरसात',
    roman: ['barsaat', 'barsat'],
    urdu: 'برسات',
    pronunciations: ['bər.saːt̪'],
    syllables: 2,
    breakdown: ['bər', 'saːt̪'],
    nucleus: 'aː',
    coda: 't̪',
    rhymeKey: 'aːt̪',
    register: 'common',
    meaning: 'rain, monsoon',
    variants: ['barsaat'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'मुलाक़ात',
    roman: ['mulaqaat', 'mulakat'],
    urdu: 'ملاقات',
    pronunciations: ['mʊ.laː.qaːt̪', 'mʊ.laː.kaːt̪'],
    syllables: 3,
    breakdown: ['mʊ', 'laː', 'qaːt̪'],
    nucleus: 'aː',
    coda: 't̪',
    rhymeKey: 'aːt̪',
    register: 'poetic',
    meaning: 'meeting, rendezvous',
    variants: ['mulaqaat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'औक़ात',
    roman: ['auqaat', 'aukat'],
    urdu: 'اوقات',
    pronunciations: ['ɔː.qaːt̪', 'ɔː.kaːt̪'],
    syllables: 2,
    breakdown: ['ɔː', 'qaːt̪'],
    nucleus: 'aː',
    coda: 't̪',
    rhymeKey: 'aːt̪',
    register: 'common',
    meaning: 'status, capacity, worth',
    variants: ['auqaat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'हालात',
    roman: ['halaat', 'halat'],
    urdu: 'حالات',
    pronunciations: ['ɦaː.laːt̪'],
    syllables: 2,
    breakdown: ['ɦaː', 'laːt̪'],
    nucleus: 'aː',
    coda: 't̪',
    rhymeKey: 'aːt̪',
    register: 'common',
    meaning: 'circumstances, condition',
    variants: ['halaat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'बात',
    roman: ['baat', 'bat'],
    urdu: 'بات',
    pronunciations: ['baːt̪'],
    syllables: 1,
    breakdown: ['baːt̪'],
    nucleus: 'aː',
    coda: 't̪',
    rhymeKey: 'aːt̪',
    register: 'common',
    meaning: 'talk, matter, point',
    variants: ['baat'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'साथ',
    roman: ['saath', 'sat'],
    urdu: 'ساتھ',
    pronunciations: ['saːt̪ʰ'],
    syllables: 1,
    breakdown: ['saːt̪ʰ'],
    nucleus: 'aː',
    coda: 't̪ʰ',
    rhymeKey: 'aːt̪ʰ',
    register: 'common',
    meaning: 'together, company',
    variants: ['saath'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'हाथ',
    roman: ['haath', 'hath'],
    urdu: 'ہاتھ',
    pronunciations: ['ɦaːt̪ʰ'],
    syllables: 1,
    breakdown: ['ɦaːt̪ʰ'],
    nucleus: 'aː',
    coda: 't̪ʰ',
    rhymeKey: 'aːt̪ʰ',
    register: 'common',
    meaning: 'hand',
    variants: ['haath'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'माथ',
    roman: ['maath', 'math'],
    urdu: 'ماتھ',
    pronunciations: ['maːt̪ʰ'],
    syllables: 1,
    breakdown: ['maːt̪ʰ'],
    nucleus: 'aː',
    coda: 't̪ʰ',
    rhymeKey: 'aːt̪ʰ',
    register: 'poetic',
    meaning: 'forehead',
    variants: ['maath'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'नाथ',
    roman: ['naath', 'nath'],
    urdu: 'ناتھ',
    pronunciations: ['naːt̪ʰ'],
    syllables: 1,
    breakdown: ['naːt̪ʰ'],
    nucleus: 'aː',
    coda: 't̪ʰ',
    rhymeKey: 'aːt̪ʰ',
    register: 'poetic',
    meaning: 'master, protector',
    variants: ['naath'],
    origin: 'Sanskrit'
  },
  {
    devanagari: 'गाथ',
    roman: ['gaath', 'gath'],
    urdu: 'گاتھ',
    pronunciations: ['ɡaːt̪ʰ'],
    syllables: 1,
    breakdown: ['ɡaːt̪ʰ'],
    nucleus: 'aː',
    coda: 't̪ʰ',
    rhymeKey: 'aːt̪ʰ',
    register: 'literary',
    meaning: 'song, legend, narrative',
    variants: ['gaath'],
    origin: 'Sanskrit'
  }
];
