import { GoldWordEntry } from './words-gold';

export const GOLD_WORDS_PART2: GoldWordEntry[] = [
  // =========================================================================
  // 8. BODY, SENSATIONS & ANATOMY (40 WORDS)
  // =========================================================================
  {
    devanagari: 'आँख',
    roman: ['aankh', 'aank'],
    urdu: 'آنکھ',
    pronunciations: ['ãːkʰ'],
    syllables: 1,
    breakdown: ['ãːkʰ'],
    nucleus: 'ãː',
    coda: 'kʰ',
    rhymeKey: 'ãːkʰ',
    register: 'common',
    meaning: 'eye',
    variants: ['aankh'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'राख',
    roman: ['raakh', 'rakh'],
    urdu: 'راکھ',
    pronunciations: ['raːkʰ'],
    syllables: 1,
    breakdown: ['raːkʰ'],
    nucleus: 'aː',
    coda: 'kʰ',
    rhymeKey: 'aːkʰ',
    register: 'poetic',
    meaning: 'ash, cinder',
    variants: ['raakh'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'शाख',
    roman: ['shaakh', 'shakh'],
    urdu: 'شاخ',
    pronunciations: ['ʃaːx', 'ʃaːkʰ'],
    syllables: 1,
    breakdown: ['ʃaːx'],
    nucleus: 'aː',
    coda: 'x',
    rhymeKey: 'aːkʰ',
    register: 'poetic',
    meaning: 'branch, bough',
    variants: ['shaakh'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'कान',
    roman: ['kaan', 'kan'],
    urdu: 'کان',
    pronunciations: ['kaːn'],
    syllables: 1,
    breakdown: ['kaːn'],
    nucleus: 'aː',
    coda: 'n',
    rhymeKey: 'aːn',
    register: 'common',
    meaning: 'ear, mine',
    variants: ['kaan'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'नाक',
    roman: ['naak', 'nak'],
    urdu: 'ناک',
    pronunciations: ['naːk'],
    syllables: 1,
    breakdown: ['naːk'],
    nucleus: 'aː',
    coda: 'k',
    rhymeKey: 'aːk',
    register: 'common',
    meaning: 'nose, honor',
    variants: ['naak'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'खाक',
    roman: ['khaak', 'khak'],
    urdu: 'خاک',
    pronunciations: ['xaːk', 'kʰaːk'],
    syllables: 1,
    breakdown: ['xaːk'],
    nucleus: 'aː',
    coda: 'k',
    rhymeKey: 'aːk',
    register: 'poetic',
    meaning: 'dust, ashes, ruins',
    variants: ['khaak'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'पाक',
    roman: ['paak', 'pak'],
    urdu: 'پاک',
    pronunciations: ['paːk'],
    syllables: 1,
    breakdown: ['paːk'],
    nucleus: 'aː',
    coda: 'k',
    rhymeKey: 'aːk',
    register: 'poetic',
    meaning: 'pure, holy',
    variants: ['paak'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'सीना',
    roman: ['seena', 'sina'],
    urdu: 'سینہ',
    pronunciations: ['siː.naː'],
    syllables: 2,
    breakdown: ['siː', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'iːnaː',
    register: 'poetic',
    meaning: 'chest, bosom',
    variants: ['seena'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'जीना',
    roman: ['jeena', 'jina'],
    urdu: 'جینا',
    pronunciations: ['d͡ʒiː.naː'],
    syllables: 2,
    breakdown: ['d͡ʒiː', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'iːnaː',
    register: 'common',
    meaning: 'to live, stairs',
    variants: ['jeena'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'पीना',
    roman: ['peena', 'pina'],
    urdu: 'پینا',
    pronunciations: ['piː.naː'],
    syllables: 2,
    breakdown: ['piː', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'iːnaː',
    register: 'common',
    meaning: 'to drink',
    variants: ['peena'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'पसीना',
    roman: ['paseena', 'pasina'],
    urdu: 'پسینہ',
    pronunciations: ['pə.siː.naː'],
    syllables: 3,
    breakdown: ['pə', 'siː', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'iːnaː',
    register: 'common',
    meaning: 'sweat, perspiration',
    variants: ['paseena'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'नगीना',
    roman: ['nageena', 'nagina'],
    urdu: 'نگینہ',
    pronunciations: ['nə.ɡiː.naː'],
    syllables: 3,
    breakdown: ['nə', 'ɡiː', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'iːnaː',
    register: 'poetic',
    meaning: 'gem, jewel',
    variants: ['nageena'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'महीना',
    roman: ['maheena', 'mahina'],
    urdu: 'مہینہ',
    pronunciations: ['mə.ɦiː.naː'],
    syllables: 3,
    breakdown: ['mə', 'ɦiː', 'naː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'iːnaː',
    register: 'common',
    meaning: 'month',
    variants: ['maheena'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'साँस',
    roman: ['saans', 'sans'],
    urdu: 'سانس',
    pronunciations: ['sãːs'],
    syllables: 1,
    breakdown: ['sãːs'],
    nucleus: 'ãː',
    coda: 's',
    rhymeKey: 'ãːs',
    register: 'common',
    meaning: 'breath',
    variants: ['saans'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'बाँस',
    roman: ['baans', 'bans'],
    urdu: 'بانس',
    pronunciations: ['bãːs'],
    syllables: 1,
    breakdown: ['bãːs'],
    nucleus: 'ãː',
    coda: 's',
    rhymeKey: 'ãːs',
    register: 'common',
    meaning: 'bamboo',
    variants: ['baans'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'फाँस',
    roman: ['phaans', 'fans'],
    urdu: 'پھانس',
    pronunciations: ['pʰãːs'],
    syllables: 1,
    breakdown: ['pʰãːs'],
    nucleus: 'ãː',
    coda: 's',
    rhymeKey: 'ãːs',
    register: 'common',
    meaning: 'splinter, trap',
    variants: ['phaans'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'खून',
    roman: ['khoon', 'khun'],
    urdu: 'خون',
    pronunciations: ['xuːn', 'kʰuːn'],
    syllables: 1,
    breakdown: ['xuːn'],
    nucleus: 'uː',
    coda: 'n',
    rhymeKey: 'uːn',
    register: 'common',
    meaning: 'blood, murder',
    variants: ['khoon'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'कानून',
    roman: ['kanoon', 'qanoon'],
    urdu: 'قانون',
    pronunciations: ['qaː.nuːn', 'kaː.nuːn'],
    syllables: 2,
    breakdown: ['qaː', 'nuːn'],
    nucleus: 'uː',
    coda: 'n',
    rhymeKey: 'uːn',
    register: 'common',
    meaning: 'law, justice',
    variants: ['kanoon', 'qanoon'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'मजनूँ',
    roman: ['majnu', 'majnoon'],
    urdu: 'مجنوں',
    pronunciations: ['məd͡ʒ.nũː'],
    syllables: 2,
    breakdown: ['məd͡ʒ', 'nũː'],
    nucleus: 'ũː',
    coda: '',
    rhymeKey: 'nũː',
    register: 'poetic',
    meaning: 'crazed lover, Majnun',
    variants: ['majnu'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'जिगर',
    roman: ['jigar'],
    urdu: 'جگر',
    pronunciations: ['d͡ʒɪ.ɡər'],
    syllables: 2,
    breakdown: ['d͡ʒɪ', 'ɡər'],
    nucleus: 'ə',
    coda: 'r',
    rhymeKey: 'ər',
    register: 'poetic',
    meaning: 'liver, heart, guts, courage',
    variants: ['jigar'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'नब्ज़',
    roman: ['nabz'],
    urdu: 'نبض',
    pronunciations: ['nəbz'],
    syllables: 1,
    breakdown: ['nəbz'],
    nucleus: 'ə',
    coda: 'bz',
    rhymeKey: 'əbz',
    register: 'poetic',
    meaning: 'pulse',
    variants: ['nabz'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'लफ़्ज़',
    roman: ['lafz'],
    urdu: 'لفظ',
    pronunciations: ['ləfz'],
    syllables: 1,
    breakdown: ['ləfz'],
    nucleus: 'ə',
    coda: 'fz',
    rhymeKey: 'əfz',
    register: 'poetic',
    meaning: 'word',
    variants: ['lafz'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'हर्फ़',
    roman: ['harf'],
    urdu: 'حرف',
    pronunciations: ['ɦərf'],
    syllables: 1,
    breakdown: ['ɦərf'],
    nucleus: 'ə',
    coda: 'rf',
    rhymeKey: 'ərf',
    register: 'literary',
    meaning: 'letter, character, blame',
    variants: ['harf'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'ज़ुल्फ़',
    roman: ['zulf'],
    urdu: 'زلف',
    pronunciations: ['zʊlf'],
    syllables: 1,
    breakdown: ['zʊlf'],
    nucleus: 'ʊ',
    coda: 'lf',
    rhymeKey: 'ʊlf',
    register: 'poetic',
    meaning: 'tress, lock of hair',
    variants: ['zulf'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'पेशानी',
    roman: ['peshani'],
    urdu: 'پیشانی',
    pronunciations: ['peː.ʃaː.niː'],
    syllables: 3,
    breakdown: ['peː', 'ʃaː', 'niː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'aːniː',
    register: 'poetic',
    meaning: 'forehead, brow',
    variants: ['peshani'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'होश',
    roman: ['hosh'],
    urdu: 'ہوش',
    pronunciations: ['ɦoːʃ'],
    syllables: 1,
    breakdown: ['ɦoːʃ'],
    nucleus: 'oː',
    coda: 'ʃ',
    rhymeKey: 'oːʃ',
    register: 'common',
    meaning: 'senses, consciousness',
    variants: ['hosh'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'जोश',
    roman: ['josh'],
    urdu: 'جوش',
    pronunciations: ['d͡ʒoːʃ'],
    syllables: 1,
    breakdown: ['d͡ʒoːʃ'],
    nucleus: 'oː',
    coda: 'ʃ',
    rhymeKey: 'oːʃ',
    register: 'common',
    meaning: 'enthusiasm, passion, heat',
    variants: ['josh'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'मदहोश',
    roman: ['madhosh'],
    urdu: 'مدہوش',
    pronunciations: ['məd̪.ɦoːʃ'],
    syllables: 2,
    breakdown: ['məd̪', 'ɦoːʃ'],
    nucleus: 'oː',
    coda: 'ʃ',
    rhymeKey: 'oːʃ',
    register: 'poetic',
    meaning: 'intoxicated, ecstatic',
    variants: ['madhosh'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'ख़ामोश',
    roman: ['khamosh'],
    urdu: 'خاموش',
    pronunciations: ['xaː.moːʃ', 'kʰaː.moːʃ'],
    syllables: 2,
    breakdown: ['xaː', 'moːʃ'],
    nucleus: 'oː',
    coda: 'ʃ',
    rhymeKey: 'oːʃ',
    register: 'common',
    meaning: 'silent, quiet',
    variants: ['khamosh'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'आगोश',
    roman: ['aagosh', 'agosh'],
    urdu: 'آغوش',
    pronunciations: ['aː.ɣoːʃ', 'aː.ɡoːʃ'],
    syllables: 2,
    breakdown: ['aː', 'ɣoːʃ'],
    nucleus: 'oː',
    coda: 'ʃ',
    rhymeKey: 'oːʃ',
    register: 'poetic',
    meaning: 'embrace, lap',
    variants: ['aagosh'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'सरगोशी',
    roman: ['sargoshi'],
    urdu: 'سرگوشی',
    pronunciations: ['sər.ɡoː.ʃiː'],
    syllables: 3,
    breakdown: ['sər', 'ɡoː', 'ʃiː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'oːʃiː',
    register: 'poetic',
    meaning: 'whisper',
    variants: ['sargoshi'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'ख़ामोशी',
    roman: ['khamoshi'],
    urdu: 'خاموشی',
    pronunciations: ['xaː.moː.ʃiː'],
    syllables: 3,
    breakdown: ['xaː', 'moː', 'ʃiː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'oːʃiː',
    register: 'poetic',
    meaning: 'silence',
    variants: ['khamoshi'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'मदहोशी',
    roman: ['madhoshi'],
    urdu: 'مدہوشی',
    pronunciations: ['məd̪.ɦoː.ʃiː'],
    syllables: 3,
    breakdown: ['məd̪', 'ɦoː', 'ʃiː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'oːʃiː',
    register: 'poetic',
    meaning: 'intoxication, trance',
    variants: ['madhoshi'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'रूह',
    roman: ['rooh', 'ruh'],
    urdu: 'روح',
    pronunciations: ['ruːɦ'],
    syllables: 1,
    breakdown: ['ruːɦ'],
    nucleus: 'uː',
    coda: 'ɦ',
    rhymeKey: 'uːɦ',
    register: 'poetic',
    meaning: 'soul, spirit',
    variants: ['rooh'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'जिस्म',
    roman: ['jism'],
    urdu: 'جسم',
    pronunciations: ['d͡ʒɪsm'],
    syllables: 1,
    breakdown: ['d͡ʒɪsm'],
    nucleus: 'ɪ',
    coda: 'sm',
    rhymeKey: 'ɪsm',
    register: 'poetic',
    meaning: 'body, physique',
    variants: ['jism'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'इस्म',
    roman: ['ism'],
    urdu: 'اسم',
    pronunciations: ['ɪsm'],
    syllables: 1,
    breakdown: ['ɪsm'],
    nucleus: 'ɪ',
    coda: 'sm',
    rhymeKey: 'ɪsm',
    register: 'literary',
    meaning: 'name, noun, divine name',
    variants: ['ism'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'तिलिस्म',
    roman: ['tilism', 'tilasm'],
    urdu: 'طلسم',
    pronunciations: ['t̪ɪ.lɪsm'],
    syllables: 2,
    breakdown: ['t̪ɪ', 'lɪsm'],
    nucleus: 'ɪ',
    coda: 'sm',
    rhymeKey: 'ɪsm',
    register: 'poetic',
    meaning: 'enchantment, magic talisman',
    variants: ['tilism'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'रंग',
    roman: ['rang'],
    urdu: 'رنگ',
    pronunciations: ['rəŋɡ'],
    syllables: 1,
    breakdown: ['rəŋɡ'],
    nucleus: 'ə',
    coda: 'ŋɡ',
    rhymeKey: 'əŋɡ',
    register: 'common',
    meaning: 'color, hue',
    variants: ['rang'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'अंग',
    roman: ['ang'],
    urdu: 'انگ',
    pronunciations: ['əŋɡ'],
    syllables: 1,
    breakdown: ['əŋɡ'],
    nucleus: 'ə',
    coda: 'ŋɡ',
    rhymeKey: 'əŋɡ',
    register: 'common',
    meaning: 'body part, limb',
    variants: ['ang'],
    origin: 'Sanskrit'
  },
  {
    devanagari: 'ढंग',
    roman: ['dhang'],
    urdu: 'ڈھنگ',
    pronunciations: ['ɖʱəŋɡ'],
    syllables: 1,
    breakdown: ['ɖʱəŋɡ'],
    nucleus: 'ə',
    coda: 'ŋɡ',
    rhymeKey: 'əŋɡ',
    register: 'common',
    meaning: 'manner, method, style',
    variants: ['dhang'],
    origin: 'Hindustani'
  },

  // =========================================================================
  // 9. SOCIETY, POWER & CONFLICT (40 WORDS)
  // =========================================================================
  {
    devanagari: 'जंग',
    roman: ['jang'],
    urdu: 'جنگ',
    pronunciations: ['d͡ʒəŋɡ'],
    syllables: 1,
    breakdown: ['d͡ʒəŋɡ'],
    nucleus: 'ə',
    coda: 'ŋɡ',
    rhymeKey: 'əŋɡ',
    register: 'common',
    meaning: 'war, battle',
    variants: ['jang'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'तंग',
    roman: ['tang'],
    urdu: 'تنگ',
    pronunciations: ['t̪əŋɡ'],
    syllables: 1,
    breakdown: ['t̪əŋɡ'],
    nucleus: 'ə',
    coda: 'ŋɡ',
    rhymeKey: 'əŋɡ',
    register: 'common',
    meaning: 'narrow, harassed, fed up',
    variants: ['tang'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'संग',
    roman: ['sang'],
    urdu: 'سنگ',
    pronunciations: ['səŋɡ'],
    syllables: 1,
    breakdown: ['səŋɡ'],
    nucleus: 'ə',
    coda: 'ŋɡ',
    rhymeKey: 'əŋɡ',
    register: 'common',
    meaning: 'along with, stone',
    variants: ['sang'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'उमंग',
    roman: ['umang'],
    urdu: 'امنگ',
    pronunciations: ['ʊ.məŋɡ'],
    syllables: 2,
    breakdown: ['ʊ', 'məŋɡ'],
    nucleus: 'ə',
    coda: 'ŋɡ',
    rhymeKey: 'əŋɡ',
    register: 'poetic',
    meaning: 'ardor, enthusiasm, zest',
    variants: ['umang'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'तरंग',
    roman: ['tarang'],
    urdu: 'ترنگ',
    pronunciations: ['t̪ə.rəŋɡ'],
    syllables: 2,
    breakdown: ['t̪ə', 'rəŋɡ'],
    nucleus: 'ə',
    coda: 'ŋɡ',
    rhymeKey: 'əŋɡ',
    register: 'poetic',
    meaning: 'wave, ripple, impulse',
    variants: ['tarang'],
    origin: 'Sanskrit'
  },
  {
    devanagari: 'अमन',
    roman: ['aman'],
    urdu: 'امن',
    pronunciations: ['ə.mən'],
    syllables: 2,
    breakdown: ['ə', 'mən'],
    nucleus: 'ə',
    coda: 'n',
    rhymeKey: 'ən',
    register: 'poetic',
    meaning: 'peace, tranquility',
    variants: ['aman'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'चमन',
    roman: ['chaman'],
    urdu: 'چمن',
    pronunciations: ['t͡ʃə.mən'],
    syllables: 2,
    breakdown: ['t͡ʃə', 'mən'],
    nucleus: 'ə',
    coda: 'n',
    rhymeKey: 'ən',
    register: 'poetic',
    meaning: 'garden, verdant lawn',
    variants: ['chaman'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'वतन',
    roman: ['watan', 'vatan'],
    urdu: 'وطن',
    pronunciations: ['ʋə.t̪ən'],
    syllables: 2,
    breakdown: ['ʋə', 't̪ən'],
    nucleus: 'ə',
    coda: 'n',
    rhymeKey: 'ən',
    register: 'common',
    meaning: 'homeland, nation',
    variants: ['watan'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'कफ़न',
    roman: ['kafan', 'qafan'],
    urdu: 'کفن',
    pronunciations: ['kə.fən', 'kə.pʰən'],
    syllables: 2,
    breakdown: ['kə', 'fən'],
    nucleus: 'ə',
    coda: 'n',
    rhymeKey: 'ən',
    register: 'poetic',
    meaning: 'shroud, winding sheet',
    variants: ['kafan'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'दफ़न',
    roman: ['dafan'],
    urdu: 'دفن',
    pronunciations: ['d̪ə.fən', 'd̪ə.pʰən'],
    syllables: 2,
    breakdown: ['d̪ə', 'fən'],
    nucleus: 'ə',
    coda: 'n',
    rhymeKey: 'ən',
    register: 'poetic',
    meaning: 'buried, concealed',
    variants: ['dafan'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'तख़्त',
    roman: ['takht'],
    urdu: 'تخت',
    pronunciations: ['t̪əxt̪', 't̪əkʰt̪'],
    syllables: 1,
    breakdown: ['t̪əxt̪'],
    nucleus: 'ə',
    coda: 'xt̪',
    rhymeKey: 'əxt̪',
    register: 'poetic',
    meaning: 'throne',
    variants: ['takht'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'सख़्त',
    roman: ['sakht'],
    urdu: 'سخت',
    pronunciations: ['səxt̪', 'səkʰt̪'],
    syllables: 1,
    breakdown: ['səxt̪'],
    nucleus: 'ə',
    coda: 'xt̪',
    rhymeKey: 'əxt̪',
    register: 'common',
    meaning: 'hard, severe, rigid',
    variants: ['sakht'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'वक़्त',
    roman: ['waqt', 'vakt'],
    urdu: 'وقت',
    pronunciations: ['ʋəkt̪', 'ʋəqt̪'],
    syllables: 1,
    breakdown: ['ʋəkt̪'],
    nucleus: 'ə',
    coda: 'kt̪',
    rhymeKey: 'əkt̪',
    register: 'common',
    meaning: 'time',
    variants: ['waqt'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'ताज',
    roman: ['taaj', 'taj'],
    urdu: 'تاج',
    pronunciations: ['t̪aːd͡ʒ'],
    syllables: 1,
    breakdown: ['t̪aːd͡ʒ'],
    nucleus: 'aː',
    coda: 'd͡ʒ',
    rhymeKey: 'aːd͡ʒ',
    register: 'common',
    meaning: 'crown',
    variants: ['taaj'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'राज',
    roman: ['raaj', 'raj'],
    urdu: 'راج',
    pronunciations: ['raːd͡ʒ'],
    syllables: 1,
    breakdown: ['raːd͡ʒ'],
    nucleus: 'aː',
    coda: 'd͡ʒ',
    rhymeKey: 'aːd͡ʒ',
    register: 'common',
    meaning: 'rule, reign, secret',
    variants: ['raaj'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'काज',
    roman: ['kaaj', 'kaj'],
    urdu: 'کاج',
    pronunciations: ['kaːd͡ʒ'],
    syllables: 1,
    breakdown: ['kaːd͡ʒ'],
    nucleus: 'aː',
    coda: 'd͡ʒ',
    rhymeKey: 'aːd͡ʒ',
    register: 'common',
    meaning: 'work, deed',
    variants: ['kaaj'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'लाज',
    roman: ['laaj', 'laj'],
    urdu: 'لاج',
    pronunciations: ['laːd͡ʒ'],
    syllables: 1,
    breakdown: ['laːd͡ʒ'],
    nucleus: 'aː',
    coda: 'd͡ʒ',
    rhymeKey: 'aːd͡ʒ',
    register: 'poetic',
    meaning: 'modesty, shame, honor',
    variants: ['laaj'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'इलाज',
    roman: ['ilaaj', 'ilaj'],
    urdu: 'علاج',
    pronunciations: ['ɪ.laːd͡ʒ'],
    syllables: 2,
    breakdown: ['ɪ', 'laːd͡ʒ'],
    nucleus: 'aː',
    coda: 'd͡ʒ',
    rhymeKey: 'aːd͡ʒ',
    register: 'common',
    meaning: 'cure, remedy',
    variants: ['ilaaj'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'मोहताज',
    roman: ['mohtaaj', 'mohtaj'],
    urdu: 'محتاج',
    pronunciations: ['moːɦ.t̪aːd͡ʒ'],
    syllables: 2,
    breakdown: ['moːɦ', 't̪aːd͡ʒ'],
    nucleus: 'aː',
    coda: 'd͡ʒ',
    rhymeKey: 'aːd͡ʒ',
    register: 'poetic',
    meaning: 'dependent, needy',
    variants: ['mohtaaj'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'हुकूमत',
    roman: ['hukumat', 'hukoomat'],
    urdu: 'حکومت',
    pronunciations: ['ɦʊ.kuː.mət̪'],
    syllables: 3,
    breakdown: ['ɦʊ', 'kuː', 'mət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'common',
    meaning: 'governance, regime',
    variants: ['hukumat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'गुलामी',
    roman: ['gulami'],
    urdu: 'غلامی',
    pronunciations: ['ɡʊ.laː.miː'],
    syllables: 3,
    breakdown: ['ɡʊ', 'laː', 'miː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'aːmiː',
    register: 'common',
    meaning: 'slavery, bondage',
    variants: ['gulami'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'सलाम',
    roman: ['salaam', 'salam'],
    urdu: 'سلام',
    pronunciations: ['sə.laːm'],
    syllables: 2,
    breakdown: ['sə', 'laːm'],
    nucleus: 'aː',
    coda: 'm',
    rhymeKey: 'aːm',
    register: 'common',
    meaning: 'salute, greeting',
    variants: ['salaam'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'कलाम',
    roman: ['kalaam', 'kalam'],
    urdu: 'کلام',
    pronunciations: ['kə.laːm'],
    syllables: 2,
    breakdown: ['kə', 'laːm'],
    nucleus: 'aː',
    coda: 'm',
    rhymeKey: 'aːm',
    register: 'poetic',
    meaning: 'poetry, discourse, speech',
    variants: ['kalaam'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'गुलाम',
    roman: ['gulaam', 'gulam'],
    urdu: 'غلام',
    pronunciations: ['ɡʊ.laːm'],
    syllables: 2,
    breakdown: ['ɡʊ', 'laːm'],
    nucleus: 'aː',
    coda: 'm',
    rhymeKey: 'aːm',
    register: 'common',
    meaning: 'slave, servant',
    variants: ['gulaam'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'मुक़ाम',
    roman: ['muqaam', 'mukam'],
    urdu: 'مقام',
    pronunciations: ['mʊ.qaːm', 'mʊ.kaːm'],
    syllables: 2,
    breakdown: ['mʊ', 'qaːm'],
    nucleus: 'aː',
    coda: 'm',
    rhymeKey: 'aːm',
    register: 'poetic',
    meaning: 'station, pedestal, stature',
    variants: ['muqaam'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'अंजाम',
    roman: ['anjaam', 'anjam'],
    urdu: 'انجام',
    pronunciations: ['ən.d͡ʒaːm'],
    syllables: 2,
    breakdown: ['ən', 'd͡ʒaːm'],
    nucleus: 'aː',
    coda: 'm',
    rhymeKey: 'aːm',
    register: 'common',
    meaning: 'consequence, fate, end',
    variants: ['anjaam'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'पैग़ाम',
    roman: ['paigaam', 'paigham'],
    urdu: 'پیغام',
    pronunciations: ['pɛː.ɣaːm', 'pɛː.ɡaːm'],
    syllables: 2,
    breakdown: ['pɛː', 'ɣaːm'],
    nucleus: 'aː',
    coda: 'm',
    rhymeKey: 'aːm',
    register: 'poetic',
    meaning: 'message, tidings',
    variants: ['paigaam'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'आज़ादी',
    roman: ['aazaadi', 'azadi'],
    urdu: 'آزادی',
    pronunciations: ['aː.zaː.d̪iː'],
    syllables: 3,
    breakdown: ['aː', 'zaː', 'd̪iː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'aːd̪iː',
    register: 'common',
    meaning: 'freedom, liberty',
    variants: ['aazaadi'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'बरबादी',
    roman: ['barbaadi', 'barbadi'],
    urdu: 'بربادی',
    pronunciations: ['bər.baː.d̪iː'],
    syllables: 3,
    breakdown: ['bər', 'baː', 'd̪iː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'aːd̪iː',
    register: 'poetic',
    meaning: 'ruin, destruction',
    variants: ['barbaadi'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'आबादी',
    roman: ['aabaadi', 'abadi'],
    urdu: 'آبادی',
    pronunciations: ['aː.baː.d̪iː'],
    syllables: 3,
    breakdown: ['aː', 'baː', 'd̪iː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'aːd̪iː',
    register: 'common',
    meaning: 'population, habitation',
    variants: ['aabaadi'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'इंक़लाब',
    roman: ['inqilaab', 'inkilab'],
    urdu: 'انقلاب',
    pronunciations: ['ɪn.qɪ.laːb', 'ɪn.kɪ.laːb'],
    syllables: 3,
    breakdown: ['ɪn', 'qɪ', 'laːb'],
    nucleus: 'aː',
    coda: 'b',
    rhymeKey: 'aːb',
    register: 'poetic',
    meaning: 'revolution',
    variants: ['inqilaab'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'बगावत',
    roman: ['baghawat', 'bagawat'],
    urdu: 'بغاوت',
    pronunciations: ['bə.ɣaː.ʋət̪', 'bə.ɡaː.ʋət̪'],
    syllables: 3,
    breakdown: ['bə', 'ɣaː', 'ʋət̪'],
    nucleus: 'ə',
    coda: 't̪',
    rhymeKey: 'ət̪',
    register: 'common',
    meaning: 'rebellion, mutiny',
    variants: ['baghawat'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'फ़ौज',
    roman: ['fauj'],
    urdu: 'فوج',
    pronunciations: ['fɔːd͡ʒ', 'pʰɔːd͡ʒ'],
    syllables: 1,
    breakdown: ['fɔːd͡ʒ'],
    nucleus: 'ɔː',
    coda: 'd͡ʒ',
    rhymeKey: 'ɔːd͡ʒ',
    register: 'common',
    meaning: 'army, squad',
    variants: ['fauj'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'मौज',
    roman: ['mauj'],
    urdu: 'موج',
    pronunciations: ['mɔːd͡ʒ'],
    syllables: 1,
    breakdown: ['mɔːd͡ʒ'],
    nucleus: 'ɔː',
    coda: 'd͡ʒ',
    rhymeKey: 'ɔːd͡ʒ',
    register: 'common',
    meaning: 'fun, merrymaking, surge',
    variants: ['mauj'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'हथियार',
    roman: ['hathiyaar', 'hathiyar'],
    urdu: 'ہتھیار',
    pronunciations: ['ɦə.t̪ʰɪ.jaːr'],
    syllables: 3,
    breakdown: ['ɦə', 't̪ʰɪ', 'jaːr'],
    nucleus: 'aː',
    coda: 'r',
    rhymeKey: 'aːr',
    register: 'common',
    meaning: 'weapon, tool',
    variants: ['hathiyaar'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'तलवार',
    roman: ['talwaar', 'talwar'],
    urdu: 'تلوار',
    pronunciations: ['t̪əl.ʋaːr'],
    syllables: 2,
    breakdown: ['t̪əl', 'ʋaːr'],
    nucleus: 'aː',
    coda: 'r',
    rhymeKey: 'aːr',
    register: 'common',
    meaning: 'sword',
    variants: ['talwaar'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'ज़ुल्म',
    roman: ['zulm'],
    urdu: 'ظلم',
    pronunciations: ['zʊlm'],
    syllables: 1,
    breakdown: ['zʊlm'],
    nucleus: 'ʊ',
    coda: 'lm',
    rhymeKey: 'ʊlm',
    register: 'poetic',
    meaning: 'oppression, tyranny',
    variants: ['zulm'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'इंसाफ़',
    roman: ['insaaf', 'insaf'],
    urdu: 'انصاف',
    pronunciations: ['ɪn.saːf'],
    syllables: 2,
    breakdown: ['ɪn', 'saːf'],
    nucleus: 'aː',
    coda: 'f',
    rhymeKey: 'aːf',
    register: 'common',
    meaning: 'justice, equity',
    variants: ['insaaf'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'साफ़',
    roman: ['saaf', 'saf'],
    urdu: 'صاف',
    pronunciations: ['saːf'],
    syllables: 1,
    breakdown: ['saːf'],
    nucleus: 'aː',
    coda: 'f',
    rhymeKey: 'aːf',
    register: 'common',
    meaning: 'clean, clear',
    variants: ['saaf'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'माफ़',
    roman: ['maaf', 'maf'],
    urdu: 'معاف',
    pronunciations: ['maːf'],
    syllables: 1,
    breakdown: ['maːf'],
    nucleus: 'aː',
    coda: 'f',
    rhymeKey: 'aːf',
    register: 'common',
    meaning: 'forgiven, excused',
    variants: ['maaf'],
    origin: 'Perso-Arabic'
  },

  // =========================================================================
  // 10. OBJECTS, FOOD & HOME (45 WORDS)
  // =========================================================================
  {
    devanagari: 'रोटी',
    roman: ['roti'],
    urdu: 'روٹی',
    pronunciations: ['roː.ʈiː'],
    syllables: 2,
    breakdown: ['roː', 'ʈiː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'ʈiː',
    register: 'common',
    meaning: 'bread, sustenance',
    variants: ['roti'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'बोटी',
    roman: ['boti'],
    urdu: 'بوٹی',
    pronunciations: ['boː.ʈiː'],
    syllables: 2,
    breakdown: ['boː', 'ʈiː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'ʈiː',
    register: 'common',
    meaning: 'morsel, meat chunk',
    variants: ['boti'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'चोटी',
    roman: ['choti'],
    urdu: 'چوٹی',
    pronunciations: ['t͡ʃoː.ʈiː'],
    syllables: 2,
    breakdown: ['t͡ʃoː', 'ʈiː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'ʈiː',
    register: 'common',
    meaning: 'peak, summit, braid',
    variants: ['choti'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'मोटी',
    roman: ['moti'],
    urdu: 'موٹی',
    pronunciations: ['moː.ʈiː'],
    syllables: 2,
    breakdown: ['moː', 'ʈiː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'ʈiː',
    register: 'common',
    meaning: 'thick, fat',
    variants: ['moti'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'खोटी',
    roman: ['khoti'],
    urdu: 'کھوٹی',
    pronunciations: ['kʰoː.ʈiː'],
    syllables: 2,
    breakdown: ['kʰoː', 'ʈiː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'ʈiː',
    register: 'common',
    meaning: 'false, tainted, flawed',
    variants: ['khoti'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'कपड़ा',
    roman: ['kapda'],
    urdu: 'کپڑا',
    pronunciations: ['kəp.ɽaː'],
    syllables: 2,
    breakdown: ['kəp', 'ɽaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'ɽaː',
    register: 'common',
    meaning: 'cloth, clothing',
    variants: ['kapda'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'टुकड़ा',
    roman: ['tukda'],
    urdu: 'ٹکڑا',
    pronunciations: ['ʈʊk.ɽaː'],
    syllables: 2,
    breakdown: ['ʈʊk', 'ɽaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'ɽaː',
    register: 'common',
    meaning: 'piece, fragment',
    variants: ['tukda'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'मुखड़ा',
    roman: ['mukhda'],
    urdu: 'مکھڑا',
    pronunciations: ['mʊkʰ.ɽaː'],
    syllables: 2,
    breakdown: ['mʊkʰ', 'ɽaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'ɽaː',
    register: 'poetic',
    meaning: 'visage, chorus of song',
    variants: ['mukhda'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'झगड़ा',
    roman: ['jhagda'],
    urdu: 'جھگڑا',
    pronunciations: ['d͡ʒʱəɡ.ɽaː'],
    syllables: 2,
    breakdown: ['d͡ʒʱəɡ', 'ɽaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'ɽaː',
    register: 'common',
    meaning: 'quarrel, feud',
    variants: ['jhagda'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'दूध',
    roman: ['doodh', 'dudh'],
    urdu: 'دودھ',
    pronunciations: ['d̪uːd̪ʱ'],
    syllables: 1,
    breakdown: ['d̪uːd̪ʱ'],
    nucleus: 'uː',
    coda: 'd̪ʱ',
    rhymeKey: 'uːd̪ʱ',
    register: 'common',
    meaning: 'milk',
    variants: ['doodh'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'चाय',
    roman: ['chai'],
    urdu: 'چائے',
    pronunciations: ['t͡ʃaːɪ', 't͡ʃaːj'],
    syllables: 1,
    breakdown: ['t͡ʃaːj'],
    nucleus: 'aːɪ',
    coda: '',
    rhymeKey: 'aːj',
    register: 'common',
    meaning: 'tea',
    variants: ['chai'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'राय',
    roman: ['raay', 'rai'],
    urdu: 'رائے',
    pronunciations: ['raːɪ', 'raːj'],
    syllables: 1,
    breakdown: ['raːj'],
    nucleus: 'aːɪ',
    coda: '',
    rhymeKey: 'aːj',
    register: 'common',
    meaning: 'opinion, counsel',
    variants: ['raay'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'हाय',
    roman: ['haay', 'hai'],
    urdu: 'ہائے',
    pronunciations: ['ɦaːɪ', 'ɦaːj'],
    syllables: 1,
    breakdown: ['ɦaːj'],
    nucleus: 'aːɪ',
    coda: '',
    rhymeKey: 'aːj',
    register: 'poetic',
    meaning: 'sigh of grief, woe',
    variants: ['haay'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'काग़ज़',
    roman: ['kaghaz', 'kagaz'],
    urdu: 'کاغذ',
    pronunciations: ['qaː.ɣəz', 'kaː.ɡəz'],
    syllables: 2,
    breakdown: ['qaː', 'ɣəz'],
    nucleus: 'ə',
    coda: 'z',
    rhymeKey: 'əz',
    register: 'common',
    meaning: 'paper, parchment',
    variants: ['kaghaz'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'क़लम',
    roman: ['qalam', 'kalam'],
    urdu: 'قلم',
    pronunciations: ['qə.ləm', 'kə.ləm'],
    syllables: 2,
    breakdown: ['qə', 'ləm'],
    nucleus: 'ə',
    coda: 'm',
    rhymeKey: 'əm',
    register: 'common',
    meaning: 'pen, calligraphy reed',
    variants: ['qalam'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'दीवार',
    roman: ['deewar', 'diwar'],
    urdu: 'دیوار',
    pronunciations: ['d̪iː.ʋaːr'],
    syllables: 2,
    breakdown: ['d̪iː', 'ʋaːr'],
    nucleus: 'aː',
    coda: 'r',
    rhymeKey: 'aːr',
    register: 'common',
    meaning: 'wall',
    variants: ['deewar'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'खिड़की',
    roman: ['khidki'],
    urdu: 'کھڑکی',
    pronunciations: ['kʰɪɽ.kiː'],
    syllables: 2,
    breakdown: ['kʰɪɽ', 'kiː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'kiː',
    register: 'common',
    meaning: 'window',
    variants: ['khidki'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'गाड़ी',
    roman: ['gaadi', 'gadi'],
    urdu: 'گاڑی',
    pronunciations: ['ɡaː.ɽiː'],
    syllables: 2,
    breakdown: ['ɡaː', 'ɽiː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'ɽiː',
    register: 'common',
    meaning: 'car, vehicle',
    variants: ['gaadi'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'झाड़ी',
    roman: ['jhaadi'],
    urdu: 'جھاڑی',
    pronunciations: ['d͡ʒʱaː.ɽiː'],
    syllables: 2,
    breakdown: ['d͡ʒʱaː', 'ɽiː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'ɽiː',
    register: 'common',
    meaning: 'bush, thicket',
    variants: ['jhaadi'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'साड़ी',
    roman: ['saadi', 'saree'],
    urdu: 'ساڑی',
    pronunciations: ['saː.ɽiː'],
    syllables: 2,
    breakdown: ['saː', 'ɽiː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'ɽiː',
    register: 'common',
    meaning: 'sari attire',
    variants: ['saadi'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'सिक्का',
    roman: ['sikka'],
    urdu: 'سکہ',
    pronunciations: ['sɪk.kaː'],
    syllables: 2,
    breakdown: ['sɪk', 'kaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'kaː',
    register: 'common',
    meaning: 'coin, dominance',
    variants: ['sikka'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'इक्का',
    roman: ['ikka'],
    urdu: 'اکہ',
    pronunciations: ['ɪk.kaː'],
    syllables: 2,
    breakdown: ['ɪk', 'kaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'kaː',
    register: 'common',
    meaning: 'ace card, horse cart',
    variants: ['ikka'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'धक्का',
    roman: ['dhakka'],
    urdu: 'دھکا',
    pronunciations: ['d̪ʱək.kaː'],
    syllables: 2,
    breakdown: ['d̪ʱək', 'kaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'kaː',
    register: 'common',
    meaning: 'push, shock, jolt',
    variants: ['dhakka'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'पक्का',
    roman: ['pakka'],
    urdu: 'پکا',
    pronunciations: ['pək.kaː'],
    syllables: 2,
    breakdown: ['pək', 'kaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'kaː',
    register: 'common',
    meaning: 'solid, authentic, certain',
    variants: ['pakka'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'कच्चा',
    roman: ['kachcha', 'kacha'],
    urdu: 'کچا',
    pronunciations: ['kət͡ʃ.t͡ʃaː'],
    syllables: 2,
    breakdown: ['kət͡ʃ', 't͡ʃaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 't͡ʃaː',
    register: 'common',
    meaning: 'raw, novice',
    variants: ['kachcha'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'सच्चा',
    roman: ['sachcha', 'sacha'],
    urdu: 'سچا',
    pronunciations: ['sət͡ʃ.t͡ʃaː'],
    syllables: 2,
    breakdown: ['sət͡ʃ', 't͡ʃaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 't͡ʃaː',
    register: 'common',
    meaning: 'true, genuine',
    variants: ['sachcha'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'बच्चा',
    roman: ['bachcha', 'bacha'],
    urdu: 'بچہ',
    pronunciations: ['bət͡ʃ.t͡ʃaː'],
    syllables: 2,
    breakdown: ['bət͡ʃ', 't͡ʃaː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 't͡ʃaː',
    register: 'common',
    meaning: 'child, kid',
    variants: ['bachcha'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'नोट',
    roman: ['note'],
    urdu: 'نوٹ',
    pronunciations: ['noːʈ'],
    syllables: 1,
    breakdown: ['noːʈ'],
    nucleus: 'oː',
    coda: 'ʈ',
    rhymeKey: 'oːʈ',
    register: 'common',
    meaning: 'banknote, cash',
    variants: ['note'],
    origin: 'English'
  },
  {
    devanagari: 'वोट',
    roman: ['vote'],
    urdu: 'وووٹ',
    pronunciations: ['ʋoːʈ'],
    syllables: 1,
    breakdown: ['ʋoːʈ'],
    nucleus: 'oː',
    coda: 'ʈ',
    rhymeKey: 'oːʈ',
    register: 'common',
    meaning: 'vote',
    variants: ['vote'],
    origin: 'English'
  },
  {
    devanagari: 'चोट',
    roman: ['chot'],
    urdu: 'چوٹ',
    pronunciations: ['t͡ʃoːʈ'],
    syllables: 1,
    breakdown: ['t͡ʃoːʈ'],
    nucleus: 'oː',
    coda: 'ʈ',
    rhymeKey: 'oːʈ',
    register: 'common',
    meaning: 'injury, blow, bruise',
    variants: ['chot'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'ओट',
    roman: ['oat', 'ot'],
    urdu: 'اوٹ',
    pronunciations: ['oːʈ'],
    syllables: 1,
    breakdown: ['oːʈ'],
    nucleus: 'oː',
    coda: 'ʈ',
    rhymeKey: 'oːʈ',
    register: 'poetic',
    meaning: 'cover, veil, shelter',
    variants: ['oat'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'कोट',
    roman: ['coat', 'kot'],
    urdu: 'کوٹ',
    pronunciations: ['koːʈ'],
    syllables: 1,
    breakdown: ['koːʈ'],
    nucleus: 'oː',
    coda: 'ʈ',
    rhymeKey: 'oːʈ',
    register: 'common',
    meaning: 'coat, jacket',
    variants: ['coat'],
    origin: 'English'
  },
  {
    devanagari: 'चाबी',
    roman: ['chabi'],
    urdu: 'چابی',
    pronunciations: ['t͡ʃaː.biː'],
    syllables: 2,
    breakdown: ['t͡ʃaː', 'biː'],
    nucleus: 'iː',
    coda: '',
    rhymeKey: 'biː',
    register: 'common',
    meaning: 'key',
    variants: ['chabi'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'ताला',
    roman: ['tala'],
    urdu: 'تالا',
    pronunciations: ['t̪aː.laː'],
    syllables: 2,
    breakdown: ['t̪aː', 'laː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'laː',
    register: 'common',
    meaning: 'lock',
    variants: ['tala'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'प्याला',
    roman: ['pyala'],
    urdu: 'پیالہ',
    pronunciations: ['pjaː.laː'],
    syllables: 2,
    breakdown: ['pjaː', 'laː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'laː',
    register: 'poetic',
    meaning: 'cup, chalice',
    variants: ['pyala'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'उजाला',
    roman: ['ujala'],
    urdu: 'اجالا',
    pronunciations: ['ʊ.d͡ʒaː.laː'],
    syllables: 3,
    breakdown: ['ʊ', 'd͡ʒaː', 'laː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'laː',
    register: 'common',
    meaning: 'light, radiance',
    variants: ['ujala'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'निराला',
    roman: ['nirala'],
    urdu: 'نرالا',
    pronunciations: ['nɪ.raː.laː'],
    syllables: 3,
    breakdown: ['nɪ', 'raː', 'laː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'laː',
    register: 'poetic',
    meaning: 'unique, matchless',
    variants: ['nirala'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'दिवाला',
    roman: ['diwala'],
    urdu: 'دیوالہ',
    pronunciations: ['d̪ɪ.ʋaː.laː'],
    syllables: 3,
    breakdown: ['d̪ɪ', 'ʋaː', 'laː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'laː',
    register: 'common',
    meaning: 'bankruptcy',
    variants: ['diwala'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'मसाला',
    roman: ['masala'],
    urdu: 'مسالہ',
    pronunciations: ['mə.saː.laː'],
    syllables: 3,
    breakdown: ['mə', 'saː', 'laː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'laː',
    register: 'common',
    meaning: 'spice, gossip',
    variants: ['masala'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'गवाला',
    roman: ['gawala'],
    urdu: 'گوالہ',
    pronunciations: ['ɡə.ʋaː.laː'],
    syllables: 3,
    breakdown: ['ɡə', 'ʋaː', 'laː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'laː',
    register: 'common',
    meaning: 'milkman',
    variants: ['gawala'],
    origin: 'Hindustani'
  },
  {
    devanagari: 'हवाला',
    roman: ['hawala'],
    urdu: 'حوالہ',
    pronunciations: ['ɦə.ʋaː.laː'],
    syllables: 3,
    breakdown: ['ɦə', 'ʋaː', 'laː'],
    nucleus: 'aː',
    coda: '',
    rhymeKey: 'laː',
    register: 'common',
    meaning: 'reference, custody, illicit money transfer',
    variants: ['hawala'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'बर्फ',
    roman: ['barf'],
    urdu: 'برف',
    pronunciations: ['bərf'],
    syllables: 1,
    breakdown: ['bərf'],
    nucleus: 'ə',
    coda: 'rf',
    rhymeKey: 'ərf',
    register: 'common',
    meaning: 'ice, snow',
    variants: ['barf'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'फर्श',
    roman: ['farsh'],
    urdu: 'فرش',
    pronunciations: ['fərʃ'],
    syllables: 1,
    breakdown: ['fərʃ'],
    nucleus: 'ə',
    coda: 'rʃ',
    rhymeKey: 'ərʃ',
    register: 'poetic',
    meaning: 'floor, ground',
    variants: ['farsh'],
    origin: 'Perso-Arabic'
  },
  {
    devanagari: 'अर्श',
    roman: ['arsh'],
    urdu: 'عرش',
    pronunciations: ['ərʃ'],
    syllables: 1,
    breakdown: ['ərʃ'],
    nucleus: 'ə',
    coda: 'rʃ',
    rhymeKey: 'ərʃ',
    register: 'poetic',
    meaning: 'highest heaven, empyrean',
    variants: ['arsh'],
    origin: 'Perso-Arabic'
  }
];
